export const AUDIT_LOG = {
  TITLE: "Lịch sử hệ thống",
  TITLE_BADGE: "Lịch sử thao tác",
  EMPTY: "Chưa có lịch sử nào",
  FETCH_ERROR: "Không thể tải lịch sử hệ thống",
  LOG_ID: "Mã Log",
  ORDER_ID: "Mã Đơn hàng",
  EMPLOYEE_ID: "Mã Nhân viên",
  ACTION: "Hành động",
  NO_CHANGES: "Không có thay đổi",
  OLD_VALUE: "Giá trị cũ",
  NEW_VALUE: "Giá trị mới",
  ACTOR_LABEL: "Đối tượng",
  METADATA_LABEL: "Dữ liệu",
  CHANGE_DETAILS: "Chi tiết thay đổi",
  BEFORE_CHANGE: "Trước khi thay đổi",
  AFTER_CHANGE: "Sau khi thay đổi",
  CREATED_AT: "Thời gian",
  REASON: "Lý do / Ghi chú",
  PANEL_TITLE: "Khung audit log",
  PANEL_DESC:
    "Theo dõi các thao tác phát sinh trong hệ thống kèm người thực hiện, thời gian và dữ liệu thay đổi.",
  TIME: "Thời gian",
  ACTOR: "Người thực hiện",
  ACTOR_NAME: "Tên người thực hiện",
  ACTOR_ROLE: "Vai trò",
  ACTIONS_METADATA: "Hành động, lý do, metadata trước/sau",
  TIMELINE_TITLE: "Dòng thời gian gần nhất",
  EMPTY_TITLE: "Chọn một đơn để xem nhật ký thao tác",
  EMPTY_DESC: "Nhật ký thao tác sẽ hiển thị tại đây khi bạn chọn một đơn hàng.",
  GLOBAL_EMPTY_TITLE: "Chưa có nhật ký thao tác nào",
  GLOBAL_EMPTY_DESC:
    "Nhật ký thao tác của toàn bộ đơn hàng sẽ hiển thị tại đây khi hệ thống phát sinh thao tác mới.",
  ENTITY: "Thực thể",
  ENTITY_ID: "ID thực thể",
  SYSTEM: "Hệ thống",
  ALL_ENTITY: "Tất cả thực thể",
  ALL_ACTION: "Tất cả hành động",
  FILTER: {
    TITLE: "Bộ lọc",
    DESC: "Lọc theo thời gian, hành động và thực thể để truy xuất lịch sử thay đổi.",
    APPLY: "Áp dụng",
    RESET: "Đặt lại",
    SEARCH_PLACEHOLDER: "Tìm theo mã đơn, hành động, người thực hiện hoặc ghi chú thay đổi",
    ACTION_LABEL: "Lọc theo thao tác",
  },
  STATS: {
    TOTAL: "Tổng bản ghi",
    CURRENT_PAGE: "Trang hiện tại",
    PAGE_SIZE: "Kích thước trang",
  },
  DESCRIPTION:
    "Theo dõi mọi thay đổi trong hệ thống bao gồm người thực hiện, thời gian và giá trị trước/sau khi thay đổi.",
  SYSTEM_INTELLIGENCE: "System Intelligence",
  LOGS: "bản ghi",
  OF: "của",
  PAGES: "trang",
  PREVIOUS: "Trước",
  NEXT: "Sau",
  RAW_STATE_BEFORE: "TRẠNG THÁI GỐC TRƯỚC",
  RAW_STATE_AFTER: "TRẠNG THÁI GỐC SAU",
  MODIFIED_LABEL: "ĐÃ THAY ĐỔI",
  CHANGE_DETECTED: "Thay đổi được phát hiện",
  CLOSE_LOGS: "Đóng lịch sử",
  ACTOR_INTELLIGENCE: "Thông tin đối tượng",
  TRANSACTION_INFO: "Thông tin giao dịch",
  PLACEHOLDER: {
    TITLE: "Tuyển tập các hoạt động thay đổi dữ liệu từ Reservation, Table đến các cấu hình khác.",
    DESCRIPTION: "Chọn một hành động để xem chi tiết các trường dữ liệu đã bị thay đổi.",
  },
  SUB_TITLE: "Theo dõi thay đổi đặt bàn và bàn ăn",
  SUB_DESC:
    "Quản lý có thể đọc nhanh ai đã thao tác, thay đổi nào đã xảy ra và mở xem chi tiết khi cần.",
  TECHNICAL_INFO: "Thông tin kỹ thuật",
  LOGGED_AT: "Ghi nhận lúc",
  ACTOR_BY: "Người thực hiện",
  ENTITIES: {
    ALL: "Tất cả đối tượng",
    RESERVATION: "Đặt bàn",
    TABLE: "Bàn ăn",
    UNKNOWN: "Đối tượng khác",
  },
  ACTIONS_LIST: {
    ALL: "Tất cả thao tác",
    CREATE: "Tạo mới",
    UPDATE: "Cập nhật",
    DELETE: "Xóa",
    STATUS_CHANGE: "Đổi trạng thái",
    CANCEL: "Hủy",
    CHECK_IN: "Check-in",
    NO_SHOW: "Khách không đến",
  },
  FIELDS: {
    Field: "TRƯỜNG",
    CustomerName: "Khách hàng",
    CustomerPhone: "Số điện thoại",
    ReservationDate: "Ngày đặt bàn",
    ReservationTime: "Giờ đặt bàn",
    GuestCount: "Số khách",
    Note: "Ghi chú",
    Status: "Trạng thái",
    AreaId: "Khu vực",
    TableId: "Bàn",
    Capacity: "Sức chứa",
    TableNumber: "Số bàn",
    AreaName: "Tên khu vực",
    IsActive: "Trạng thái hoạt động",
    UpdatedAt: "Thời gian cập nhật",
    UpdatedBy: "Người cập nhật",
    CreatedAt: "Thời gian tạo",
    CreatedBy: "Người tạo",
  },
  ACTOR_INFO: {
    GUEST: "Khách",
    GUEST_SUB: "Người dùng không đăng nhập",
    EMPLOYEE: "Nhân viên",
    EMPLOYEE_ID: "Nhân viên {id}",
    INTERNAL: "Hệ thống nội bộ",
    IP_PREFIX: "IP",
  },
  SUBJECTS: {
    RESERVATION: "đặt bàn của {name} ({phone})",
    RESERVATION_NAME: "đặt bàn của {name}",
    RESERVATION_ID: "đặt bàn {id}",
    TABLE_NUM: "bàn {number}",
    TABLE_ID: "bàn {id}",
  },
  MESSAGES: {
    EMPTY_HINT: "Thử đổi bộ lọc hoặc thực hiện thao tác đặt bàn, đổi trạng thái bàn để kiểm tra.",
    NO_DETAIL_CHANGES: "Không có thay đổi chi tiết để hiển thị.",
    NULL_VALUE: "trống",
    YES_VALUE: "có",
    NO_VALUE: "không",
  },
  ACTION_RESULTS: {
    CHECK_IN: "{actor} đã check-in {subject}.",
    CANCEL: "{actor} đã hủy {subject}.",
    STATUS_CHANGE: "{actor} đã đổi trạng thái {subject}.",
    GENERIC: "{actor} đã {action} {subject}.",
  },
  TECHNICAL_LOG_HINT:
    "Bản ghi này chứa các thay đổi thuộc về hệ thống kỹ thuật. Vui lòng xem chi tiết ở mục phía dưới.",
};
