export const AUDIT_LOG = {
  TITLE: "Lịch sử hệ thống",
  EMPTY: "Chưa có lịch sử nào",
  FETCH_ERROR: "Không thể tải lịch sử hệ thống",
  LOG_ID: "Mã Log",
  ORDER_ID: "Mã Đơn hàng",
  EMPLOYEE_ID: "Mã Nhân viên",
  ACTION: "Hành động",
  NO_CHANGES: "Không có thay đổi",
  OLD_VALUE: "Giá trị cũ",
  NEW_VALUE: "Giá trị mới",
  ACTOR_LABEL: "Actor (ActorID)",
  METADATA_LABEL: "Metadata",
  CHANGE_DETAILS: "Chi tiết thay đổi",
  BEFORE_CHANGE: "Trước khi thay đổi",
  AFTER_CHANGE: "Sau khi thay đổi",
  CREATED_AT: "Thời gian",
  REASON: "Lý do / Ghi chú",
};
