export const COMMON = {
  LOADING: "Đang tải...",
  ERROR: "Có lỗi xảy ra",
  RETRY: "Thử lại",
  SAVE: "Lưu",
  CANCEL: "Hủy",
  CONFIRM: "Xác nhận",
  ACTION: "Thao tác",
  CREATE_AT: "Ngày tạo",
  UPDATE_AT: "Ngày cập nhật",
  NULL: "Null",
  EMPTY: "Trống",
  UPDATE: "Đã cập nhật",
  ALL: "Tất cả",
  FILTER: "Bộ lọc",
  SEARCH: "Tìm kiếm",
  NAME_PROJECT: "FoodHub",
  RESET: "Đặt lại",
  UPDATE_SUCCESS: "Cập nhật thông tin thành công",
  UPDATE_ERROR: "Cập nhật thông tin thất bại",
  COPYRIGHT: "Hệ thống quản lý FoodHub &copy; 2026",
  SUCCESS: "Thành công!",
  SAVE_SUCCESS: "Lưu dữ liệu thành công!",
  DELETE_CONFIRM: "Bạn có chắc chắn muốn xóa không?",
  ERROR_UNKNOWN: "Có lỗi xảy ra, vui lòng thử lại.",
  CURRENCY: "đ",
  OUT_OF_STOCK: "Hết hàng",
  PLUS: "+",
  MINUS: "-",
  PAREN_LEFT: "(",
  PAREN_RIGHT: ")",
  HASH: "#",
  BULLET: "•",
  ASTERISK: "*",
  SLASH: "/",
  DASH: "–",
  PIPE: "|",
  COMMA: ",",
  EXCLAMATION: "!",
  QUESTION: "?",
  ELLIPSIS: "…",
  COLON: ":",
  SEMICOLON: ";",
  QUOTE: '"',
  APOSTROPHE: "'",
  BACKTICK: "`",
  AT_SIGN: "@",
  AMPERSAND: "&",
  PERCENT: "%",
  DOLLAR: "$",
  CARET: "^",
  UNDERSCORE: "_",
  PLUS_SIGN: "+",
  MINUS_SIGN: "-",
  EQUAL_SIGN: "=",
  GREATER_THAN: ">",
  LESS_THAN: "<",
  TILDE: "~",
  SPACE: " ",
  NEWLINE: "\n",
  TAB: "\t",
  YES: "Có",
  NO: "Không",
  OK: "OK",
  NEXT: "Tiếp theo",
  PREVIOUS: "Trước đó",
  FINISH: "Hoàn thành",
  BACK: "Quay lại",
  CONTINUE: "Tiếp tục",
  SUBMIT: "Gửi",
  CLOSE: "Đóng",
  EDIT: "Sửa",
  DELETE: "Xóa",
  ADD: "Thêm",
  SAVE_CHANGES: "Lưu thay đổi",
  PEOPLE: "người",
  TIME_LABEL: "Thời gian:",
  DOT: ".",
  MORE: "More",
  PROJECTS: "Projects",
  VIEW_PROJECT: "View Project",
  SHARE_PROJECT: "Share Project",
  DELETE_PROJECT: "Delete Project",
  CLOSE_EN: "Close",
  CANCEL_EN: "Cancel",
  SIDEBAR: "Sidebar",
  SIDEBAR_DESC: "Displays the mobile sidebar.",
  TOGGLE_SIDEBAR: "Toggle Sidebar",
  REQUEST_SENT: "Yêu cầu đã được gửi. Vui lòng kiểm tra email.",
  SEND_FAILED: "Gửi yêu cầu thất bại.",
  SENDING: "Đang gửi...",
  PROCESSING: "Đang xử lý...",
  SOMETHING_WENT_WRONG: "Đã có lỗi xảy ra. Vui lòng thử lại sau.",
  TOGGLE: "Mở rộng",
};

export const SIDE_BAR = {
  DASHBOARD: "Trang chủ",
  MENU: "Thực đơn",
  TABLE: "Sơ đồ bàn",
  ORDER: "Đơn hàng",
  EMPLOYEE: "Nhân viên",
  AUDIT_LOG: "Lịch sử",
  INVENTORY: "Kho hàng",
};

export const FORM = {
  REQUIRED: "Trường này là bắt buộc",
  INVALID_EMAIL: "Email không hợp lệ",
  MIN_LENGTH: (min: number) => `Tối thiểu ${min} ký tự`,
  EDIT_COMBO: "Chỉnh sửa Combo",
  ADD_COMBO: "Thêm mới Combo",
  EDIT_ITEM: "Chỉnh sửa món lẻ",
  ADD_ITEM: "Thêm mới món lẻ",
  IMAGE_LABEL: "Hình ảnh",
  ITEM_NAME: "Tên món ăn",
  SKU_CODE: "Mã SKU",
  CATEGORY: "Danh mục",
  DESCRIPTION: "Mô tả",
  COMBO_COMPONENTS: "Thành phần Combo",
  SELECT_ITEM_FALLBACK: "Chọn món lẻ thêm vào...",
  PRICE_CONFIG: "Cấu hình giá bán",
  PRICE_DINE_IN: "GIÁ TẠI CHỖ",
  PRICE_TAKE_AWAY: "MANG VỀ",
  COST_PRICE: "Giá vốn",
  PREP_TIME: "Chuẩn bị (phút)",
  STATION: "Trạm",
  CANCEL: "HỦY",
  CONFIRM_SAVE: "Xác nhận lưu",
};

export const ROLE = {
  TITLE: "Vai trò nhân viên",
  CURRENT_ROLE: "Vai trò hiện tại",
  NEW_ROLE: "Vai trò mới",
  MANAGER: "Quản lý",
  CASHIER: "Thu ngân",
  WAITER: "Phục vụ",
  CHEF: "Đầu bếp",
};

export const BUTTON = {
  SUBMIT: "Gửi",
  RESET: "Đặt lại",
  CLOSE: "Đóng",
  EDIT: "Sửa",
  DELETE: "Xóa",
  ADD: "Thêm",
  SAVE_CHANGES: "Lưu thay đổi",
  DETAIL: "Chi tiết",
  HISTORY: "Lịch sử",
  CONFIRM_DELETE: "Đồng ý xóa",
};

export const API = {
  NETWORK_ERROR: "Không thể kết nối server",
  TIMEOUT: "Hết thời gian phản hồi",
  UNAUTHORIZED: "Bạn chưa đăng nhập",
};
