export const DASHBOARD = {
  PORTAL_TITLE: "Cổng thông tin vận hành",
  PORTAL_SUBTITLE: "Hệ thống quản lý FoodHub | Trung tâm điều hành",
  OVERVIEW: "Tổng quan Dashboard",
  USER_ROLE: (role: string) => `Bạn đang đăng nhập với vai trò: ${role}`,
  STALE_DATA: "Dữ liệu cũ (5p)",
  SYSTEM_HEALTH: "Sức khỏe hệ thống",
  OPERATIONAL_DATA_LOCKED: "Dữ liệu vận hành bị khóa",
  LOCKED_DESC:
    "Dữ liệu tài chính và lịch sử đơn hàng bị hạn chế theo bộ phận của bạn. Vui lòng sử dụng Terminal Bếp hoặc POS để quản lý trực tiếp.",
  POS_STATUS: "Trạng thái POS",
  PRINTER_STATUS: "Máy in Bếp",
  INVENTORY_SYNC: "Đồng bộ kho",
  ONLINE: "TRỰC TUYẾN",
  READY: "SẴN SÀNG",
  STALE: "TRỄ",
  BULLETIN_TITLE: "Thông báo nội bộ",
  BULLETIN_TAG: "Thông báo chính thức",
  RESOURCES_TITLE: "Tài nguyên chung",
  VIEW_ALL: "Xem tất cả thông báo",
  PULSE: "Nhịp đập nhà hàng",
  WEATHER_CLOUDY: "28°C / Có mây",
  MAIN_LOBBY: "Sảnh chính",
  STALE_DURATION: (mins: number) => `(${mins} phút)`,

  SIGNALR_CONNECTED: "SIGNALR: ĐÃ KẾT NỐI",
  KPI_LABEL: "(KPI)",
  STATS: {
    REVENUE: "Tổng doanh thu",
    ORDERS: "Đơn hàng mới",
    TABLES: "Bàn hoạt động",
    STAFF: "Nhân viên trực ca",
    REVENUE_TREND: (v: string) => `${v} vs hqua`,
    ORDERS_TREND: (v: string) => `${v} vs tuần trước`,
    TABLES_TREND: (v: string) => `${v} lấp đầy`,
    STAFF_TREND: "Đang trực",
    REVENUE_DESC: (percent: string) => `${percent} so với tháng trước`,
    ORDERS_DESC: (percent: string) => `${percent} so với hôm qua`,
    TABLES_DESC: (percent: string) => `${percent} tỉ lệ sử dụng`,
    STAFF_DESC: (chefs: number, waiters: number) => `${chefs} đầu bếp, ${waiters} phục vụ`,
  },

  TABLE_OCCUPANCY: {
    TITLE: "Tình trạng sử dụng bàn",
    FREE: "Bàn trống",
    OCCUPIED: "Đang sử dụng",
    RESERVED: "Đã đặt trước",
  },

  RECENT_ORDERS: {
    TITLE: "Đơn hàng gần đây",
    ORDER_ID: "Mã đơn",
    CUSTOMER: "Khách hàng",
    TABLE: "Bàn",
    AMOUNT: "Số tiền",
    STATUS: "Trạng thái",
    TIME: "Thời gian",
    MINS_AGO: (mins: number) => `${mins} phút trước`,
    HOUR_AGO: (hours: number) => `${hours} giờ trước`,
    STATUS_COMPLETED: "Hoàn tất",
    STATUS_PREPARING: "Đang chế biến",
    STATUS_PENDING: "Chờ xử lý",
    STATUS_CANCELLED: "Đã hủy",
  },

  REVENUE_CHART: {
    TITLE: "Hiệu suất hàng tuần",
    AVG_DAILY: "Trung bình ngày",
    PEAK_DAY: "Ngày cao điểm",
    DAYS: {
      MON: "Thứ 2",
      TUE: "Thứ 3",
      WED: "Thứ 4",
      THU: "Thứ 5",
      FRI: "Thứ 6",
      SAT: "Thứ 7",
      SUN: "Chủ nhật",
    },
  },

  RESOURCES: {
    TITLE: "Tài nguyên chung",
    RECIPES: "Công thức chuẩn",
    SCHEDULE: "Lịch phân ca",
    TRAINING: "Cổng đào tạo",
    HACCP: "Nhật ký HACCP",
    SUPPORT: "Hỗ trợ IT Bếp",
    PUNCH_CLOCK: "Máy chấm công",
  },

  TOP_DISHES: {
    TITLE: "Món ăn bán chạy",
    ORDERS_COUNT: (count: number) => `${count} đơn trong tuần`,
  },

  ALERT_STRIP: {
    PRINTER_ERROR: (station: string) => `Lỗi máy in bếp: ${station} mất kết nối`,
    DELAYED_ORDER: (id: string, mins: number) => `Đơn hàng #${id} trễ > ${mins} phút chưa ra món`,
  },

  OPERATIONS: {
    TITLE: "Trung tâm điều hành",
    KDS_BACKLOG: "KDS Backlog (Bếp)",
    INVENTORY_ALERTS: "Cảnh báo kho",
    PROCESSING_ITEMS: (count: number) => `Có ${count} món đang xử lý`,
    WAITING: "Đang đợi",
    PREPARING: "Đang làm",
    PREPARING_PROGRESS: "TIẾN ĐỘ CHẾ BIẾN",
    ITEMS_COUNT: (count: number) => `${count} món`,
    DELAYED_WARNING: (count: number, mins: number) => `CẢNH BÁO: ${count} MÓN TRỄ > ${mins}P`,
    INGREDIENT_STATUS: "TRẠNG THÁI NGUYÊN LIỆU",
    OUT_OF_STOCK: "Hết hàng",
    LOW_STOCK: "Sắp hết hàng",
    STABLE_INVENTORY: "Kho hàng ổn định",
    VIEW_DETAILS: "XEM CHI TIẾT KHO",
  },

  ANALYTICS: {
    TITLE: "Phân tích chuyên sâu",
    KPI_TITLE: "Chỉ số quan trọng",
    VS_YESTERDAY: "so với hôm qua",
    REVENUE_CHANNEL: "Tỉ trọng kênh bán hàng",
    UPDATED_JUST_NOW: "CẬP NHẬT: VỪA XONG",
    VIEW_REPORT: "XEM BÁO CÁO CHI TIẾT",
    ADD_WIDGET: "Thêm báo cáo mới",
    ADD_WIDGET_DESC: "Kéo thả các biểu đồ hoặc chỉ số bạn muốn theo dõi tại đây",
    LIVE_MONITORING: "Live Monitoring",
    DINE_IN: "Tại chỗ",
    DELIVERY: "Giao hàng",
    BEST_SELLERS_ANALYSIS: "Phân tích món bán chạy",
    QUICK_INSIGHTS: "Xem phân tích sâu",
  },
};
