export const EMPLOYEE = {
  TITLE: "Danh sách nhân viên",
  DESCRIPTION: "Quản lý thông tin nhân viên",
  INFO: "Thông tin nhân viên",
  EMPTY: "Chưa có nhân viên",
  ADD: "Thêm nhân viên",
  ADD_DESCRIPTION: "Thêm nhân viên mới vào hệ thống",
  ADD_SUSCESS: "Thêm nhân viên thành công",
  ADD_FAILED: "Thêm nhân viên thất bại",
  EDIT: "Sửa nhân viên",
  DELETE: "Xóa nhân viên",
  DELETE_CONFIRM: "Bạn có chắc chắn muốn xóa nhân viên này không?",
  DELETE_SUSCESS: "Xóa nhân viên thành công",
  DELETE_FAILED: "Xóa nhân viên thất bại",
  UPDATE_SUSCESS: "Cập nhật nhân viên thành công",
  UPDATE_FAILED: "Cập nhật nhân viên thất bại",
  FETCH_ERROR: "Không thể tải danh sách nhân viên",
  EMPLOYEECODE: "Mã nhân viên",
  FULLNAME: "Họ và tên",
  FULLNAME_PLACEHOLDER: "Nhập họ và tên",
  EMAIL: "Email",
  ROLE: "Vai trò",
  PHONE: "Số điện thoại",
  ADDRESS: "Địa chỉ",
  DOB: "Ngày sinh",
  STATUS: "Trạng thái",
  ACTIVE: "Đang kích hoạt",
  INACTIVE: "Không kích hoạt",
  CHANGE_PASSWORD: "Đổi mật khẩu",
  CHANGE_ROLE: "Đổi vai trò",
  CHANGE_PASSWORD_DESC: "Việc thay đổi mật khẩu sẽ tự động gửi email thông báo đến nhân viên.",
  CHANGE_PASSWORD_REASON: "Lý do thay đổi mật khẩu",
  DETAIL: "Chi tiết nhân viên",
  EMP_ID: "Mã NV",
  EMPLOYEE_TITLE: "Nhân viên",
  CONTACT: "Liên hệ",
  NOT_FOUND: "Không tìm thấy nhân viên nào",
  RETRY: "Thử lại",
  CHANGE_ROLE_TITLE: "Thay đổi vai trò",
  CHANGE_ROLE_DESC_FULL:
    "Việc thay đổi role của nhân viên sẽ cấp cho nhân viên một tài khoản mới và tài khoản cũ sẽ bị vô hiệu hóa.",
  REASON: "Lý do thay đổi",
  INFO_TITLE: "💡 Thông tin:",
  INFO_1: "Tài khoản cũ sẽ bị vô hiệu hóa.",
  INFO_2: "Hệ thống tự động tạo mã nhân viên mới.",
  INFO_3: "Thông tin đăng nhập mới đã được gửi tới ",
  CONFIRM_CHANGE_ROLE: "Xác nhận thay đổi vai trò",
  AGREE_TERMS: "Bằng cách nhấp vào hộp kiểm này, tài khoản cũ sẽ bị vô hiệu hóa.",
  AUTO_GEN: "Tự động tạo mật khẩu:",
  DELETE_CONFIRM_NAME: (name: string) => `Bạn có chắc chắn muốn xóa "${name}" không?`,
  UPDATE_PROFILE: "Cập nhật hồ sơ",
  UPDATE_INFO: "Cập nhật thông tin cơ bản",
  CHANGE_ROLE_DESC: "Thay đổi vai trò nhân viên",
  DELETE_EMPLOYEE: "Xóa nhân viên",
  CONFIRM_DELETE: "Xác nhận xóa",
  CONFIRM_DELETE_DESC: "Bạn chắc chắn muốn tiến hành xóa chứ?",
  ACCOUNT_SECURITY: "Bảo mật tài khoản",
  SECURITY_DESC: "Đổi mật khẩu",
  REMOVE_FROM_SYSTEM: "Gỡ khỏi hệ thống",
  REMOVE_DESC: "Xóa hoàn toàn",
  CONFIRM_REQUIRED: "Vui lòng xác nhận thay đổi vai trò",
  REASON_REQUIRED: "Vui lòng nhập lý do thay đổi vai trò",
  ROLE_MISMATCH: "Vai trò mới phải khác vai trò hiện tại",
  INVALID_CODE: "Mã nhân viên không hợp lệ hoặc không tồn tại",
  CHANGE_SUCCESS: "Thay đổi vai trò thành công",
  CHANGE_FAILED: "Thay đổi vai trò thất bại",
  REASON_PLACEHOLDER: "Nhập lý do thăng chức, chuyển bộ phận...",
  SEARCH_BAR_PLACEHOLDER: "Tìm nhân viên theo tên, email, mã số...",
};
