export const INVENTORY = {
  NAV: {
    OVERVIEW: "Tổng quan",
    STOCK_IO: "Nhập / Xuất kho",
    OPENING_STOCK: "Khai báo tồn đầu",
    CHECK: "Kiểm kho",
    REPORT: "Báo cáo kho",
    LEDGER: "Sổ cái",
    TRANSACTIONS: "Lịch sử",
    LOTS: "Lô tồn kho",
    COGS: "Tính giá xuất kho",
    ALERTS: "Cảnh báo",
    SETTINGS: "Cài đặt",
  },
  TITLE: "Kho nguyên liệu",
  WIP_DESC: "Quản lý và theo dõi nguyên liệu nhà bếp của bạn.",
  TOTAL_ITEMS: "Tổng số nguyên liệu",
  LOW_STOCK: "Sắp hết hàng",
  INVENTORY_VALUE: "Giá trị kho",
  ALERT_TAB_LOW_STOCK: "Sắp hết hàng",
  ALERT_TAB_EXPIRING: "Sắp hết hạn",
  ALERTS_TITLE: "Cảnh báo kho",
  ALERTS_DESC: "Quản lý mức tồn kho tới hạn và hạn sử dụng sắp đến.",
  ALERTS_BTN: "Cảnh báo",
  HISTORY_TITLE: "Lịch sử xuất nhập hàng",
  HISTORY_DESC: "Theo dõi và quản lý các giao dịch nhập xuất kho",
  STOCK_IN_TITLE: "Quản lý xuất nhập",
  CREATE_VOUCHER_BTN: "Tạo phiếu hàng",
  STOCK_IN_VOUCHER: "Phiếu nhập hàng",
  STOCK_OUT_VOUCHER: "Phiếu xuất hàng",
  BACK_TO_INVENTORY: "Quay lại kho",
  NEW_BATCHES_MONTH: "Tổng số lô tháng này",
  NEW_STOCK_VALUE: "Giá trị nhập mới",
  FLAGGED_ITEMS: "Đánh dấu",
  ADD_TITLE: "Thêm nguyên liệu mới",
  ADD_DESC: "Thêm một nguyên liệu mới vào kho. Hệ thống sẽ cảnh báo khi tồn kho dưới mức này.",
  EDIT_TITLE: "Cập nhật nguyên liệu",
  EDIT_DESC: "Chỉnh sửa thông tin của nguyên liệu hiện có trong hệ thống.",
  CREATED_BY: "Người Xuất",
  DELETE: {
    TITLE: "Xóa nguyên liệu",
    DESC: "Bạn có chắc chắn muốn xóa nguyên liệu này không? Hành động này không thể hoàn tác.",
    REACTIVATE_TITLE: "Kích hoạt lại nguyên liệu",
    REACTIVATE_DESC: "Bạn có muốn kích hoạt lại nguyên liệu này để tiếp tục sử dụng không?",
    SUCCESS: "Đã xóa nguyên liệu thành công",
    SUCCESS_DEACTIVATE: "Đã ngừng sử dụng nguyên liệu",
    SUCCESS_REACTIVATE: "Đã kích hoạt lại nguyên liệu",
    ERROR: "Lỗi khi xóa nguyên liệu",
    BTN_CANCEL: "Hủy",
    BTN_CONFIRM: "Ngừng dùng",
    BTN_CONFIRM_REACTIVATE: "Kích hoạt lại",
    BTN_DELETING: "Đang xử lý...",
  },
  PRO_TIP:
    "Đảm bảo đơn vị phù hợp với mức thường xuyên sử dụng nhất để giúp nhân viên nhà bếp dễ dàng chuyển đổi.",
  FORM: {
    NAME: "Tên nguyên liệu",
    SKU: "Mã NVL",
    UNIT: "Đơn vị tính",
    SELECT_UNIT: "Chọn đơn vị",
    ALERT_THRESHOLD: "Ngưỡng cảnh báo hết hàng",
    COST: "Giá trung bình",
    INITIAL_STOCK: "Số lượng ban đầu",
    AUTO_GEN: "(tự động)",
    CURRENT_STOCK: "Tồn hiện tại",
    STOCK_HELP_TEXT: "Số lượng chỉ thay đổi khi nhập/xuất kho.",
    COST_HELP_TEXT: "Giá vốn được tính từ phiếu nhập kho.",
    SUPPLIER: "Nhà cung cấp chính",
    DESCRIPTION: "Mô tả / Ghi chú",
    IS_ACTIVE: "Trạng thái hoạt động",
    PLACEHOLDER_NAME: "VD: Cà chua, Thịt bò...",
    PLACEHOLDER_SKU: "NVL-...",
    PLACEHOLDER_CATEGORY: "Rau củ, Thịt...",
    PLACEHOLDER_DESCRIPTION: "Nhập mô tả nguyên liệu...",
    BATCH_CODE_LABEL: "Mã lô (tuỳ chọn)",
    BATCH_CODE_PLACEHOLDER: "Nhập mã lô nếu có",
    ERROR_ADD: "Lỗi khi thêm nguyên liệu",
    ERROR_CONN: "Đã xảy ra lỗi kết nối",
    SUCCESS_ADD: "Thêm nguyên liệu thành công",
    SUCCESS_EDIT: "Cập nhật nguyên liệu thành công",
    BTN_SAVING: "Đang lưu...",
    BTN_SAVE: "Lưu nguyên liệu",
  },
  TOOLBAR: {
    SEARCH_PLACEHOLDER: "Tìm mã hoặc tên NVL...",
    FILTER_STATUS: "Trạng thái tồn kho",
    STATUS_ALL: "Tất cả trạng thái",
  },
  STOCK: {
    CURRENT: "Tồn kho hiện tại",
    STATUS_NORMAL: "Bình thường",
    STATUS_LOW: "Sắp hết",
    STATUS_OUT: "Hết hàng",
  },
  TABLE: {
    EMPTY_TITLE: "Chưa có nguyên liệu",
    EMPTY_DESC: "Bắt đầu bằng cách thêm nguyên liệu mới vào kho.",
    EMPTY_ALERT: "Không có nguyên liệu nào đang sắp hết.",
    EMPTY_EXPIRING: "Không có nguyên liệu nào sắp hết hạn.",
    EMPTY_HISTORY: "Chưa có lịch sử nhập kho",
    COL_NAME: "Tên nguyên liệu",
    COL_SKU: "Mã NVL",
    COL_CATEGORY: "Danh mục",
    COL_STOCK: "Tồn kho",
    COL_PRICE: "Đơn giá",
    COL_STATUS: "Tình trạng",
    COL_ACTIVE: "Trạng thái",
    COL_ACTIONS: "Thao tác",
    COL_ITEM: "Nguyên liệu",
    COL_CURRENT_STOCK: "Tồn kho hiện tại",
    COL_THRESHOLD: "Ngưỡng cảnh báo",
    COL_BATCH: "Lô hàng (Batch)",
    COL_EXPIRATION: "Ngày hết hạn",
    COL_REMAINING: "Tồn kho còn lại",
    COL_DATE: "Ngày nhập",
    COL_SUPPLIER: "Nhà cung cấp",
    COL_QTY: "Số lượng",
    COL_TOTAL_COST: "Tổng chi phí",
    COL_RECEIVER: "Người tạo",
    COL_STOCK_OUT_BY: "Người xuất",
    COL_TYPE: "Loại giao dịch",
    COL_BALANCE: "Tồn sau giao dịch",
    COL_REFERENCE: "Tham chiếu",
    TRANS_TYPE_OPENING: "Số dư đầu kỳ",
    TRANS_TYPE_IN: "Nhập kho",
    TRANS_TYPE_IN_REVERSE: "Hủy nhập",
    TRANS_TYPE_OTHER: "Khác",
    HISTORY_DESC_FULL: "Theo dõi tất cả biến động số lượng và chi phí của nguyên liệu.",
    COL_SORT: "Sắp xếp",
    SORT_NEWEST: "Mới nhất",
    SORT_OLDEST: "Cũ nhất",
    TRANS_HISTORY: "Lịch sử kho",
    THRESHOLD_PREFIX: "Ngưỡng:",
    ERROR_PREFIX: "Lỗi:",
    EXPIRING_BADGE: "Sắp hết hạn",
    OUT_OF_STOCK_BADGE: "Hết hàng",
    LOW_STOCK_BADGE: "Sắp hết",
    ACTIVE_BADGE: "Đang dùng",
    INACTIVE_BADGE: "Ngừng dùng",
    CURRENCY: "$",
    PAGE: "Trang",
    PAGE_SIZE: "Số dòng:",
    COL_UNIT_SHORT: "ĐVT",
    SLASH: "/",
    HYPHEN: "-",
    PLUS_SIGN: "+",
    MINUS_SIGN: "-",
    EM_DASH: "—",
    PAREN_OPEN: "(",
    PAREN_CLOSE: ")",
  },
  SETTINGS: {
    TITLE: "Cấu hình Kho",
    DESC: "Quản lý các thông số vận hành và phương pháp tính toán của kho sản phẩm.",
    GENERAL_INFO: "Thông tin chung",
    EXPIRY_WARNING: "Số ngày cảnh báo hết hạn",
    EXPIRY_WARNING_DESC: "Hệ thống sẽ gửi thông báo trước khi sản phẩm hết hạn sử dụng.",
    LOW_STOCK_THRESHOLD: "Ngưỡng cảnh báo sắp hết mặc định",
    LOW_STOCK_THRESHOLD_DESC: "Cảnh báo khi tồn kho thấp hơn số lượng này (áp dụng cho NVL mới).",
    AUTO_DEDUCT: "Tự động trừ kho khi bán",
    AUTO_DEDUCT_DESC: "Tự động trừ tồn kho nguyên vật liệu khi đơn hàng được hoàn tất.",
    COST_METHOD: "Phương pháp tính giá vốn",
    COST_METHOD_DESC: "Phương pháp mặc định hệ thống đang áp dụng để tính giá trị kho.",
    MAX_RECALC_DAYS: "Số ngày tối đa cho phép tính lại giá vốn",
    MAX_RECALC_DAYS_DESC: "Khoảng thời gian tối đa để thực hiện tính toán lại giá vốn định kỳ.",
    SUCCESS_UPDATE: "Cập nhật cấu hình kho thành công",
    ERROR_FETCH: "Không thể tải cấu hình kho",
  },
  OPENING_STOCK: {
    TITLE: "Nhập số dư ban đầu",
    DESC: "Thiết lập số lượng tồn và đơn giá ban đầu cho tất cả nguyên vật liệu khi bắt đầu sử dụng hệ thống.",
    SEARCH_PLACEHOLDER: "Tìm mã hoặc tên nguyên vật liệu...",
    TOTAL_VALUE: "Tổng giá trị",
    BTN_SAVE: "Lưu số dư",
    COL_CODE: "Mã NVL",
    COL_NAME: "Tên nguyên vật liệu",
    COL_UNIT: "Đơn vị",
    COL_CURRENT: "Tồn hiện tại",
    COL_QTY: "Số lượng",
    COL_INITIAL: "Số lượng ban đầu",
    COL_COST: "Đơn giá nhập",
    COL_TOTAL: "Thành tiền",
    ERROR_FETCH: "Không thể tải danh sách nguyên vật liệu",
    SUCCESS_IMPORT: "Nhập số dư ban đầu thành công",
    EMPTY_SEARCH: "Không tìm thấy nguyên vật liệu nào",
    VALIDATION_REQUIRED: "Vui lòng nhập số lượng cho ít nhất một nguyên vật liệu",
    LOCKED_TITLE: "Số dư đầu kỳ đã khóa",
    LOCKED_DESC: "Dữ liệu tồn đầu kỳ đã được chốt và không thể chỉnh sửa thêm.",
    LOCKED_TIME: "Thời gian khóa:",
    REMINDER_TITLE: "Bạn chưa nhập số dư đầu kỳ",
    REMINDER_DESC:
      "Vui lòng nhập số dư đầu kỳ trước khi tiếp tục quản lý kho để dữ liệu tồn kho được chính xác.",
    REMINDER_BTN: "Đi đến nhập số dư",
  },
  STOCK_OUT: {
    DATE: "Ngày xuất",
    REASON_LABEL: "Lý do",
    REASON_FIELD: "Lý do xuất",
    REASON_PLACEHOLDER: "Nhập lý do",
    REASON_PRESETS: ["Hủy NVL", "Xuất nội bộ", "Kiểm kê", "Khác"],
    NOTE_LABEL: "Ghi chú bổ sung (tuỳ chọn)",
    NOTE_PLACEHOLDER: "Nhập ghi chú nếu cần",
    QTY_LABEL: "Số lượng xuất",
    PRICE_LABEL: "Đơn giá xuất",
    PRICE_OPTIONAL: "(tùy chọn)",
    TOTAL_PRICE_LABEL: "Thành tiền",
    CURRENT_STOCK_LABEL: "Tồn hiện tại:",
    EXCEED_STOCK_WARNING: "Số lượng vượt tồn cho phép",
    VALIDATION_MIN_ITEMS: "Vui lòng thêm ít nhất 1 dòng NVL và số lượng > 0",
    VALIDATION_REASON_REQ: "Vui lòng chọn lý do xuất",
    SUCCESS_CREATE_PREFIX: "Đã tạo phiếu xuất",
    STOCK_EXCEEDED_PREFIX: "Số lượng xuất vượt tồn hiện tại của",
    STOCK_EXCEEDED_TOKEN: "(tồn",
    ITEM_COUNT_LABEL: "Số dòng NVL",
  },
  VOUCHER: {
    TYPE_IN: "Phiếu nhập",
    TYPE_OUT: "Phiếu xuất",
  },
  CHECK: {
    TITLE: "Kiểm kê kho",
    DESC: "Đối chiếu số lượng thực tế trong kho và số dư trên sổ sách.",
    CREATE_BTN: "Tạo phiếu kiểm kê",
    COL_CODE: "Mã phiếu",
    COL_DATE: "Ngày kiểm",
    COL_CREATOR: "Người tạo",
    COL_STATUS: "Trạng thái",
    COL_ITEMS: "Số mặt hàng",
    FILTER_STATUS: "Trạng thái:",
    STATUS_ALL: "Tất cả",
    DATE_RANGE: "Khoảng ngày:",
    STATUS_DRAFT: "Nháp",
    STATUS_PROCESSED: "Đã xử lý",
    EMPTY_TITLE: "Chưa có phiếu kiểm kê",
    EMPTY_DESC: "Bắt đầu kiểm kê kho để đảm bảo dữ liệu tồn kho chính xác.",
    CREATE: {
      TITLE: "Phiếu kiểm kê kho",
      DESC: "Nhập số lượng thực tế kiểm kê được tại kho.",
      COL_BOOK_QTY: "Tồn sổ sách",
      COL_PHYSICAL_QTY: "Tồn thực tế",
      COL_DIFF_QTY: "Chênh lệch",
      COL_DIFF_SHORT: "Lệch",
      COL_REASON: "Nguyên nhân",
      COL_REASON_NOTE: "Ghi chú/Lý do",
      SAVE_DRAFT: "Lưu nháp",
      PROCESS: "Xử lý kiểm kê",
      SUCCESS_SAVE: "Đã lưu phiếu kiểm kê",
      SUCCESS_PROCESS: "Đã xử lý phiếu kiểm kê thành công",
    },
  },
  REPORT: {
    TITLE: "Báo cáo tồn kho",
    DESC: "Phân tích biến động và giá trị tồn kho theo thời gian.",
    COL_OPENING: "Tồn đầu kỳ",
    COL_IN: "Tổng nhập",
    COL_OUT: "Tổng xuất",
    COL_SALE: "Bán hàng",
    COL_CLOSING: "Tồn cuối kỳ",
    COL_AVG_COST: "Đơn giá bình quân",
    COL_VALUE: "Giá trị tồn",
    LEDGER_TITLE: "Sổ chi tiết nguyên vật liệu",
    LEDGER_DESC: "Chi tiết biến động số dư của nguyên liệu",
    LEDGER_LOADING: "Đang tải lịch sử kho...",
    LEDGER_COL_TIME: "Thời điểm",
    LEDGER_COL_DELTA: "Biến động",
    LEDGER_COL_NOTE: "Ghi chú",
    TOTAL_VALUE_LABEL: "Tổng giá trị tồn",
    DATE_RANGE: "Thời gian báo cáo:",
    FILTER_CATEGORY: "Hạng mục:",
    CATEGORY_ALL: "Tất cả nguyên vật liệu",
    SELECT_MATERIAL: "Chọn nguyên liệu",
    VALUE_SEPARATOR: "—",
  },
  COGS: {
    TITLE: "Tính giá vốn xuất kho",
    DESC: "Phương pháp: Bình quân gia quyền (Weighted Average)",
    FORM_TITLE: "Chọn kỳ tính giá",
    FROM_DATE: "Từ ngày",
    TO_DATE: "Đến ngày",
    ALL_INGREDIENTS: "Tất cả nguyên vật liệu",
    BTN_CALCULATE: "Tính giá",
    BTN_CALCULATING: "Đang tính...",
    NOTE: "Kỳ tính giá tối đa 31 ngày. Hệ thống sẽ tính lại đơn giá bình quân và cập nhật thành tiền trên tất cả phiếu xuất trong kỳ.",
    INFO_MAX_DAYS: "Kỳ tính giá tối đa 31 ngày",
    FORMULA_TITLE: "Công thức Bình quân gia quyền",
    FORMULA:
      "Đơn giá BQ = (Giá trị tồn đầu kỳ + Giá trị nhập trong kỳ) ÷ (SL tồn đầu kỳ + SL nhập trong kỳ)",
    RULE_1: "Tính lại sau mỗi phiếu nhập mới",
    RULE_2: "Xuất kho theo đơn giá BQ tại thời điểm xuất",
    RULE_3: "Chưa nhập lần nào → đơn giá = 0",
    RULE_4: "Giá trị xuất = SL xuất × Đơn giá BQ",
    RESULTS_TITLE: "Kết quả tính giá — Kỳ",
    BADGE_CALCULATED: "Đã tính",
    SUCCESS_TITLE: "Tính toán thành công",
    SUCCESS_MSG: "Tính giá vốn hoàn tất",
    SUCCESS_DESC_PREFIX: "Giá vốn đã được cập nhật cho kỳ từ",
    SUCCESS_DESC_TO: "đến",
    LABEL_RECEIPTS: "Giao dịch đã xử lý",
    LABEL_ITEMS: "Lô hàng cập nhật",
    LABEL_ADJUSTMENT: "Tổng GT điều chỉnh",
    BTN_RECALCULATE: "Tính lại kỳ khác",
    CONFIRM_TITLE: "Xác nhận tính toán lại giá vốn",
    CONFIRM_DESC_PREFIX: "Bạn có chắc chắn muốn tính toán lại giá vốn từ",
    CONFIRM_DESC_TO: "đến",
    CONFIRM_DESC_SUFFIX: "? Quá trình này sẽ cấn trừ lại toàn bộ giao dịch xuất nhập trong kỳ.",
    BTN_RUNNING: "Đang chạy...",
    BTN_RUN_NOW: "Tính toán ngay",
    COL_NO: "STT",
    COL_OPENING_QTY: "Tồn đầu kỳ (SL)",
    COL_OPENING_VAL: "Tồn đầu kỳ (Giá)",
    COL_IN_QTY: "Nhập trong kỳ (SL)",
    COL_IN_VAL: "Nhập trong kỳ (Giá)",
    COL_AVG_PRICE: "Đơn giá BQ",
    COL_OUT_COUNT: "Số phiếu xuất",
    COL_TOTAL_VAL: "Thành tiền",
    TXT_VND_PER_KG: "đ/kg",
    FOOTER_TOTAL: "Tổng thành tiền:",
  },
  ALERTS: {
    TAB_LOW_STOCK: "Sắp hết / Hết hàng",
    TAB_EXPIRING: "Sắp hết hạn / Đã hết hạn",
    REFRESH: "Làm mới",
    EMPTY_TITLE: "Không có cảnh báo mới",
    EMPTY_DESC: "Kho hàng đang ở trạng thái tốt",
    FILTER_PLACEHOLDER: "Tìm nguyên vật liệu...",
    SORT_LOW_STOCK: "Sắp xếp: Hết hàng lên đầu",
    SORT_EXPIRING: "Sắp xếp: Hết hạn sớm nhất lên đầu",
    BADGE_OUT_OF_STOCK: "Hết hàng",
    BADGE_LOW_STOCK: "Sắp hết",
    BADGE_EXPIRED: "Đã hết hạn",
    BADGE_URGENT: "Cực kỳ khẩn",
    BADGE_EXPIRING: "Sắp hết hạn",
    ACTION_ORDER_NOW: "Đặt hàng ngay",
    ACTION_ORDER: "Đặt hàng",
    FILTER_LOT_PLACEHOLDER: "Tìm nguyên liệu hoặc mã lô...",
    FILTER_7_DAYS: "Trong 7 ngày tới",
    COL_LOT: "Mã lô",
    COL_DAYS_REMAINING: "Số ngày còn lại",
    COL_NOTE: "Ghi chú",
    MSG_EXPIRED: "Đã quá hạn",
    MSG_REMAINING: "Còn",
    MSG_NOTE_URGENT: "Kiểm tra và xử lý ngay",
    MSG_NOTE_TODAY: "Ưu tiên sử dụng hôm nay",
    MSG_NOTE_PLAN: "Lên kế hoạch sử dụng",
    MSG_NOTE_ALLOCATE: "Chú ý phân bổ sử dụng",
    MSG_NOTE_CHECK: "Kiểm tra và xử lý hủy",
    TXT_DAYS: "ngày",
  },
  LOTS: {
    TITLE: "Quản lý lô tồn kho",
    DESC: "Xem và quản lý chi tiết các lô hàng nhập kho theo hạn sử dụng",
    SUCCESS_CREATE_RECEIPT: "Đã tạo phiếu nhập",
    SEARCH_PLACEHOLDER: "Tìm theo mã lô hoặc tên nguyên liệu...",
    COL_CODE: "Mã Lô",
    COL_INGREDIENT: "Nguyên liệu",
    COL_STOCK: "Số lượng tồn",
    COL_UNIT: "Đơn vị",
    COL_EXPIRY: "Hạn sử dụng",
    COL_STATUS: "Trạng thái",
    COL_ACTIONS: "Thao tác",
    STATUS_VALID: "Còn hạn",
    STATUS_NEAR_EXPIRY: "Sắp hết hạn",
    STATUS_EXPIRED: "Đã hết hạn",
    STATUS_DEPLETED: "Đã dùng hết",
    STATUS_DISPOSED: "Đã hủy",
    DISPOSE: {
      TITLE_SHORT: "Hủy lô",
      TITLE: "Xác nhận hủy lô nguyên vật liệu",
      DESC: "Bạn sắp hủy lô nguyên vật liệu này. Hành động này không thể hoàn tác và sẽ cập nhật giá vốn.",
      LABEL_NAME: "Tên nguyên liệu:",
      LABEL_CODE: "Mã lô:",
      LABEL_AVAILABLE: "Tồn khả dụng:",
      LABEL_QTY: "Số lượng hủy",
      LABEL_REASON: "Lý do hủy",
      PLACEHOLDER_REASON: "VD: Hết hạn sử dụng, Hư hỏng trong quá trình bảo quản...",
      BTN_CANCEL: "Hủy",
      BTN_CONFIRM: "Xác nhận hủy lô",
      BTN_DISPOSING: "Đang xử lý...",
      SUCCESS: "Hủy lô nguyên vật liệu thành công",
      ERROR: "Không thể hủy lô nguyên vật liệu",
      VALIDATION_QTY: "Vui lòng nhập số lượng hợp lệ",
    },
  },
};
