export const INVENTORY = {
  TITLE: "Kho nguyên liệu",
  WIP_DESC: "Quản lý và theo dõi nguyên liệu nhà bếp của bạn.",
  TOTAL_ITEMS: "Tổng số nguyên liệu",
  LOW_STOCK: "Sắp hết hàng",
  INVENTORY_VALUE: "Giá trị kho",
  ALERT_TAB_LOW_STOCK: "Sắp hết",
  ALERT_TAB_EXPIRING: "Sắp hết hạn",
  ALERTS_TITLE: "Cảnh báo kho",
  ALERTS_DESC: "Quản lý mức tồn kho tới hạn và hạn sử dụng sắp đến.",
  ALERTS_BTN: "Cảnh báo",
  HISTORY_TITLE: "Lịch sử nhập kho",
  HISTORY_DESC: "Theo dõi và quản lý các lô hàng đã nhập",
  HISTORY_BTN: "Lịch sử nhập",
  BACK_TO_INVENTORY: "Quay lại kho",
  NEW_BATCHES_MONTH: "Tổng số lô tháng này",
  NEW_STOCK_VALUE: "Giá trị nhập mới",
  FLAGGED_ITEMS: "Đánh dấu",
  ADD_TITLE: "Thêm nguyên liệu mới",
  ADD_DESC: "Thêm một nguyên liệu mới vào kho. Hệ thống sẽ cảnh báo khi tồn kho dưới mức này.",
  EDIT_TITLE: "Cập nhật nguyên liệu",
  EDIT_DESC: "Chỉnh sửa thông tin của nguyên liệu hiện có trong hệ thống.",
  DELETE: {
    TITLE: "Xóa nguyên liệu",
    DESC: "Bạn có chắc chắn muốn xóa nguyên liệu này không? Hành động này không thể hoàn tác.",
    SUCCESS: "Đã xóa nguyên liệu thành công",
    ERROR: "Lỗi khi xóa nguyên liệu",
    BTN_CANCEL: "Hủy",
    BTN_CONFIRM: "Xóa nguyên liệu",
    BTN_DELETING: "Đang xóa...",
  },
  PRO_TIP:
    "Đảm bảo đơn vị phù hợp với mức thường xuyên sử dụng nhất để giúp nhân viên nhà bếp dễ dàng chuyển đổi.",
  FORM: {
    NAME: "Tên nguyên liệu",
    SKU: "Mã SKU / Barcode",
    UNIT: "Đơn vị tính",
    SELECT_UNIT: "Chọn đơn vị",
    ALERT_THRESHOLD: "Ngưỡng cảnh báo hết hàng",
    COST: "Giá trung bình",
    INITIAL_STOCK: "Số lượng ban đầu",
    SUPPLIER: "Nhà cung cấp chính",
    DESCRIPTION: "Mô tả / Ghi chú",
    IS_ACTIVE: "Trạng thái hoạt động",
    PLACEHOLDER_NAME: "VD: Cà chua, Thịt bò...",
    PLACEHOLDER_SKU: "SKU-...",
    PLACEHOLDER_CATEGORY: "Rau củ, Thịt...",
    PLACEHOLDER_DESCRIPTION: "Nhập mô tả nguyên liệu...",
    ERROR_ADD: "Lỗi khi thêm nguyên liệu",
    ERROR_CONN: "Đã xảy ra lỗi kết nối",
    BTN_SAVING: "Đang lưu...",
    BTN_SAVE: "Lưu nguyên liệu",
  },
  TOOLBAR: {
    SEARCH_PLACEHOLDER: "Tìm mã hoặc tên NVL...",
    FILTER_STATUS: "Trạng thái tồn kho",
    STATUS_ALL: "Tất cả trạng thái",
  },
  STOCK: {
    CURRENT: "Tồn kho hiện tại",
    STATUS_NORMAL: "Bình thường",
    STATUS_LOW: "Sắp hết",
    STATUS_OUT: "Hết hàng",
  },
  TABLE: {
    EMPTY_TITLE: "Chưa có nguyên liệu",
    EMPTY_DESC: "Bắt đầu bằng cách thêm nguyên liệu mới vào kho.",
    EMPTY_ALERT: "Không có nguyên liệu nào đang sắp hết.",
    EMPTY_EXPIRING: "Không có nguyên liệu nào sắp hết hạn.",
    EMPTY_HISTORY: "Chưa có lịch sử nhập kho",
    COL_NAME: "Tên nguyên liệu",
    COL_SKU: "Mã SKU",
    COL_CATEGORY: "Danh mục",
    COL_STOCK: "Tồn kho",
    COL_PRICE: "Đơn giá",
    COL_STATUS: "Tình trạng",
    COL_ACTIVE: "Trạng thái",
    COL_ACTIONS: "Thao tác",
    COL_ITEM: "Nguyên liệu",
    COL_CURRENT_STOCK: "Tồn kho hiện tại",
    COL_THRESHOLD: "Ngưỡng cảnh báo",
    COL_BATCH: "Lô hàng (Batch)",
    COL_EXPIRATION: "Ngày hết hạn",
    COL_REMAINING: "Tồn kho còn lại",
    COL_DATE: "Ngày nhập",
    COL_SUPPLIER: "Nhà cung cấp",
    COL_QTY: "Số lượng",
    COL_TOTAL_COST: "Tổng chi phí",
    COL_RECEIVER: "Người nhận",
    THRESHOLD_PREFIX: "Ngưỡng:",
    ERROR_PREFIX: "Lỗi:",
    EXPIRING_BADGE: "Sắp hết hạn",
    OUT_OF_STOCK_BADGE: "Hết hàng",
    LOW_STOCK_BADGE: "Sắp hết",
    ACTIVE_BADGE: "Đang dùng",
    INACTIVE_BADGE: "Ngừng dùng",
    CURRENCY: "$",
    PAGE: "Trang",
    PAGE_SIZE: "Số dòng:",
    SLASH: "/",
    HYPHEN: "-",
    PAREN_OPEN: "(",
    PAREN_CLOSE: ")",
  },
};
