export const INVENTORY = {
  TITLE: "Kho nguyên liệu",
  WIP_DESC: "Quản lý và theo dõi nguyên liệu nhà bếp của bạn.",
  TOTAL_ITEMS: "Tổng số nguyên liệu",
  LOW_STOCK: "Sắp hết hàng",
  INVENTORY_VALUE: "Giá trị kho",
  ALERT_TAB_LOW_STOCK: "Sắp hết",
  ALERT_TAB_EXPIRING: "Sắp hết hạn",
  ALERTS_TITLE: "Cảnh báo kho",
  ALERTS_DESC: "Quản lý mức tồn kho tới hạn và hạn sử dụng sắp đến.",
  ALERTS_BTN: "Cảnh báo",
  HISTORY_TITLE: "Lịch sử xuất nhập hàng",
  HISTORY_DESC: "Theo dõi và quản lý các giao dịch nhập xuất kho",
  STOCK_IN_TITLE: "Quản lý xuất nhập",
  CREATE_VOUCHER_BTN: "Tạo phiếu hàng",
  STOCK_IN_VOUCHER: "Phiếu nhập hàng",
  STOCK_OUT_VOUCHER: "Phiếu xuất hàng",
  BACK_TO_INVENTORY: "Quay lại kho",
  NEW_BATCHES_MONTH: "Tổng số lô tháng này",
  NEW_STOCK_VALUE: "Giá trị nhập mới",
  FLAGGED_ITEMS: "Đánh dấu",
  ADD_TITLE: "Thêm nguyên liệu mới",
  ADD_DESC: "Thêm một nguyên liệu mới vào kho. Hệ thống sẽ cảnh báo khi tồn kho dưới mức này.",
  EDIT_TITLE: "Cập nhật nguyên liệu",
  EDIT_DESC: "Chỉnh sửa thông tin của nguyên liệu hiện có trong hệ thống.",
  CREATED_BY: "Người Xuất",
  DELETE: {
    TITLE: "Xóa nguyên liệu",
    DESC: "Bạn có chắc chắn muốn xóa nguyên liệu này không? Hành động này không thể hoàn tác.",
    REACTIVATE_TITLE: "Kích hoạt lại nguyên liệu",
    REACTIVATE_DESC: "Bạn có muốn kích hoạt lại nguyên liệu này để tiếp tục sử dụng không?",
    SUCCESS: "Đã xóa nguyên liệu thành công",
    SUCCESS_DEACTIVATE: "Đã ngừng sử dụng nguyên liệu",
    SUCCESS_REACTIVATE: "Đã kích hoạt lại nguyên liệu",
    ERROR: "Lỗi khi xóa nguyên liệu",
    BTN_CANCEL: "Hủy",
    BTN_CONFIRM: "Ngừng dùng",
    BTN_CONFIRM_REACTIVATE: "Kích hoạt lại",
    BTN_DELETING: "Đang xử lý...",
  },
  PRO_TIP:
    "Đảm bảo đơn vị phù hợp với mức thường xuyên sử dụng nhất để giúp nhân viên nhà bếp dễ dàng chuyển đổi.",
  FORM: {
    NAME: "Tên nguyên liệu",
    SKU: "Mã NVL",
    UNIT: "Đơn vị tính",
    SELECT_UNIT: "Chọn đơn vị",
    ALERT_THRESHOLD: "Ngưỡng cảnh báo hết hàng",
    COST: "Giá trung bình",
    INITIAL_STOCK: "Số lượng ban đầu",
    AUTO_GEN: "(tự động)",
    CURRENT_STOCK: "Tồn hiện tại",
    STOCK_HELP_TEXT: "Số lượng chỉ thay đổi khi nhập/xuất kho.",
    COST_HELP_TEXT: "Giá vốn được tính từ phiếu nhập kho.",
    SUPPLIER: "Nhà cung cấp chính",
    DESCRIPTION: "Mô tả / Ghi chú",
    IS_ACTIVE: "Trạng thái hoạt động",
    PLACEHOLDER_NAME: "VD: Cà chua, Thịt bò...",
    PLACEHOLDER_SKU: "NVL-...",
    PLACEHOLDER_CATEGORY: "Rau củ, Thịt...",
    PLACEHOLDER_DESCRIPTION: "Nhập mô tả nguyên liệu...",
    ERROR_ADD: "Lỗi khi thêm nguyên liệu",
    ERROR_CONN: "Đã xảy ra lỗi kết nối",
    SUCCESS_ADD: "Thêm nguyên liệu thành công",
    SUCCESS_EDIT: "Cập nhật nguyên liệu thành công",
    BTN_SAVING: "Đang lưu...",
    BTN_SAVE: "Lưu nguyên liệu",
  },
  TOOLBAR: {
    SEARCH_PLACEHOLDER: "Tìm mã hoặc tên NVL...",
    FILTER_STATUS: "Trạng thái tồn kho",
    STATUS_ALL: "Tất cả trạng thái",
  },
  STOCK: {
    CURRENT: "Tồn kho hiện tại",
    STATUS_NORMAL: "Bình thường",
    STATUS_LOW: "Sắp hết",
    STATUS_OUT: "Hết hàng",
  },
  TABLE: {
    EMPTY_TITLE: "Chưa có nguyên liệu",
    EMPTY_DESC: "Bắt đầu bằng cách thêm nguyên liệu mới vào kho.",
    EMPTY_ALERT: "Không có nguyên liệu nào đang sắp hết.",
    EMPTY_EXPIRING: "Không có nguyên liệu nào sắp hết hạn.",
    EMPTY_HISTORY: "Chưa có lịch sử nhập kho",
    COL_NAME: "Tên nguyên liệu",
    COL_SKU: "Mã NVL",
    COL_CATEGORY: "Danh mục",
    COL_STOCK: "Tồn kho",
    COL_PRICE: "Đơn giá",
    COL_STATUS: "Tình trạng",
    COL_ACTIVE: "Trạng thái",
    COL_ACTIONS: "Thao tác",
    COL_ITEM: "Nguyên liệu",
    COL_CURRENT_STOCK: "Tồn kho hiện tại",
    COL_THRESHOLD: "Ngưỡng cảnh báo",
    COL_BATCH: "Lô hàng (Batch)",
    COL_EXPIRATION: "Ngày hết hạn",
    COL_REMAINING: "Tồn kho còn lại",
    COL_DATE: "Ngày nhập",
    COL_SUPPLIER: "Nhà cung cấp",
    COL_QTY: "Số lượng",
    COL_TOTAL_COST: "Tổng chi phí",
    COL_RECEIVER: "Người tạo",
    COL_STOCK_OUT_BY: "Người xuất",
    COL_TYPE: "Loại giao dịch",
    COL_BALANCE: "Tồn sau giao dịch",
    COL_REFERENCE: "Tham chiếu",
    TRANS_TYPE_OPENING: "Số dư đầu kỳ",
    TRANS_TYPE_IN: "Nhập kho",
    TRANS_TYPE_IN_REVERSE: "Hủy nhập",
    TRANS_TYPE_OTHER: "Khác",
    HISTORY_DESC_FULL: "Theo dõi tất cả biến động số lượng và chi phí của nguyên liệu.",
    COL_SORT: "Sắp xếp",
    SORT_NEWEST: "Mới nhất",
    SORT_OLDEST: "Cũ nhất",
    TRANS_HISTORY: "Lịch sử kho",
    THRESHOLD_PREFIX: "Ngưỡng:",
    ERROR_PREFIX: "Lỗi:",
    EXPIRING_BADGE: "Sắp hết hạn",
    OUT_OF_STOCK_BADGE: "Hết hàng",
    LOW_STOCK_BADGE: "Sắp hết",
    ACTIVE_BADGE: "Đang dùng",
    INACTIVE_BADGE: "Ngừng dùng",
    CURRENCY: "$",
    PAGE: "Trang",
    PAGE_SIZE: "Số dòng:",
    SLASH: "/",
    HYPHEN: "-",
    PAREN_OPEN: "(",
    PAREN_CLOSE: ")",
  },
  SETTINGS: {
    TITLE: "Cấu hình Kho",
    DESC: "Quản lý các thông số vận hành và phương pháp tính toán của kho sản phẩm.",
    GENERAL_INFO: "Thông tin chung",
    EXPIRY_WARNING: "Số ngày cảnh báo hết hạn",
    EXPIRY_WARNING_DESC: "Hệ thống sẽ gửi thông báo trước khi sản phẩm hết hạn sử dụng.",
    LOW_STOCK_THRESHOLD: "Ngưỡng cảnh báo sắp hết mặc định",
    LOW_STOCK_THRESHOLD_DESC: "Cảnh báo khi tồn kho thấp hơn số lượng này (áp dụng cho NVL mới).",
    AUTO_DEDUCT: "Tự động trừ kho khi bán",
    AUTO_DEDUCT_DESC: "Tự động trừ tồn kho nguyên vật liệu khi đơn hàng được hoàn tất.",
    COST_METHOD: "Phương pháp tính giá vốn",
    COST_METHOD_DESC: "Phương pháp mặc định hệ thống đang áp dụng để tính giá trị kho.",
    MAX_RECALC_DAYS: "Số ngày tối đa cho phép tính lại giá vốn",
    MAX_RECALC_DAYS_DESC: "Khoảng thời gian tối đa để thực hiện tính toán lại giá vốn định kỳ.",
    SUCCESS_UPDATE: "Cập nhật cấu hình kho thành công",
    ERROR_FETCH: "Không thể tải cấu hình kho",
  },
  OPENING_STOCK: {
    TITLE: "Nhập số dư ban đầu",
    DESC: "Thiết lập số lượng tồn và đơn giá ban đầu cho tất cả nguyên vật liệu khi bắt đầu sử dụng hệ thống.",
    SEARCH_PLACEHOLDER: "Tìm mã hoặc tên nguyên vật liệu...",
    TOTAL_VALUE: "Tổng giá trị",
    BTN_SAVE: "Lưu số dư",
    COL_CODE: "Mã NVL",
    COL_NAME: "Tên nguyên vật liệu",
    COL_UNIT: "Đơn vị",
    COL_CURRENT: "Tồn hiện tại",
    COL_QTY: "Số lượng",
    COL_INITIAL: "Số lượng ban đầu",
    COL_COST: "Đơn giá nhập",
    COL_TOTAL: "Thành tiền",
    ERROR_FETCH: "Không thể tải danh sách nguyên vật liệu",
    SUCCESS_IMPORT: "Nhập số dư ban đầu thành công",
    EMPTY_SEARCH: "Không tìm thấy nguyên vật liệu nào",
    VALIDATION_REQUIRED: "Vui lòng nhập số lượng cho ít nhất một nguyên vật liệu",
    LOCKED_TITLE: "Số dư đầu kỳ đã khóa",
    LOCKED_DESC: "Dữ liệu tồn đầu kỳ đã được chốt và không thể chỉnh sửa thêm.",
    LOCKED_TIME: "Thời gian khóa:",
    REMINDER_TITLE: "Bạn chưa nhập số dư đầu kỳ",
    REMINDER_DESC:
      "Vui lòng nhập số dư đầu kỳ trước khi tiếp tục quản lý kho để dữ liệu tồn kho được chính xác.",
    REMINDER_BTN: "Đi đến nhập số dư",
  },
  STOCK_OUT: {
    DATE: "Ngày xuất",
    REASON_LABEL: "Lý do",
    REASON_FIELD: "Lý do xuất",
    REASON_PLACEHOLDER: "Nhập lý do",
    REASON_PRESETS: ["Hủy NVL", "Xuất nội bộ", "Kiểm kê", "Khác"],
    NOTE_LABEL: "Ghi chú bổ sung (tuỳ chọn)",
    NOTE_PLACEHOLDER: "Nhập ghi chú nếu cần",
    QTY_LABEL: "Số lượng xuất",
    PRICE_LABEL: "Đơn giá xuất",
    PRICE_OPTIONAL: "(tùy chọn)",
    TOTAL_PRICE_LABEL: "Thành tiền",
    CURRENT_STOCK_LABEL: "Tồn hiện tại:",
    EXCEED_STOCK_WARNING: "Số lượng vượt tồn cho phép",
    VALIDATION_MIN_ITEMS: "Vui lòng thêm ít nhất 1 dòng NVL và số lượng > 0",
    VALIDATION_REASON_REQ: "Vui lòng chọn lý do xuất",
    SUCCESS_CREATE_PREFIX: "Đã tạo phiếu xuất",
    STOCK_EXCEEDED_PREFIX: "Số lượng xuất vượt tồn hiện tại của",
    STOCK_EXCEEDED_TOKEN: "(tồn",
    ITEM_COUNT_LABEL: "Số dòng NVL",
  },
  VOUCHER: {
    TYPE_IN: "Phiếu nhập",
    TYPE_OUT: "Phiếu xuất",
  },
};
