export const KDS = {
  TITLE: "KDS Dashboard",
  QUEUE: "Hàng đợi",
  PROCESSING: "Đang chế biến",
  READY: "Sẵn sàng",
  COMPLETED: "Hoàn tất",
  PAGE: "TRANG",
  PREV: "TRƯỚC",
  NEXT: "TIẾP",
  ORDER_PREFIX: "Order #",
  OPTION_LABEL: "T.Chọn:",
  NOTE_LABEL: "Ghi chú:",
  UPDATE_LABEL: "Cập nhật:",
  ORDER_TYPE_LABEL: "Loại:",
  STATION_LABEL: "Trạm:",
  STATION_PREFIX: "Khu vực chế biến • Station",
  QUEUE_TITLE: "Hàng Đợi",
  TOTAL_ITEMS: "Tổng món",
  TOTAL_ORDERS: "Tổng số đơn",
  ITEMS_IN_ORDER_DESC: "Số bên phải mỗi đơn: số loại món trong đơn",
  REJECT_WARNING: "Hành động này sẽ gửi thông báo đến nhân viên phục vụ và khách hàng.",
  REJECT_CONFIRM: "Bạn đang thực hiện từ chối món:",
  REASON: "Lý do từ chối",
  ORDER_LABEL: "Order",
  NAV: {
    STATION: "VÀO TRẠM",
    AUDIT_LOG: "NHẬT KÝ HOẠT ĐỘNG",
    EXPAND: "MỞ RỘNG MENU",
    COLLAPSE: "THU GỌN MENU",
    STATION_SELECTION: "CHỌN TRẠM LÀM VIỆC",
    STATION_ALL: "TẤT CẢ CÁC TRẠM",
    ACTION_ALL: "TẤT CẢ HÀNH ĐỘNG",
    TIME_TODAY: "HÔM NAY",
    SEARCH_PLACEHOLDER: "TÌM THEO MÃ ĐƠN...",
    FILTER_STATION: "TRẠM:",
    FILTER_ACTION: "HÀNH ĐỘNG:",
    FILTER_TIME: "THỜI GIAN:",
    DESC_AUDIT: "THEO DÕI CHI TIẾT LỊCH SỬ THAO TÁC CỦA NHÂN VIÊN BẾP VÀ BAR",
    WIP_LABEL: "ĐANG NẤU (WIP):",
    WIP_LIMIT_REACHED: "ĐÃ ĐẠT GIỚI HẠN WIP",
  },
  AUDIT: {
    TIME: "THỜI GIAN",
    ACTOR: "NGƯỜI THỰC HIỆN",
    ACTION: "HÀNH ĐỘNG",
    ORDER_DETAILS: "CHI TIẾT ĐƠN HÀNG",
    REASON: "LÝ DO / GHI CHÚ",
    ACTIONS: "THAO TÁC",
    EMPTY: "CHƯA CÓ LỊCH SỬ NÀO",
    UNDO: "HOÀN TÁC",
    ICON: "receipt_long",
    ACTION_START: "BẮT ĐẦU NẤU",
    ACTION_DONE: "HOÀN THÀNH",
    ACTION_REJECT: "TỪ CHỐI MÓN",
    ACTION_UNDO: "HOÀN TÁC",
    REJECT_MODAL: {
      TITLE: "LÝ DO TỪ CHỐI MÓN",
      PLACEHOLDER: "NHẬP LÝ DO (VD: HẾT NGUYÊN LIỆU)...",
      REQUIRED: "VUI LÒNG NHẬP LÝ DO TRƯỚC KHI XÁC NHẬN",
      CONFIRM: "XÁC NHẬN TỪ CHỐI",
      REASONS: ["Hết hàng", "Bếp quá tải", "Thiết bị hỏng"],
    },
  },
  ORDER: {
    STATUS_SERVING: "CHỜ CUNG ỨNG",
    STATUS_COOKING: "ĐANG CHẾ BIẾN",
    COMPLETE_BTN: "HOÀN TẤT ĐƠN",
    EMPTY: "KHÔNG CÓ MÓN TRONG ĐƠN",
    EMPTY_GRID: "CHƯA CÓ ĐƠN HÀNG NÀO CẦN THỰC HIỆN",
    EMPTY_QUEUE: "KHÔNG CÓ ĐƠN HÀNG CHỜ",
    PREPARING: "ĐANG CHUẨN BỊ",
  },
  ITEM: {
    DONE: "HOÀN THÀNH",
    RETURN: "TRẢ MÓN",
    TIME_ICON: "schedule",
    WAITING_SUFFIX: "MÓN ĐANG ĐỢI",
    KEYWORD_ADD: "THÊM",
    KEYWORD_LESS: "ÍT",
    KEYWORD_CRISPY: "GIÒN",
    KEYWORD_MANY: "NHIỀU",
    STATUS_PREPARING: "CHỜ NẤU",
    STATUS_COOKING: "ĐANG NẤU",
    VIP_LABEL: "ƯU TIÊN",
    QTY_PREFIX: "x",
    ITEMS_IN_ORDER_LABEL: "Số món",
  },
  VERSION: "V2.4.0",
  STATIONS: {
    KITCHEN: "TRẠM BẾP (KITCHEN)",
    BAR: "TRẠM BAR (BAR)",
    BARISTA: "BARISTA",
    CHEFBAR: "CHEFBAR",
    STATUS_HIGH: "HOẠT ĐỘNG CAO",
    STATUS_NORMAL: "BÌNH THƯỜNG",
    SYSTEM_ONLINE: "HỆ THỐNG TRỰC TUYẾN",
  },
  FETCH_ERROR: "Khong the tai du lieu KDS",
  START_COOKING_SUCCESS: "Da bat dau nau!",
  COMPLETE_COOKING_SUCCESS: "Mon da hoan thanh!",
  REJECT_ITEM_SUCCESS: "Da tu choi mon!",
};
