export const LANDING = {
  TITLE: "Nền tảng Quản lý",
  SUBTITLE: "Nhà hàng Toàn diện",
  GET_STARTED: "Bắt đầu miễn phí",
  FOOTER_BRAND: "FoodHub",
  FOOTER_DESC:
    "Nền tảng quản lý nhà hàng 4.0, tối ưu hóa quy trình vận hành từ nhà bếp đến bàn ăn một cách liền mạch.",
  PRODUCT: "Product",
  FEATURES: "Features",
  PRICING: "Pricing",
  INTEGRATIONS: "Integrations",
  COMPANY: "Company",
  ABOUT: "About",
  CAREERS: "Carreers",
  BLOG: "Blog",
  SUPPORT: "Support",
  HELP_CENTER: "Help Center",
  STATUS: "Status",
  COPYRIGHT: "© 2026 FoodHub Kitchen Management. All rights reserved.",
  PRIVACY: "Privacy Policy",
  TERMS: "Terms of Service",
  CONTACT_INFO: "Liên hệ",
  SOCIAL_MEDIA: "Mạng xã hội",
  HOTLINE_LBL: "Hotline:",
  EMAIL_LBL: "Email:",
  WEBSITE_LBL: "Website",
  FACEBOOK_LBL: "Facebook",
  INSTAGRAM_LBL: "Instagram",
  ZALOOA_LBL: "Zalo OA",
  ADDRESS_LBL: "Địa chỉ",
  KDS_V2: "KDS v2.0 - Live Connection",
  NAV_BRAND: "FoodHub",
  LEARN_MORE: "Learn more",
  PARTNERS: "Partner Restaurants",
  NEWS: "News & Resources",
  INSIGHT: "Insight",
  HERO_TITLE: "Tối ưu hóa quy trình",
  HERO_SUBTITLE: "Vận hành ẩm thực",
  HERO_DESC:
    "Từ gọi món tại bàn đến sức nóng của bếp. FoodHub cung cấp nền tảng số cho các hoạt động nhà hàng hiện đại và quản lý bếp thông minh.",
  ENTER_SYSTEM: "Vào hệ thống",
  DASHBOARD: "Tổng quan",
  STAFF_LOGIN: "Đăng nhập nhân viên",
  KITCHEN_TERMINAL: "Thiết bị Bếp",
  MISSION_CRITICAL: "Giải pháp cốt lõi cho BOH",
  MISSION_DESC: "Phần mềm được thiết kế chuyên biệt cho nhịp độ và áp lực của khu vực hậu sảnh.",
  KITCHEN_INTEL: "Trí tuệ nhà bếp",
  KDS_PREVIEW: "Giao diện KDS Terminal 01",
  TECH_REDUCING: "Giảm trung bình 24% thời gian lên món",
  RESERVATION_BTN: "Đặt bàn ngay",
  ABOUT_TITLE: "Về FoodHub",
  ABOUT_DESC:
    "FoodHub là đối tác tin cậy của hơn 500 nhà hàng lớn nhỏ, cung cấp hệ sinh thái quản lý toàn diện giúp nâng tầm trải nghiệm thực khách.",
  ESTABLISHED: "Thành lập từ 2018",
  TEAM_SIZE: "Hơn 100 chuyên gia kỹ thuật và ẩm thực",
  YEAR_VAL: "2023",
  AWARDS_VAL: "50+",
  CUSTOMERS_VAL: "500+",
  ABOUT_IMG_ALT: "Restaurant Business",
  RESERVATION_TITLE: "Đặt bàn FoodHub",
  RESERVATION_DESC:
    "Chọn ngày, giờ và số lượng khách để đặt bàn tại nhà hàng đối tác của chúng tôi.",
  CONFIRM_RESERVATION: "Xác nhận đặt bàn",
  BLOG_TITLE: "Tin tức & Sự nghiệp",
  BLOG_DESC: "Cập nhật những xu hướng công nghệ nhà hàng và tin tức nội bộ mới nhất từ FoodHub.",
  BLOG_INSIGHT: "Insight",
  READ_MORE: "Đọc thêm",

  REVIEWS_TITLE: "Đánh giá từ đối tác",
  REVIEWS_DESC: "Những gì các bếp trưởng và quản lý nói về chúng tôi.",
  REVIEWS_LIST: [
    {
      author: "Bếp trưởng Toàn Nguyễn",
      role: "Ocean Grill",
      content:
        "Kể từ khi dùng FoodHub, tình trạng sai sót ticket gần như bằng không. Đội ngũ bếp phối hợp nhịp nhàng hơn hẳn.",
    },
    {
      author: "Chị Lan Anh",
      role: "Manager tại Red Coral",
      content:
        "Hệ thống báo cáo chi tiết giúp tôi nắm bắt tình hình kinh doanh ngay cả khi không có mặt tại quán.",
    },
    {
      author: "Anh Minh Quân",
      role: "Chủ chuỗi Tasty Hub",
      content: "Phần mềm ổn định, giao diện hiện đại và rất dễ để đào tạo nhân viên mới.",
    },
  ],
  RESERVATION: {
    SUBTITLE: "Reservations",
    TITLE_MAIN: "Giữ chỗ cho",
    TITLE_ITALIC: "Trải Nghiệm",
    TITLE_SUFFIX: "của bạn.",
    DESCRIPTION:
      "Đừng để những khoảnh khắc quý giá phải chờ đợi. FoodHub cam kết mang đến không gian chuẩn mực nhất.",
    HOTLINE_LABEL: "Hotline hỗ trợ 24/7",
    HOTLINE_NUMBER: "1900 6868",
    FORM: {
      NAME_LABEL: "Họ tên quý khách",
      NAME_PLACEHOLDER: "Nguyễn Văn A",
      PHONE_LABEL: "Số điện thoại",
      PHONE_PLACEHOLDER: "09xx xxx xxx",
      DATE_LABEL: "Ngày dùng bữa",
      DATE_PICKER_EMPTY: "Chọn ngày",
      TIME_LABEL: "Giờ nhận bàn",
      TIME_PLACEHOLDER: "Chọn giờ",
      TIME_EMPTY: "Hết giờ",
      GUESTS_LABEL: "Số lượng khách",
      AREA_LABEL: "Khu vực",
      AREA_PLACEHOLDER: "Chọn vị trí",
      MENU_LABEL: "Hình thức",
      MENU_PLACEHOLDER: "Chọn thực đơn",
      NOTE_LABEL: "Lời nhắn (Không quá 200 ký tự)",
      NOTE_PLACEHOLDER: "Yêu cầu đặc biệt (Sinh nhật, dị ứng...)",
      SUBMIT_BUTTON: "Xác nhận đặt bàn",
      SUBMIT_DISABLED: "Ngừng nhận khách",
      FOOTER_NOTE: "Xác nhận tức thì • Miễn phí hủy bàn (Trước 45p)",
    },
    AREAS: [
      { value: 0, label: "Phòng Thường" },
      { value: 1, label: "Phòng VIP" },
    ],
    MENU_TYPES: [
      { value: "alacarte", label: "Gọi món (A la carte)" },
      { value: "combo", label: "Dùng Combo / Set menu" },
    ],
  },
  PARTNER_CONTACT: {
    SUBTITLE: "Trở Thành Đối Tác",
    TITLE_MAIN: "Giải pháp quản lý",
    TITLE_ITALIC: "Đột Phá",
    TITLE_SUFFIX: "cho doanh nghiệp",
    DESCRIPTION:
      "Liên hệ ngay hôm nay để nhận tư vấn miễn phí và trải nghiệm hệ thống quản lý nhà hàng thông minh.",
    HOTLINE_LABEL: "Hotline kinh doanh",
    HOTLINE_NUMBER: "1900 6868",
    FORM: {
      RESTAURANT_NAME_LABEL: "Tên nhà hàng/quán",
      RESTAURANT_NAME_PLACEHOLDER: "Nhập tên nhà hàng",
      CONTACT_NAME_LABEL: "Người liên hệ",
      CONTACT_NAME_PLACEHOLDER: "Họ và tên",
      PHONE_LABEL: "Số điện thoại",
      PHONE_PLACEHOLDER: "09xx xxx xxx",
      EMAIL_LABEL: "Email liên hệ",
      EMAIL_PLACEHOLDER: "example@domain.com",
      NOTE_LABEL: "Lời nhắn (Tùy chọn)",
      NOTE_PLACEHOLDER: "Nhập yêu cầu tư vấn...",
      SUBMIT_BUTTON: "Gửi thông tin",
      FOOTER_NOTE: "Chúng tôi sẽ liên hệ lại trong vòng 24h",
    },
  },
  RESTAURANT_PAGE: {
    HERO_TITLE: "Trải nghiệm ẩm thực",
    HERO_SUBTITLE: "",
    HERO_DESC:
      "Hòa quyện giữa hương vị tinh tế, nguyên liệu tươi ngon và không gian sang trọng. Chúng tôi mang đến cho bạn những phút giây trọn vẹn nhất.",
    FEATURE_TAG: "Hương vị đánh thức giác quan",
    EXPLORE_MENU: "Khám phá thực đơn",
    ABOUT_TITLE: "Về Chúng Tôi",
    ABOUT_DESC:
      "Với niềm đam mê ẩm thực mãnh liệt, mỗi món ăn tại nhà hàng không chỉ là một kiệt tác nghệ thuật mà còn chứa đựng tâm huyết của những đầu bếp hàng đầu. Không gian ấm cúng, phục vụ tận tình - tất cả chỉ để mang lại cho bạn trải nghiệm hoàn hảo.",
    ESTABLISHED: "Thành lập từ 2010",
    TEAM_SIZE: "Đầu bếp chuẩn sao Michelin",
    YEAR_VAL: "2010",
    AWARDS_VAL: "15+",
    CUSTOMERS_VAL: "1M+",
    SATISFIED_CUSTOMERS: "Khách hàng Hài lòng",
    ABOUT_IMG_ALT: "Không gian nhà hàng sang trọng",
    OPERATING_HOURS: "Giờ hoạt động",
    ADDRESS: "Địa chỉ",
    MASTERCHEF: "Masterchef",
    SIGNATURE: "Signature",
    REVIEWS_TITLE: "Đánh giá từ thực khách",
    REVIEWS_DESC: "Khách hàng nói gì về trải nghiệm tại nhà hàng của chúng tôi.",
    REVIEWS_LIST: [
      {
        author: "Anh Trần Phát",
        role: "Thực khách thường xuyên",
        content:
          "Hương vị món ăn cực kỳ tuyệt vời. Không gian ấm cúng rất phù hợp cho các buổi tiệc gia đình. Nhân viên phục vụ chu đáo, chuyên nghiệp.",
      },
      {
        author: "Chị Minh Ngọc",
        role: "Food Blogger",
        content:
          "Thực sự ấn tượng với cách decor món ăn ở đây. Mọi thứ đều tươi ngon và vừa vặn. Chắc chắn sẽ quay lại nhiều lần nữa!",
      },
      {
        author: "Anh Đức Hải",
        role: "Doanh nhân",
        content:
          "Nơi lý tưởng để tiếp khách đối tác. Các món steak được chế biến hoàn hảo, rượu vang đa dạng và không gian vô cùng sang trọng.",
      },
    ],
  },
};
