export const MENU = {
  TITLE: "Quản lý Thực đơn",
  SUBTITLE: "Hệ thống quản lý món ăn, giá bán và điều phối trạm tập trung.",
  ADD_NEW_ITEM: "Thêm món mới",
  TAB_ITEM: "Món lẻ",
  TAB_COMBO: "Combo / Set Menu",
  ADD_ITEM: "+ Thêm món lẻ",
  ADD_COMBO: "Thêm Combo",
  EMPTY_COMBO: "Chưa có dữ liệu Combo...",
  ID_NOT_FOUND: "Lỗi: Không tìm thấy ID món ăn!",
  DELETE_SUCCESS: "Xóa thành công!",
  DELETE_CONFIRM: (name: string) => `Bạn có chắc chắn muốn xóa món "${name}" không?`,
  UPDATE_STOCK_ERROR: "Không thể cập nhật trạng thái hàng hóa!",
  SAVE_SUCCESS: "Lưu dữ liệu thành công!",
  DELETE_DEFAULT_ERROR:
    "Món ăn này đã có trong hóa đơn, không thể xóa. Hãy tắt trạng thái bán thay vì xóa!",
  OPTIONS: {
    TITLE: "Tuỳ chọn món ăn",
    MENU_FAILED: "Không thể tải tuỳ chọn cho món ăn này!",
    NAME_GROUP: "Tên nhóm tuỳ chọn",
    TYPE: "Loại tuỳ chọn",
    REQUIRED_MARK: "*",
    CHOOSE_ONE: "Chọn 1",
    MAXIMUM: "Tối đa",
    REQUIRED_LABEL: "Bắt buộc",
    SELECTED: "Đã chọn",
    NEED_SELECT: "Cần chọn",
    ADD_TO_ORDER: "Thêm vào đơn -",
    ITEM_NOTE: "Ghi chú món",
    PRICE_EXTRA: "Giá cộng thêm",
    PLACEHOLDER_OPTION_NAME: "VD: Size M",
    PLACEHOLDER_EXTRA_PRICE: "VD: 10000",
    COMBO_ITEMS: "Các lựa chọn trong nhóm",
    EMPTY_COMBO: "Chưa có lựa chọn nào. Nhấp vào Thêm để tạo.",
  },
  // Table Columns
  COL_ITEM_NAME: "Món ăn",
  COL_CATEGORY: "Danh mục",
  COL_PRICE: "Giá",
  COL_STATUS: "Trạng thái",
  COL_ACTION: "Hành động",

  // Status and Tooltips
  STATUS_OUT_OF_STOCK: "Hết hàng",
  STATUS_IN_STOCK: "Còn hàng",
  NO_CATEGORY: "Không có",
  TOOLTIP_CHANGE_STATUS: "Đổi trạng thái",
  TOOLTIP_EDIT: "Sửa",
  TOOLTIP_DELETE: "Xóa",

  // Not Found
  NOT_FOUND_TITLE: "Không tìm thấy món ăn nào!",
  NOT_FOUND_DESC: "Hãy kiểm tra lại bộ lọc hoặc thêm món ăn mới.",

  // Form Modal
  MODAL_EDIT_TITLE: "Chỉnh sửa món ăn",
  MODAL_ADD_TITLE: "Thêm món ăn mới",
  MODAL_EDIT_DESC: "Cập nhật thông tin chi tiết của món ăn.",
  MODAL_ADD_DESC: "Điền thông tin để tạo món ăn mới cho nhà hàng.",
  LABEL_NAME: "Tên món ăn",
  LABEL_DESC: "Mô tả",
  LABEL_STATION: "Khu vực chế biến",
  LABEL_PRICE: "Giá bán (VNĐ)",
  LABEL_COST: "Giá vốn (VNĐ)",
  LABEL_CATEGORY: "Danh mục",
  LABEL_IMAGE_URL: "Hình ảnh (URL)",
  LABEL_MARK_OUT_OF_STOCK: "Đánh dấu là Hết Hàng (Không bán)",
  LABEL_EXPECTED_TIME: "Thời gian chuẩn bị (phút)",
  LABEL_IMAGE_VIEW: "Xem hình ảnh",
  LABEL_COMBO_ITEMS: "Các món trong Combo",
  PLACEHOLDER_NAME: "VD: Phở Bò Chín",
  PLACEHOLDER_DESC: "Mô tả chi tiết về món ăn...",
  PLACEHOLDER_STATION: "Chọn khu vực",
  PLACEHOLDER_PRICE: "VD: 50000",
  PLACEHOLDER_COST: "VD: 30000",
  PLACEHOLDER_CATEGORY: "Chọn danh mục",
  PLACEHOLDER_IMAGE_URL: "https://example.com/image.jpg",

  PLACEHOLDER_EXPECTED_TIME: "VD: 15",
  OPTION_SELECT_DEFAULT: "-- Chọn --",
  BUTTON_CANCEL: "Hủy",
  BUTTON_UPDATE: "Cập nhật",
  BUTTON_CREATE: "Tạo mới",

  STATION: {
    HOTKITCHEN: "Bếp nóng",
    COLDKITCHEN: "Bếp lạnh",
    DRINKS: "Pha chế",
  },

  LOADING_IMAGE: "Đang tải hình ảnh...",
  UPLOADING_IMAGE: "Đang xử lý hình ảnh...",
  FETCHING_RECIPE: "Đang tải dữ liệu công thức...",
  UNIT_VND: "VNĐ",
  HELPER_INGREDIENTS: "Thiết lập các nguyên liệu thành phần cho món ăn này.",
  HELPER_KDS_DEDUCTION:
    "Khi món ăn này được hoàn thành (Completed) trên KDS, hệ thống sẽ tự động trừ kho nguyên liệu dựa trên định lượng này. Đảm bảo dữ liệu chính xác để báo cáo tồn kho đúng.",
  ADD_NOW: "Thêm ngay",
  INGREDIENTS_COUNT: (count: number) => `${count} nguyên liệu`,

  // Filter Bar
  PLACEHOLDER_SEARCH: "Tìm kiếm tên món ăn...",
  FILTER_ALL_CATEGORY: "Tất cả danh mục",
  FILTER_OUT_OF_STOCK: "Hết hàng",

  // Management Page
  CATEGORY: {
    COFFEE: "Cà phê",
    SOUP: "Món nước",
    TEA: "Trà",
  },
  MENU_PAGE_SUBTITLE: "Thêm, sửa, xóa và quản lý trạng thái món ăn trong nhà hàng.",
  LIST_TITLE: "Danh sách món ăn",
  TAB_DETAILS: "Chi tiết món",
  TAB_RECIPE: "Định lượng nguyên liệu",
  TAB_MEDIA: "Hình ảnh & Media",
  MODAL_ID_PREFIX: "ID:",
  MEDIA_MANAGEMENT_TITLE: "Quản lý Media",
  MEDIA_MANAGEMENT_DESC: "Tải lên hình ảnh hoặc video cho món ăn này.",
  OR: "HOẶC",
  RECEIPT: {
    TITLE: "Chi tiết hóa đơn",
    DISCOUNT: "Giảm giá",
    SUBTOTAL: "Tạm tính",
    TAX: "Thuế",
    TOTAL: "Tổng cộng",
  },

  RECIPE: {
    SETUP_TITLE: "Thiết lập định lượng",
    SETUP_DESC: "Xác định các nguyên liệu và số lượng cần thiết cho món ăn này.",
    ADD_INGREDIENT: "Thêm nguyên liệu",
    SEARCH_INGREDIENT_PLACEHOLDER: "Tìm kiếm nguyên liệu...",
    CATEGORY_PLACEHOLDER: "Danh mục",
    CATEGORY_ALL: "Tất cả danh mục",
    CATEGORY_MEAT: "Thịt",
    CATEGORY_VEGGIE: "Rau củ",
    CATEGORY_SPICE: "Gia vị",
    SEARCH_BUTTON: "Tìm",
    INGREDIENT_NAME: "Tên nguyên liệu",
    UNIT: "Đơn vị",
    STOCK_COLUMN: "Tồn kho",
    QUANTITY_COLUMN: "Số lượng",
    NO_INGREDIENTS_FOUND: "Không tìm thấy nguyên liệu nào.",
    CONFIRM_ADD_BUTTON: "Xác nhận đã thêm",
    TOTAL_COST: "Tổng chi phí định lượng",
    PREP_TIME: "Thời gian chuẩn bị (phút)",
    INSTRUCTIONS: "Hướng dẫn thực hiện",
    QUANTITY: "Số lượng",
    COST: "Giá ước tính",
    IS_OPTIONAL: "Không bắt buộc",
    INGREDIENTS_LIST: "Danh sách nguyên liệu",
    EMPTY_MAPPED: "Chưa có nguyên liệu nào. Nhấn Thêm nguyên liệu để bắt đầu.",
    SAVING: "Đang lưu công thức...",
    SAVE_SUCCESS: "Đã lưu công thức thành công!",
    SAVE_ERROR: "Lưu công thức thất bại. Vui lòng thử lại!",
    LOADING: "Đang tải dữ liệu công thức...",
    SAVE_RECIPE: "Lưu định lượng",
    DISCARD: "Hủy bỏ",
    QUANTITY_MIN_ERROR: "Số lượng phải lớn hơn 0",
    AT_LEAST_ONE_ERROR: "Cần nhất một nguyên liệu",
    INSTRUCTIONS_PLACEHOLDER: "Mô tả quy trình chế biến món ăn...",
    PREP_TIME_PLACEHOLDER: "VD: 15",
    TITLE: "Chi tiết công thức",
    DESCRIPTION: "Xem và chỉnh sửa nguyên liệu cần thiết để chuẩn bị món ăn này.",
    INGREDIENT: "Nguyên liệu",
    INSTRUCTION: "Hướng dẫn chế biến",
    CURRENCY: "$",
    TOTAL_COST_DESC: "Dựa trên giá nhập gần nhất của các nguyên liệu trong định lượng.",
  },
};
