export const ORDER = {
  TITLE: "Đơn hàng",
  EMPTY: "Chưa có đơn hàng nào",
  TAB_ORDER: "Đơn hàng",
  TAB_MENU: "Thực đơn",
  FETCH_ORDERING: "Đang tải đơn hàng...",
  FETCH_MENU: "Đang tải thực đơn...",
  FETCH_ERROR: "Không thể tải danh sách đơn hàng",
  DESCRIPTION_DETAIL: (tableNumber: string, total: number) => `${tableNumber} • Tổng ${total} món`,
  NOTE: (note: string) => `Ghi chú: ${note}`,
  BOARD: {
    TABLE_ZONE: "Khu vực bàn",
    TAKEAWAY_ORDERS: "Đơn mang đi",
    AVAILABLE_LCT: "Sẵn",
    AT_TABLE: "Tại bàn",
    TAKEAWAY: "Mang đi",
    LATEST_UPDATE: "Cập nhật mới nhất",
    OLDEST_UPDATE: "Cập nhật cũ nhất",
    SORT_BY: "Sắp xếp theo",
    STATUS_LABEL: "Trạng Thái",
    ADVANCED_FILTER: "Bộ lọc nâng cao",
    OVERVIEW: "Tổng quan",
  },
  CURRENT: {
    TOTAL_AMOUNT: "Tổng thanh toán",
    PAYMENT_METHOD: "Phương thức thanh toán",
    CASH: "Tiền mặt",
    TRANSFER: "Chuyển khoản",
    CARD: "Thẻ (POS)",
    CUSTOMER_GAVE: "Khách đưa",
    CHANGE: "Tiền thối lại",
    PROCESSING: "Đang xử lý...",
    SUBTOTAL: "Tạm tính",
    TAX: "Thuế (VAT 10%)",
    PAY: "Thanh toán",
    EMPTY: "Chưa có món nào trong đơn hàng",
    CONFIRM_PAYMENT: "Xác nhận thanh toán",
    CHECKOUT_TITLE: "Thanh toán đơn hàng",
    CHECKOUT_DESC: "Vui lòng chọn phương thức thanh toán và xác nhận",
    NEW: "Mới",
    STATUS_PREP: "Đang chuẩn bị",
    STATUS_COOKING: "Đang nấu",
    STATUS_READY: "Sẵn sàng",
    STATUS_DONE: "Hoàn tất",
    TAKEAWAY: "Mang đi",
  },
};
