export const ORDER = {
  TITLE: "Đơn hàng",
  EMPTY: "Chưa có đơn hàng nào",
  TAB_ORDER: "Đơn hàng",
  TAB_MENU: "Thực đơn",
  FETCH_ORDERING: "Đang tải đơn hàng...",
  FETCH_MENU: "Đang tải thực đơn...",
  FETCH_ERROR: "Không thể tải danh sách đơn hàng",
  DESCRIPTION_DETAIL: (tableNumber: string, total: number) => `${tableNumber} • Tổng ${total} món`,
  NOTE: (note: string) => `Ghi chú: ${note}`,
  QUANTITY: (quantity: number) => `Số Lượng: ${quantity}`,
  BOARD: {
    TABLE_ZONE: "Khu vực bàn",
    ORDER_COUNT: (count: number) => `${count} đơn`,
    PICK_ORDER_TITLE: "Chọn đơn",
    PICK_ORDER_DESC: "Chọn một đơn đang phục vụ trên bàn này để mở chi tiết.",
    CREATE_TAKEAWAY_ORDER: "Tạo đơn mang đi",
    TAKEAWAY_ORDERS: "Đơn mang đi",
    AVAILABLE_LCT: "Sẵn",
    AT_TABLE: "Tại bàn",
    TAKEAWAY: "Mang đi",
    LATEST_UPDATE: "Cập nhật mới nhất",
    OLDEST_UPDATE: "Cập nhật cũ nhất",
    SORT_BY: "Sắp xếp theo",
    STATUS_LABEL: "Trạng Thái",
    ADVANCED_FILTER: "Bộ lọc nâng cao",
    OVERVIEW: "Tổng quan",
    ORDER_CODE: "Mã Đơn",
    TYPE_TABLE: "Loại / Bàn",
    TIME: "Thời Gian",
    TOTAL_AMOUNT: "Tổng Tiền",
    VIP: "VIP",
    ALL_STATUS: "Tất cả trạng thái",
    ALL_TYPE: "Tất cả loại đơn",
    DINE_IN_LABEL: "Tại bàn (Dine-in)",
    TAKEAWAY_LABEL: "Mang đi (Takeaway)",
    LOADING_DATA: "Đang tải dữ liệu...",
    NOT_FOUND: "Không tìm thấy đơn hàng nào phù hợp.",
    SEARCH_PLACEHOLDER: "Tìm kiếm mã đơn, số bàn...",
    TABLE_PREFIX: "Bàn:",
    PAGE: "Trang",
    PAGE_PREV: "Trang trước",
    PAGE_NEXT: "Trang tiếp",
    FETCH_ERROR: "Lỗi khi lấy danh sách đơn hàng.",
    CREATE_ORDER_ERROR: "Tạo đơn hàng thất bại",
    STATUS_AVAILABLE: "Bàn trống",
    STATUS_SERVING: "Đang sử dụng",
    STATUS_RESERVED: "Đặt trước",
    STATUS_OUT_OF_SERVICE: "Tạm ngưng",
    GET_STATUS_LABEL: (status: string) => {
      switch (status) {
        case "ready":
          return "Bàn trống";
        case "serving":
          return "Đang sử dụng";
        case "reserved":
          return "Đặt trước";
        case "out_of_service":
          return "Tạm ngưng";
        case "tk_serving":
          return "Đang nấu";
        case "tk_ready":
          return "Sẵn sàng";
        default:
          return status;
      }
    },
    DROPDOWN_FEATURE: {
      MERGE: "Gộp đơn",
      MERGE_LABEL: "Chọn đơn hàng để gộp",
      // MERGE_PLACEHOLDER: "Chọn đơn hàng",
      MERGE_NO_ORDERS: "Không có đơn hàng nào để gộp",

      LABEL_MERGE: "Chọn đơn hàng để gộp",
      MERGE_SUCCESS: "Gộp đơn thành công",
      MERGE_ERROR: "Gộp đơn thất bại",
      MERGE_ORIGIN: "Đơn nguồn",
      MERGE_DESTINATION: "Đơn đích",
      MERGE_PLACEHOLDER: "Chọn đơn để gộp",
      MERGE_SECOND_ORDER_REQUIRED: "Đơn đích không được để trống",
      MERGE_DUPLICATE_ERROR: "Không thể gộp cùng một đơn",
      SPLIT: "Tách đơn",
      SPLIT_ORIGIN: "Đơn nguồn",
      SPLIT_SUMMARY: (lineCount: number, itemTotal: number) =>
        `${lineCount} món | ${itemTotal} phần`,
      SPLIT_DESTINATION_LABEL: "Nơi nhận món",
      SPLIT_DESTINATION_DESC: "Chọn đơn đang có hoặc bàn trống để tạo đơn mới.",
      SPLIT_MODE_SAME: "Cùng bàn",
      SPLIT_MODE_EXISTING: "Đơn đang có",
      SPLIT_MODE_NEW: "Bàn trống",
      SPLIT_DESTINATION_ORDER: "Đơn đích",
      SPLIT_DESTINATION_ORDER_PLACEHOLDER: "Chọn đơn nhận món",
      SPLIT_DESTINATION_TABLE: "Bàn đích",
      SPLIT_DESTINATION_TABLE_PLACEHOLDER: "Chọn bàn trống để tạo đơn mới",
      SPLITED_ITEMS_LABEL: "Món cần tách",
      SPLITED_ITEMS_DESC: "Chọn số lượng cần chuyển cho từng món.",
      SPLIT_SELECTED_COUNT: (count: number) => `${count} suất được chuyển`,
      SPLIT_LOADING_ITEMS: "Đang tải món...",
      SPLIT_EMPTY_ITEMS: "Không có món để tách.",
      SPLIT_ITEM_QTY_LABEL: "Số lượng hiện tại:",
      SPLIT_ITEM_NOTE_LABEL: "Ghi chú:",
      SPLIT_ITEM_COMPLETED_ERROR: "Món đã hoàn tất, không thể tách.",
      SPLIT_SUCCESS: "Tách đơn thành công",
      SPLIT_ERROR: "Tách đơn thất bại",
      SPLIT_ACTION_NEW: "Tạo đơn tách",
      SPLIT_ACTION_EXISTING: "Tách sang đơn đích",
      SPLIT_FETCH_ITEMS_ERROR: "Không tải được món của bàn này",
      SPLIT_REQUIRED_QTY: "Chọn số lượng món cần tách",
      SPLIT_REQUIRED_DESTINATION_ORDER: "Chọn đơn đích để nhận món",
      SPLIT_REQUIRED_DESTINATION_TABLE: "Chọn bàn trống để tạo đơn mới",
      SPLIT_DESTINATION_SAME_ORDER: "Cùng đơn",
      SPLIT_DESTINATION_EXISTING_ORDER: "Đơn khác",
      SPLIT_DESTINATION_NEW_TABLE: "Bàn khác",
      MOVE_TABLE: "Chuyển bàn",
      MOVE_TABLE_LABEL: "Chọn bàn để chuyển",
      MOVE_TABLE_ORIGIN: "Bàn nguồn",
      MOVE_TABLE_DESTINATION: "Bàn đích",
      MOVE_TABLE_SUCCESS: "Chuyển bàn thành công",
      MOVE_TABLE_ERROR: "Chuyển bàn thất bại",
      MOVE_TABLE_SELECT_PLACEHOLDER: "Chọn đơn hàng",
      MOVE_TABLE_ORDER_REQUIRED: "Không tìm thấy đơn hàng của bàn này",
      MOVE_TABLE_DESTINATION_REQUIRED: "Chọn bàn đích để chuyển",
      CANCEL: "Hủy đơn",
      CANCEL_CONFIRM: "Bạn có chắc chắn muốn hủy đơn hàng trống này không?",
      CANCEL_SUCCESS: "Hủy đơn hàng thành công",
      CANCEL_ERROR: "Hủy đơn hàng thất bại",
    },
  },
  CURRENT: {
    TOTAL_AMOUNT: "Tổng thanh toán",
    PAYMENT_METHOD: "Phương thức thanh toán",
    CASH: "Tiền mặt",
    TRANSFER: "Chuyển khoản",
    CARD: "Thẻ (POS)",
    CUSTOMER_GAVE: "Khách đưa",
    CHANGE: "Tiền thối lại",
    PROCESSING: "Đang xử lý...",
    SUBTOTAL: "Tạm tính",
    TAX: "Thuế (VAT 10%)",
    DISCOUNT: "Giảm giá",
    ADD_TO_ORDER: "Thêm vào đơn",
    PAY: "Thanh toán",
    PRINT_TEMP_ACTION: "In tạm tính",
    EMPTY: "Chưa có món nào trong đơn hàng",
    CONFIRM_PAYMENT: "Xác nhận thanh toán",
    CHECKOUT_TITLE: "Thanh toán đơn hàng",
    CHECKOUT_DESC: "Vui lòng chọn phương thức thanh toán và xác nhận",
    NEW: "Mới",
    STATUS_PREP: "Đang chuẩn bị",
    STATUS_COOKING: "Đang nấu",
    STATUS_DONE: "Hoàn tất",
    STATUS_SERVING: "Đang phục vụ",
    STATUS_COMPLETED: "Đã hoàn thành",
    STATUS_CANCELLED: "Đã hủy",
    STATUS_REJECTED: "Đã từ chối",
    STATUS_PAID: "Đã thanh toán",
    TAKEAWAY: "Mang đi",
    DINE_IN: "Dùng tại bàn",
    QR_CREATE_ERROR: "Không thể tạo mã QR thanh toán.",
    QR_FETCH_ERROR: "Đã xảy ra lỗi khi tải mã QR.",
    PAYMENT_RECEIVED: "Hệ thống đã nhận được tiền!",
    INPUT_AMOUNT_REQUIRED: "Vui lòng nhập số tiền khách đưa",
    INVALID_AMOUNT: "Số tiền khách đưa không hợp lệ hoặc nhỏ hơn tổng tiền",
    PAYMENT_SUCCESS: "Thanh toán thành công!",
    PAYMENT_FAILED: "Thanh toán thất bại, vui lòng thử lại.",
    PAYMENT_ERROR: "Đã xảy ra lỗi trong quá trình thanh toán.",
    SELECT_TABLE_REQUIRED: "Vui lòng chọn bàn trước khi gửi yêu cầu",
    ORDER_NOT_FOUND: "Không tìm thấy thông tin đơn hàng",
    CART_EMPTY: "Giỏ hàng đang trống",
    SUBMIT_SUCCESS: "Đã gửi yêu cầu vào bếp thành công!",
    SUBMIT_FAILED: "Gửi vào bếp thất bại",
    SUBMIT_ERROR: "Đã có lỗi xảy ra khi gửi yêu cầu",
  },
  PRINT_TEMP: {
    TITLE: "PHIẾU TẠM TÍNH",
    TIME: "Ngày in",
    EMPLOYEE: "Nhân viên",
    ORDER_CODE(orderCode: string) {
      return `Mã Đơn Hàng: ${orderCode}`;
    },
    MENU_NAME: "Tên món",
    QUANTITY: "Số lượng",
    UNIT_PRICE: "Đơn giá",
    AMOUNT: "Thành tiền",
    TAX_LABEL: "Thuế GTGT (10%)",
    BEFORE_TAX: "Tổng trước thuế",
    TOTAL_AMOUNT: "Tổng thanh toán",
    THIS_IS_NOT_RECEIPT: "Đây không phải là hóa đơn thanh toán",
    THANK_YOU: "Cảm ơn quý khách và hẹn gặp lại!",
  },
  DETAIL: {
    TITLE: "Chi tiết đơn hàng",
    DESCRIPTION_MANAGER: "Theo dõi thông tin, món, thanh toán và nhật ký thao tác của đơn hàng.",
    BACK_TO_LIST: "Quay lại danh sách",
    LOADING: "Đang tải chi tiết đơn...",
    EMPTY_TITLE: "Chưa có dữ liệu đơn hàng",
    EMPTY_DESC: "Không tìm thấy đơn tương ứng.",
    TAB_OVERVIEW: "Tổng quan",
    TAB_ITEMS: "Món",
    TAB_PAYMENT: "Thanh toán",
    TAB_AUDIT: "Nhật ký",
    TIMELINE_TITLE: "Mốc thời gian",
    TIMELINE_DESC: "Lifecycle của đơn hàng.",
    TIMELINE_CREATE: "Tạo đơn",
    TIMELINE_UPDATE: "Cập nhật",
    TIMELINE_PAID: "Thanh toán",
    TIMELINE_COMPLETE: "Hoàn tất",
    TIMELINE_CANCEL: "Hủy",
    ORDER_TYPE: "Loại đơn",
    TABLE_RESERVATION: "Bàn / reservation",
    SUBTOTAL: "Tạm tính",
    TOTAL_AMOUNT: "Tổng thanh toán",
    ITEMS_TITLE: "Danh sách món",
    ITEMS_EMPTY_TITLE: "Đơn chưa có món",
    ITEMS_EMPTY_DESC: "Danh sách món sẽ xuất hiện tại đây.",
    QTY_LABEL: "SL:",
    PRICE_LABEL: "Đơn giá:",
    NOTE_LABEL: "Ghi chú:",
    LINE_TOTAL: "Thành tiền",
    SECTION_NOTE: "Trạng thái món, option, ghi chú và tổng từng dòng.",
    PAYMENT_TITLE: "Thanh toán",
    PAYMENT_METHOD: "Phương thức",
    PAYMENT_RECEIVED: "Đã nhận",
    PAID_AT: "Paid at",
    VAT: "VAT",
    PRECHECK_TITLE: "Pre-check bill",
    PRECHECK_DESC: "Chỉ đơn đang phục vụ mới hiển thị dữ liệu này.",
    PRE_SUBTOTAL: "Tạm tính",
    PRE_PRETAX: "Pre-tax",
    PRE_VAT: "VAT",
    PRE_TOTAL: "Tổng",
    PRE_EMPTY_TITLE: "Chưa có phiếu tạm tính",
    AUDIT_TIMELINE: "Dòng thời gian đơn",
    AUDIT_BE_TITLE: "Audit log BE",
    AUDIT_BE_DESC:
      "Theo dõi các thao tác đã xảy ra trên đơn hàng, bao gồm người thực hiện, thời gian và dữ liệu thay đổi.",
    ITEM_COUNT: (count: number) => `${count} món trong đơn`,
    SPLIT_BILL: "Tách bill",
    SPLIT_BILL_PROMPT: (name: string) => `Nhập số lượng muốn tách từ "${name}"`,
    SPLIT_BILL_INVALID_QTY: "Số lượng tách không hợp lệ.",
    SPLIT_BILL_SUCCESS: "Tách bill thành công.",
    SPLIT_BILL_FAILED: "Tách bill thất bại.",
    ORDER_NOT_FOUND_FOR_TABLE: "Không tìm thấy đơn hàng của bàn này",
    DISCOUNT_AMOUNT: "Giảm giá",
    PROMOTION_CODE: "Mã khuyến mãi",
    VOUCHER_CODE: "Mã Voucher",
    NOTE: "Ghi chú đơn hàng",
    VAT_RATE: (rate: number) => `Thuế (VAT ${rate}%)`,
    PAYMENT_INFO: "Thông tin thanh toán",
    CUSTOMER_INFO: "Thông tin khách hàng",
    RESERVATION_ID: "Mã đặt chỗ",
    TABLE_ID: "Số bàn",
    SUBTOTAL_BEFORE_DISCOUNT: "Tạm tính (trước giảm)",
  },
  MANAGEMENT: {
    WORKSPACE_TITLE: "Workspace quản lý đơn hàng",
    WORKSPACE_DESC:
      "Một màn cho manager: xem đơn, soi thanh toán và giữ layout audit log sẵn sàng.",
    RELOAD: "Tải lại",
    STATS: {
      TOTAL: "Tổng đơn",
      SERVING: "Đang phục vụ",
      REVENUE: "Doanh thu",
      VIP: "VIP",
    },
    TABS: {
      ORDERS: "Danh sách đơn",
      BILLING: "Lịch sử thanh toán",
      AUDIT: "Nhật ký thao tác",
    },
    PAGE_COUNT: (count: number) => `${count} trang`,
  },
  OVERVIEW: {
    HERO_TITLE: "Quản lý đơn hàng",
    HERO_DESC: "Theo dõi trạng thái đơn, thanh toán và audit từ một nơi.",
    FETCH_ERROR: "Không thể tải tổng quan đơn hàng.",
    STATS: {
      ACTIVE: "Tổng đơn đang hoạt động",
      WAITING: "Chờ thanh toán",
      PAID_TODAY: "Đã thanh toán hôm nay",
    },
    BILLING_HISTORY: {
      TITLE: "Lịch sử thanh toán",
      LOADING: "Đang tải lịch sử thanh toán...",
      EMPTY: "Chưa có giao dịch thanh toán nào.",
      UNKNOWN_METHOD: "Chưa rõ",
    },
    AUDIT: {
      TITLE: "Nhật ký thao tác",
      LOADING: "Đang tải nhật ký thao tác...",
      EMPTY: "Chưa có dữ liệu audit log từ API.",
      SERVING_ACTION: "Đang phục vụ",
      UPDATE_ACTION: "Cập nhật đơn",
    },
    DISTRIBUTION: {
      ORDER_TYPE: "Cơ cấu theo loại đơn",
      ORDER_TYPE_DESC:
        "Theo dõi nhanh tỷ trọng đơn tại bàn, mang đi và giao hàng trong ca hiện tại.",
      ORDER_STATUS: "Phân bổ theo trạng thái",
      ORDER_STATUS_DESC:
        "Tập trung vào các trạng thái vận hành chính để biết khu bếp và thu ngân đang ở đâu.",
      EMPTY_TYPE: "Chưa có dữ liệu loại đơn để hiển thị.",
      EMPTY_STATUS: "Chưa có dữ liệu trạng thái để hiển thị.",
    },
    STATUS_LABELS: {
      SERVING: "Đang phục vụ",
      COMPLETED: "Bếp đã hoàn tất",
      WAITING_CHECKOUT: "Chờ thanh toán",
    },
  },
  BILLING: {
    TITLE: "Lịch sử thanh toán",
    SEARCH_PLACEHOLDER: "Tìm theo mã đơn hoặc khách",
    METHOD_PLACEHOLDER: "Phương thức",
    TYPE_PLACEHOLDER: "Loại đơn",
    ALL_METHODS: "Phương thức thanh toán",
    CASH: "Tiền mặt",
    TRANSFER: "Chuyển khoản",
    CARD: "Thẻ",
    DELIVERY: "Giao hàng",
    DINE_IN: "Dùng tại bàn",
    TAKEAWAY: "Mang đi",
    FETCH_ERROR: "Không thể tải lịch sử thanh toán.",
    LOADING: "Đang tải lịch sử thanh toán...",
    EMPTY: "Chưa có giao dịch thanh toán nào phù hợp.",
    COLUMNS: {
      ORDER_CODE: "Mã đơn",
      ORDER_TYPE: "Loại đơn",
      METHOD: "Phương thức",
      PAID_AT: "Paid at",
      TOTAL: "Tổng tiền",
      STATUS: "Trạng thái",
    },
  },
};
