export const SALES_ANALYTICS = {
  TITLE: "Phân tích & Thống kê",
  DESCRIPTION: "Theo dõi hiệu suất kinh doanh của nhà hàng của bạn.",
  WIP_TITLE: "Tính năng đang phát triển",
  WIP_DESC:
    "Tính năng này hiện đang trong quá trình phát triển. Vui lòng quay lại sau để xem các báo cáo chi tiết.",
  BEST_SELLERS_ANALYSIS: "Phân tích món bán chạy",
  TOP_CATEGORY: "Danh mục hiệu quả nhất",
  MOST_PROFITABLE: "Món sinh lời nhất",
  TOTAL_ITEM_SALES: "Tổng số lượng bán",
  SEARCH_PLACEHOLDER: "Tìm kiếm món ăn...",
  FILTER_CATEGORY: "Lọc theo danh mục",
  SORT_BY: "Sắp xếp theo",
  REVENUE_OVER_TIME: "Doanh thu theo thời gian",
  REVENUE_BY_CATEGORY: "Doanh thu theo danh mục",
  DAILY: "Ngày",
  MONTHLY: "Tháng",
  MAIN_DISH: "Món chính",
  STARTER: "Khai vị",
  DRINK: "Đồ uống",
  DESSERT: "Tráng miệng",
  RANK: "#",
  ITEM_NAME: "Món ăn",
  CATEGORY: "Danh mục",
  QUANTITY: "Số lượng",
  REVENUE: "Doanh thu",
  TOTAL_PERCENT: "% Tổng",
  TOTAL_REVENUE: "Tổng doanh thu",
  TOTAL_ORDERS: "Tổng số đơn",
  AVG_ORDER_VALUE: "Giá trị trung bình",
  GROSS_PROFIT: "Lợi nhuận gộp",
  SALES_TARGET_LABEL: "Mục tiêu",
  STABLE_OPERATIONS: "Vận hành ổn định",
  REAL_TIME_UPDATE: "Cập nhật theo thời gian thực",
  QUICK_INSIGHTS: "Phân tích nhanh",
  OPERATIONAL_SUGGESTION: "Gợi ý vận hành",
  MANAGER_ONLY: "Chỉ Quản lý mới có quyền xem dữ liệu chi tiết này.",
  EXPORT_REPORT: "Xuất báo cáo",
  SELECT_DATE: "Chọn ngày",
  EXPORT_BY_RANGE: "Theo khoảng ngày",
  EXPORT_BY_MONTH: "Theo tháng",
  SELECT_MONTH: "Chọn tháng",
  SELECT_YEAR: "Chọn năm",
  BEST_ITEM_INSIGHT: (name: string, percent: number) =>
    `Món ${name} hiệu quả nhất, đóng góp ${percent}% doanh thu.`,
  CATEGORY_INSIGHT: (name: string) => `Danh mục ${name} dẫn đầu. Nên tối ưu menu.`,
};
