export const SHIFT = {
  TITLE: "Quản lý ca làm việc",
  ADD_SHIFT: "Tạo ca làm việc",
  EDIT_SHIFT: "Chỉnh sửa ca làm việc",
  SHIFT_NAME: "Tên ca làm việc",
  START_TIME: "Giờ bắt đầu",
  END_TIME: "Giờ kết thúc",
  STATUS: "Trạng thái",
  ACTIVE: "Đang hoạt động",
  INACTIVE: "Tạm dừng",
  TOTAL_ACTIVE: "TỔNG ĐANG HOẠT ĐỘNG",
  STAFF_WORKING: "NHÂN VIÊN ĐANG LÀM",
  OVERTIME_RISK: "RỦI RO TĂNG CA",
  VACANT_POSITIONS: "VỊ TRÍ TRỐNG",
  DESCRIPTION: "Mô tả",
  POSITION: "Vị trí công việc",
  PLACEHOLDER_NAME: "VD: Ca Sáng",
  PLACEHOLDER_DESC: "Mô tả chi tiết về ca làm việc...",
  PLACEHOLDER_POSITION: "Chọn vị trí...",
  CREATE_SUCCESS: "Tạo ca làm việc thành công",
  UPDATE_SUCCESS: "Cập nhật ca làm việc thành công",
  DELETE_SUCCESS: "Xóa ca làm việc thành công",
  PAGE_DESC: "Cấu hình và giám sát khung thời gian làm việc cho nhân sự.",
  REPORT_DESC: "Tỷ lệ chuyên cần của nhân viên đã tăng kể từ khi áp dụng lịch mới.",
  ADD_NEW: "Thêm ca làm việc mới",
  ADD_DESC: "Điền thông tin để tạo ca làm việc mới cho nhà hàng.",
  EDIT_DESC: "Cập nhật thông tin chi tiết cho ca làm việc này.",
  DETAILS: "Chi tiết ca",
  MEDIA: "Hình ảnh & Media",
  STATS_WEEKLY_CHANGE: "+2 tuần này",
  STATS_OVERTIME_WARNING: "Cảnh báo cao",
  STATS_UNASSIGNED: "Chưa gán",
};

export const SCHEDULE = {
  TITLE: "Quản lý lịch làm việc",
  WEEK: "TUẦN NÀY",
  COPY_PREVIOUS: "Sao chép tuần trước",
  SAVE_SCHEDULE: "Lưu lịch",
  TOTAL_STAFF: "TỔNG NHÂN SỰ",
  ESTIMATED_HOURS: "GIỜ LÀM DỰ KIẾN",
  ESTIMATED_COST: "CHI PHÍ ƯỚC TÍNH",
  SHIFT_COVERAGE: "ĐỘ PHỦ CA",
  EMPLOYEE_NAME: "NHÂN VIÊN",
  TODAY: "HÔM NAY",
  MORNING_SHIFT: "CA SÁNG",
  AFTERNOON_SHIFT: "CA CHIỀU",
  PAGE_TEXT: "Trang",
  REPORT_TITLE: "BÁO CÁO HIỆU QUẢ CA LÀM",
  VIEW_ANALYTICS: "XEM PHÂN TÍCH",
  PENDING_REQUESTS: "YÊU CẦU ĐANG CHỜ",
  VIEW_ALL_REQUESTS: "XEM TẤT CẢ YÊU CẦU",
  ADMIN_TITLE: "CRIMSON STUDIO ADMIN",
  WEEK_DATES: "20/10 — 26/10",
  STATS_STAFF_SUB: "+2 nhân viên mới tuần này",
  STATS_HOURS_SUB: "Dựa trên lịch đã xếp",
  STATS_COST_SUB: "VND (Lương cơ bản)",
  ASSIGN_TITLE: "Phân công ca làm việc",
  ASSIGN_DESC: "Gán ca làm việc cho nhân viên vào ngày cụ thể.",
  SELECT_SHIFT: "Chọn ca làm việc",
  SELECT_SHIFT_PLACEHOLDER: "Chọn ca...",
  NOTE_LABEL: "Ghi chú",
  NOTE_PLACEHOLDER: "VD: Làm bù cho tuần trước",
  ASSIGN_BUTTON: "Phân công",
  WORK_DATE: "Ngày làm việc",
  UPDATE_SUCCESS: "Cập nhật phân công thành công",
  DELETE_SUCCESS: "Gỡ phân công thành công",
  CONFIRM_DELETE: "Bạn có chắc chắn muốn gỡ phân công này không?",
  EDIT_TITLE: "Chỉnh sửa phân công",
  REMOVE_BUTTON: "Gỡ phân công",
  HOURS_UNIT: "h",
  REQUEST_TYPE_SHIFT_CHANGE: "Đổi ca - Ca chiều",
  REQUEST_TYPE_LEAVE: "Nghỉ phép - Thứ Sáu",
  NOW: "Bây giờ",
  NEXT_WEEK: "Tuần sau",
  NEXT_2_WEEKS: "2 tuần nữa",
  NEXT_MONTH: "Tháng sau",
  SELECT_WEEK: "Chọn tuần làm việc",
  ASSIGNED_SHIFT: "Ca đã gán",
  EMPTY_SHIFT: "Trống (Di chuột để gán)",
  AUTO_SAVE: "Tự động lưu thay đổi nhanh",
  CHOOSE_WEEK: "CHỌN TUẦN LÀM VIỆC",
  PERIOD: "Khoảng thời gian",
};
