export const VOUCHER = {
  TITLE: "Quản lý Voucher",
  DESCRIPTION: "Quản lý mã giảm giá và chương trình khuyến mãi",
  CREATE: "Tạo Voucher",
  EDIT: "Chỉnh sửa Voucher",
  UPDATE: "Cập nhật Voucher",
  DETAILS: "Voucher Details",

  SEARCH_PLACEHOLDER: "Tìm mã voucher...",
  FILTER_TYPE: "Type",
  FILTER_STATUS: "Status",
  FILTER_ALL_TYPE: "Tất cả loại",
  FILTER_ALL_STATUS: "Tất cả trạng thái",
  FILTER_ACTIVE: "Hoạt động",
  FILTER_INACTIVE: "Tạm ngưng",
  STATS_ACTIVE: "đang hoạt động",
  STATS_INACTIVE: "tạm ngưng",

  TABLE_CODE: "Voucher Code",
  TABLE_TYPE: "Loại",
  TABLE_VALUE: "Giá trị",
  TABLE_USAGE: "Sử dụng",
  TABLE_VALIDITY: "Thời gian hiệu lực",
  TABLE_STATUS: "Trạng thái",
  TABLE_ACTIONS: "Thao tác",

  ACTION_VIEW: "Xem chi tiết",
  ACTION_VIEW_DESC: "Xem thông tin voucher",
  ACTION_EDIT: "Chỉnh sửa",
  ACTION_EDIT_DESC: "Cập nhật thông tin voucher",
  ACTION_DELETE: "Xóa voucher",
  ACTION_DELETE_DESC: "Gỡ khỏi hệ thống",
  ACTION_RETRY: "Thử lại",
  ACTION_CLOSE: "Đóng",
  ACTION_CANCEL: "Hủy",
  ACTION_SAVE: "Tạo Voucher",
  ACTION_ACTIVATE: "Kích hoạt",
  ACTION_DEACTIVATE: "Tạm ngưng",
  ACTION_TOGGLE_DESC: "Thay đổi trạng thái",

  STATUS_ACTIVE: "Hoạt động",
  STATUS_INACTIVE: "Tạm ngưng",
  STATUS_EXPIRED: "Hết hạn",
  STATUS_LABEL: "Trạng thái:",

  NOT_FOUND: "Không tìm thấy voucher nào",
  DELETE_CONFIRM: (code: string) => `Bạn có chắc chắn muốn xóa voucher "${code}"?`,

  PAGINATION_SHOWING: "Hiển thị",
  PAGINATION_OF: "vouchers",
  PAGINATION_PREV: "‹",
  PAGINATION_NEXT: "›",
  ARROW: "→",

  SECTION_BASIC: "Thông tin cơ bản",
  SECTION_VALUE: "Giá trị & Giới hạn",
  SECTION_VALIDITY: "Thời gian hiệu lực",
  SECTION_USAGE: "Sử dụng & Trạng thái",

  FIELD_CODE: "Mã voucher",
  FIELD_CODE_PLACEHOLDER: "VD: SUMMER50",
  FIELD_TYPE: "Loại voucher",
  FIELD_DISCOUNT_PERCENT: "Giá trị giảm (%)",
  FIELD_DISCOUNT_FIXED: "Giá trị giảm (đ)",
  FIELD_MAX_DISCOUNT: "Giảm tối đa (đ)",
  FIELD_MAX_DISCOUNT_PLACEHOLDER: "Tùy chọn",
  FIELD_MIN_ORDER: "Đơn tối thiểu (đ)",
  FIELD_START_DATE: "Bắt đầu",
  FIELD_END_DATE: "Kết thúc",
  FIELD_START_TIME: "Giờ bắt đầu",
  FIELD_END_TIME: "Giờ kết thúc",
  FIELD_USAGE_LIMIT: "Giới hạn sử dụng",
  FIELD_STATUS: "Trạng thái hoạt động",
  FIELD_STATUS_ON: "Kích hoạt",
  FIELD_STATUS_OFF: "Tạm ngưng",

  FREE_ITEM_TITLE: "Cấu hình tặng món",
  FREE_ITEM_ID: "ID Món tặng",
  FREE_ITEM_QTY: "Số lượng",

  VALIDATE_CODE_REQUIRED: "Vui lòng nhập mã voucher",
  VALIDATE_DATE_REQUIRED: "Vui lòng chọn ngày bắt đầu và kết thúc",
  VALIDATE_DATE_ORDER: "Ngày kết thúc phải sau ngày bắt đầu",

  CREATE_DESC: "Thiết lập chương trình khuyến mãi mới.",
  EDIT_DESC: "Cập nhật thông tin voucher khuyến mãi.",
  SAVING: "Đang lưu...",

  DETAIL_BASIC: "Thông tin cơ bản",
  DETAIL_CONDITIONS: "Điều kiện",
  DETAIL_STATS: "Thống kê sử dụng",
  DETAIL_CODE: "Mã voucher",
  DETAIL_NAME: "Tên",
  DETAIL_TYPE: "Loại",
  DETAIL_VALUE: "Giá trị",
  DETAIL_MIN_ORDER: "Đơn tối thiểu",
  DETAIL_MAX_DISCOUNT: "Giảm tối đa",
  DETAIL_TIME_RANGE: "Thời gian",
  DETAIL_TIME_OF_DAY: "Khung giờ",
  DETAIL_ALL_DAY: "Cả ngày",
  DETAIL_FREE_ITEM: "Món tặng",
  DETAIL_UNLIMITED: "Không giới hạn",
  DETAIL_USED: "đã dùng",
  DETAIL_ENABLE: "Kích hoạt Voucher",
  DETAIL_ENABLE_DESC: "Cho phép khách sử dụng mã này",
  DETAIL_FREE_ITEM_LABEL: "Tặng món",

  SECTION_NUM_1: "1",
  SECTION_NUM_2: "2",
  SECTION_NUM_3: "3",
  SECTION_NUM_4: "4",

  SIDEBAR_TITLE: "Voucher",

  APPLY_MODAL_TITLE: "Áp dụng mã giảm giá",
  APPLY_MODAL_DESC: "Nhập mã voucher để nhận ưu đãi cho đơn hàng.",
  APPLY_MODAL_PLACEHOLDER: "Nhập mã voucher...",
  APPLY_MODAL_APPLY: "Áp dụng",
  APPLY_MODAL_REMOVE: "Gỡ bỏ",
  APPLY_MODAL_CURRENT: "Mã đang áp dụng:",
  APPLY_SUCCESS: "Áp dụng mã giảm giá thành công!",
  APPLY_ERROR: "Không thể áp dụng mã giảm giá",
  ERROR_MIN_AMOUNT: "Giá trị đơn hàng chưa đạt mức tối thiểu để sử dụng mã này",
  ERROR_ALREADY_APPLIED: "Đơn hàng này đã áp dụng mã giảm giá rồi",
  REMOVE_SUCCESS: "Đã gỡ mã giảm giá",
  REMOVE_ERROR: "Không thể gỡ mã giảm giá",
  LIST_AVAILABLE: "Danh sách voucher khả dụng",
  LOADING_LIST: "Đang tải danh sách...",
  EXPIRY_SHORT: "HSD:",
  EMPTY_LIST: "Không có voucher nào khả dụng lúc này",
  APPLIED: "Đã áp dụng",
};
