export const ATTENDANCE = {
  REPORT_TITLE: "Attendance Report",
  REPORT_DESCRIPTION: "Track and manage employee working hours.",
  EXPORT_EXCEL: "Export Excel",
  EXPORT_SUCCESS: "Report exported successfully",
  EXPORT_FAILURE: "Export failed",

  FILTER_DATE: "Select date",
  FILTER_EMPLOYEE: "Employee",
  FILTER_STATUS: "Status",
  FILTER_ALL_EMPLOYEES: "All employees",
  FILTER_ALL: "All",
  FILTER_BUTTON: "FILTER",

  TABLE_DATE: "Date",
  TABLE_EMPLOYEE: "Employee",
  TABLE_SHIFT: "Shift",
  TABLE_CHECK_IN: "Check-in",
  TABLE_CHECK_OUT: "Check-out",
  TABLE_STATUS: "Status",
  TABLE_EMPTY: "No data",

  STATUS_ON_TIME: "On time",
  STATUS_LATE: "Late",
  STATUS_EARLY_LEAVE: "Left early",
  STATUS_ABSENT: "Absent",

  STAT_TOTAL_STAFF: "Total staff",
  STAT_ON_TIME: "On time",
  STAT_LATE: "Late",
  STAT_PENALTY: "Late penalty (est.)",
  STAT_NOTE: "Attention needed",
  STAT_CURRENCY: "VNĐ",
  STAT_MONTH_CHANGE: "this month",

  PORTAL_TODAY_SHIFT: "Today's shift",
  PORTAL_WORKING: "WORKING",
  PORTAL_UPCOMING: "UPCOMING",
  PORTAL_CHECK_IN: "Check in",
  PORTAL_CHECK_OUT: "Check out",
  PORTAL_CAMERA_NOTE: "Please stand in front of the camera to verify identity",
  PORTAL_LOCATION: "Current location",
  PORTAL_NETWORK: "Network status",
  PORTAL_NETWORK_STABLE: "Stable",
  PORTAL_MOCK_SHIFT_NAME: "Morning Shift",
  PORTAL_MOCK_SHIFT_TIME: "10:30 \u2014 14:00",
  PORTAL_MOCK_LOCATION: "Studio District 1",
  PORTAL_NO_SHIFT: "No shift scheduled",
  PORTAL_WARNING_TITLE: "WARNING",
  PORTAL_LATE_CHECKIN: "Shift check-in time has passed!",
  PORTAL_EMPTY_SHIFT: "EMPTY",
  PORTAL_MY_SCHEDULE: "My schedule",
  PORTAL_SCHEDULE_EMPTY: "No schedule assigned to you yet",
  PORTAL_NOTE_LABEL: "Note:",
  PORTAL_TAB_ATTENDANCE: "Attendance",
  PORTAL_TAB_SCHEDULE: "Schedule",

  MODAL_CHECK_IN_SUCCESS: "Check-in Successful",
  MODAL_CHECK_OUT_SUCCESS: "Check-out Successful",
  MODAL_CHECK_IN_TIME: "You checked in at",
  MODAL_CHECK_OUT_TIME: "You checked out at",
  MODAL_GREETING: "Have an energetic work session!",
  MODAL_STATS_TODAY: "Today's stats",
  MODAL_TOTAL_TIME: "Total working time:",
  MODAL_UNDERSTOOD: "Got it",
  MODAL_CHECK_IN_FAIL: "Check-in failed",
  MODAL_CHECK_OUT_FAIL: "Check-out failed",
};
