export const AUDIT_LOG = {
  TITLE: "System History",
  TITLE_BADGE: "Activity Log",
  EMPTY: "No history yet",
  FETCH_ERROR: "Could not load system history",
  LOG_ID: "Log ID",
  ORDER_ID: "Order ID",
  EMPLOYEE_ID: "Employee ID",
  ACTION: "Action",
  NO_CHANGES: "No changes",
  OLD_VALUE: "Old value",
  NEW_VALUE: "New value",
  ACTOR_LABEL: "Actor",
  METADATA_LABEL: "Data",
  CHANGE_DETAILS: "Change Details",
  BEFORE_CHANGE: "Before change",
  AFTER_CHANGE: "After change",
  CREATED_AT: "Timestamp",
  REASON: "Reason / Note",
  PANEL_TITLE: "Audit log panel",
  PANEL_DESC: "Track operations in the system including the performer, time, and data changes.",
  TIME: "Time",
  ACTOR: "Performed by",
  ACTOR_NAME: "Performer name",
  ACTOR_ROLE: "Role",
  ACTIONS_METADATA: "Action, reason, before/after metadata",
  TIMELINE_TITLE: "Recent timeline",
  EMPTY_TITLE: "Select an order to view audit log",
  EMPTY_DESC: "The audit log will appear here when you select an order.",
  GLOBAL_EMPTY_TITLE: "No audit logs yet",
  GLOBAL_EMPTY_DESC:
    "Audit logs for all orders will appear here when the system generates new operations.",
  ENTITY: "Entity",
  ENTITY_ID: "Entity ID",
  SYSTEM: "System",
  ALL_ENTITY: "All entities",
  ALL_ACTION: "All actions",
  FILTER: {
    TITLE: "Filters",
    DESC: "Filter by time, action, and entity to retrieve change history.",
    APPLY: "Apply",
    RESET: "Reset",
    SEARCH_PLACEHOLDER: "Search by order code, action, performer, or change notes",
    ACTION_LABEL: "Filter by action",
  },
  STATS: {
    TOTAL: "Total records",
    CURRENT_PAGE: "Current page",
    PAGE_SIZE: "Page size",
  },
  DESCRIPTION:
    "Track all changes in the system including the performer, time, and values before/after the change.",
  SYSTEM_INTELLIGENCE: "System Intelligence",
  LOGS: "records",
  OF: "of",
  PAGES: "pages",
  PREVIOUS: "Previous",
  NEXT: "Next",
  RAW_STATE_BEFORE: "RAW STATE BEFORE",
  RAW_STATE_AFTER: "RAW STATE AFTER",
  MODIFIED_LABEL: "MODIFIED",
  CHANGE_DETECTED: "Change detected",
  CLOSE_LOGS: "Close history",
  ACTOR_INTELLIGENCE: "Actor information",
  TRANSACTION_INFO: "Transaction information",
  PLACEHOLDER: {
    TITLE:
      "Collection of data change activities from Reservation, Table, and other configurations.",
    DESCRIPTION: "Select an action to view details of changed data fields.",
  },
  SUB_TITLE: "Track reservation and table changes",
  SUB_DESC: "Managers can quickly read who performed what action and view details when needed.",
  TECHNICAL_INFO: "Technical information",
  LOGGED_AT: "Logged at",
  ACTOR_BY: "Performed by",
  ENTITIES: {
    ALL: "All entities",
    RESERVATION: "Reservation",
    TABLE: "Table",
    ORDER: "Order",
    EMPLOYEE: "Employee",
    MENU: "Menu",
    AREA: "Area",
    PROMOTION: "Promotion",
    UNKNOWN: "Other entity",
  },
  ACTIONS_LIST: {
    ALL: "All actions",
    CREATE: "Create",
    UPDATE: "Update",
    DELETE: "Delete",
    STATUS_CHANGE: "Status change",
    CANCEL: "Cancel",
    CHECK_IN: "Check-in",
    NO_SHOW: "No show",
  },
  FIELDS: {
    Field: "FIELD",
    CustomerName: "Customer",
    CustomerPhone: "Phone number",
    ReservationDate: "Reservation date",
    ReservationTime: "Reservation time",
    GuestCount: "Guest count",
    Note: "Note",
    Status: "Status",
    AreaId: "Area",
    TableId: "Table",
    Capacity: "Capacity",
    TableNumber: "Table number",
    AreaName: "Area name",
    IsActive: "Active status",
    UpdatedAt: "Updated at",
    UpdatedBy: "Updated by",
    CreatedAt: "Created at",
    CreatedBy: "Created by",
  },
  ACTOR_INFO: {
    GUEST: "Guest",
    GUEST_SUB: "Unauthenticated user",
    EMPLOYEE: "Employee",
    EMPLOYEE_ID: "Employee {id}",
    INTERNAL: "Internal system",
    IP_PREFIX: "IP",
  },
  SUBJECTS: {
    RESERVATION: "reservation of {name} ({phone})",
    RESERVATION_NAME: "reservation of {name}",
    RESERVATION_ID: "reservation {id}",
    TABLE_NUM: "table {number}",
    TABLE_ID: "table {id}",
  },
  MESSAGES: {
    EMPTY_HINT: "Try changing filters or perform a reservation, table status change to test.",
    NO_DETAIL_CHANGES: "No detailed changes to display.",
    NULL_VALUE: "empty",
    YES_VALUE: "yes",
    NO_VALUE: "no",
  },
  ACTION_RESULTS: {
    CHECK_IN: "{actor} checked in {subject}.",
    CANCEL: "{actor} cancelled {subject}.",
    STATUS_CHANGE: "{actor} changed the status of {subject}.",
    GENERIC: "{actor} {action} {subject}.",
  },
  ACTIONS: {
    CREATE_ORDER: "Create order",
    SUBMIT_ORDER: "Send to kitchen",
    ADD_ORDER_ITEM: "Add item",
    UPDATE_ORDER_ITEM: "Update item",
    ADJUST_ORDER_ITEM_QUANTITY: "Adjust quantity",
    CANCEL_ORDER_ITEM: "Cancel item",
    CANCEL_ORDER: "Cancel order",
    COMPLETE_ORDER: "Complete order",
    CHECKOUT_ORDER: "Checkout",
    CHANGE_ORDER_TABLE: "Change table",
    MERGE_ORDER: "Merge orders",
    SPLIT_ORDER: "Split order",
    KDS_START_COOKING: "Kitchen cooking",
    KDS_COMPLETE_COOKING: "Kitchen done",
    KDS_REJECT: "Kitchen reject",
    APPLY_PROMOTION: "Promotion",
  },
  TECHNICAL_LOG_HINT:
    "This record contains technical system changes. Please see details in the section below.",
};
