export const AUTH = {
  LOGIN: "Login",
  LOGOUT: "Logout",
  REGISTER: "Register",
  EMAIL: "Email",
  PASSWORD: "Password",
  LOGIN_TITLE: "Welcome back",
  EMPLOYEE_CODE: "Employee code",
  EMPLOYEE_CODE_PLACEHOLDER: "e.g. M000001",
  REMEMBER_ME: "Remember me",
  FORGOT_PASSWORD: "Forgot password?",
  FORGOT_PASSWORD_TITLE: "Forgot password?",
  FORGOT_PASSWORD_DESC: "Please enter your Employee code to recover your password.",
  FORGOT_PASSWORD_PLACEHOLDER: "e.g. WA001",
  SEND_REQUEST: "Send request",
  SENDING: "Sending...",
  BACK_TO_LOGIN: "Back to login",
  LOGGING_OUT: "Logging out...",
  ERROR_INVALID_CREDENTIALS: "Invalid employee code or password",
  RESET_PASSWORD: {
    TITLE: "Reset password",
    DESC: "Please enter a new password for your account.",
    INVALID_TOKEN: "Token is invalid or has expired.",
    MISMATCH: "Confirmation password does not match.",
    SUCCESS: "Password reset successful! Please log in again.",
    FAILED: "Password reset failed.",
    ERROR_TITLE: "Error!",
    TOKEN_MISSING: "Password recovery token does not exist or is invalid.",
    REQUEST_NEW: "Request new code",
    NEW_PASSWORD: "New password",
    NEW_PASSWORD_PLACEHOLDER: "Enter new password",
    CONFIRM_NEW_PASSWORD: "Confirm new password",
    CONFIRM_NEW_PASSWORD_PLACEHOLDER: "Re-enter new password",
    UPDATE_BUTTON: "Update password",
  },
};

export const CHANGE_PASSWORD = {
  TITLE: "Change password",
  BUTTON: "Change password",
  CURRENT_PASSWORD: "Current password",
  NEW_PASSWORD: "New password",
  CONFIRM_PASSWORD: "Confirm password",
  CONFIRM_NOT_MATCH: "Confirmation password does not match",
  REQUIRED: "Please fill in all fields",
  UPPERCASE_REQUIRED: "New password must contain at least one uppercase letter",
  LOWERCASE_REQUIRED: "New password must contain at least one lowercase letter",
  NUMBER_REQUIRED: "New password must contain at least one digit",
  SPECIAL_CHAR_REQUIRED: "New password must contain at least one special character",
  MIN_LENGTH: "New password must be at least 8 characters",
};

export const RESET_PASSWORD = {
  TITLE: "Reset password",
  DESC: "Please enter a new password for your account.",
  INVALID_TOKEN: "Token is invalid or has expired.",
  MISMATCH: "Confirmation password does not match.",
  SUCCESS: "Password reset successful! Please log in again.",
  FAILED: "Password reset failed.",
  ERROR_TITLE: "Error!",
  TOKEN_MISSING: "Password recovery token does not exist or is invalid.",
  REQUEST_NEW: "Request new code",
  NEW_PASSWORD: "New password",
  NEW_PASSWORD_PLACEHOLDER: "Enter new password",
  CONFIRM_NEW_PASSWORD: "Confirm new password",
  CONFIRM_NEW_PASSWORD_PLACEHOLDER: "Re-enter new password",
  UPDATE_BUTTON: "Update password",
};

export const PROFILE = {
  TITLE: "Personal Information",
  DESCRIPTION: "Update your personal information",
  CHANGE_PASSWORD: "Change password",
  CURRENT_PASSWORD: "Current password",
  NEW_PASSWORD: "New password",
  CONFIRM_PASSWORD: "Confirm password",
  CONFIRM_PASSWORD_MISMATCH: "Confirmation password does not match",
  PROFILE_TAB: "Profile",
  PROFILE_DESC: "Information & Security",
  SETTINGS_TAB: "Settings",
  SETTINGS_DESC: "System customization",
  SECURE_DATA: "Security data",
  LAST_UPDATED: "Last updated",
  SECURITY_DESC:
    "Manage your password and security settings for your account to ensure information safety.",
  ACCOUNT_INFO: "Account information",
  PERSONAL_INFO: "Personal information",
  ADMIN_USER: "Admin User",
};

export const UNAUTHORIZED = {
  TITLE: "Access Denied",
  DESCRIPTION:
    "You do not have permission to access this page. Please check your account or contact the administrator.",
  GO_BACK: "Go back to previous page",
  LOGIN_OTHER: "Login with another account",
};
