export const COMMON = {
  LOADING: "Loading...",
  ERROR: "An error occurred",
  RETRY: "Retry",
  SAVE: "Save",
  CANCEL: "Cancel",
  CONFIRM: "Confirm",
  ACTION: "Action",
  CREATE_AT: "Created at",
  UPDATE_AT: "Updated at",
  NULL: "Null",
  EMPTY: "Empty",
  UPDATE: "Updated",
  UPLOAD: "Upload",
  ALL: "All",
  NOT_APPLICABLE: "N/A",
  FILTER: "Filter",
  SEARCH: "Search",
  NO_RESULTS: "No results",
  REFINE_SEARCH: "Try changing your search keywords",
  EXPORT: "Export",
  NAME_PROJECT: "FoodHub",
  NAME_RESTAURANT: "FoodHub Restaurant",
  RESET: "Reset",
  UPDATE_SUCCESS: "Updated successfully",
  UPDATE_ERROR: "Update failed",
  COPYRIGHT: "FoodHub Management System &copy; 2026",
  SUCCESS: "Success!",
  SAVE_SUCCESS: "Data saved successfully!",
  DELETE_CONFIRM: "Are you sure you want to delete?",
  ERROR_UNKNOWN: "An error occurred, please try again.",
  CURRENCY: "đ",
  OUT_OF_STOCK: "Out of stock",
  PLUS: "+",
  MINUS: "-",
  PAREN_LEFT: "(",
  PAREN_RIGHT: ")",
  HASH: "#",
  BULLET: "•",
  ASTERISK: "*",
  SLASH: "/",
  DASH: "–",
  PIPE: "|",
  COMMA: ",",
  EXCLAMATION: "!",
  QUESTION: "?",
  ELLIPSIS: "...",
  COLON: ":",
  SEMICOLON: ";",
  QUOTE: '"',
  APOSTROPHE: "'",
  BACKTICK: "`",
  AT_SIGN: "@",
  AMPERSAND: "&",
  PERCENT: "%",
  DOLLAR: "$",
  CARET: "^",
  UNDERSCORE: "_",
  PLUS_SIGN: "+",
  MINUS_SIGN: "-",
  EQUAL_SIGN: "=",
  GREATER_THAN: ">",
  LESS_THAN: "<",
  TILDE: "~",
  SPACE: " ",
  NEWLINE: "\n",
  TAB: "\t",
  YES: "Yes",
  NO: "No",
  OK: "OK",
  NEXT: "Next",
  PREVIOUS: "Previous",
  FINISH: "Done",
  BACK: "Back",
  CONTINUE: "Continue",
  SUBMIT: "Submit",
  CLOSE: "Close",
  EDIT: "Edit",
  DELETE: "Delete",
  ADD: "Add",
  SAVE_CHANGES: "Save changes",
  PEOPLE: "people",
  TIME_LABEL: "Time:",
  DOT: ".",
  MORE: "More",
  PROJECTS: "Projects",
  VIEW_PROJECT: "View Project",
  SHARE_PROJECT: "Share Project",
  DELETE_PROJECT: "Delete Project",
  CLOSE_EN: "Close",
  CANCEL_EN: "Cancel",
  SIDEBAR: "Sidebar",
  SIDEBAR_DESC: "Displays the mobile sidebar.",
  TOGGLE_SIDEBAR: "Toggle Sidebar",
  REQUEST_SENT: "Request sent. Please check your email.",
  SEND_FAILED: "Failed to send request.",
  SENDING: "Sending...",
  PROCESSING: "Processing...",
  SOMETHING_WENT_WRONG: "Something went wrong. Please try again later.",
  TOGGLE: "Expand",
  SELECT_DATE_RANGE: "Select date range",
  FROM_DATE: "From date",
  TO_DATE: "To date",
  SELECT_TIME: "Select time",
  CLEAR_FILTER: "Clear filter",
  HYPHEN: " - ",
  LOCALE_VI: "vi-VN",
  VALIDATION_ERROR: "Invalid data. Please check again.",
  LIVE: "LIVE",
  PAGINATION_SHOWING: "Showing",
  TO: "to",
  OF: "of",
  PAGINATION: {
    PAGE: "Page",
    OF: "/",
    TOTAL: "Total",
    PREV: "Prev",
    NEXT: "Next",
    BACK_TO_TOP: "Back to top",
    QUOTE_LEFT: "\u201C",
    QUOTE_RIGHT: "\u201D",
  },
  SYSTEM: "System",
  MINUTES: "m",
  SHARE: "Share",
  DOT_SEP: "·",
  REMAINING: "Remaining",
  DAYS: "days",
  QUANTITY_X: "x",
  CHANGE_AVATAR: "Change avatar",
  TODAY: "Today",
  STATUS: "Status",
  ACTIVE: "Active",
  REFRESH: "Refresh",
  DELETE_TITLE: "Confirm deletion",
  DISPLAY: "Display",
  TWO_HOURS_AGO: "2 hours ago",
  FIVE_HOURS_AGO: "5 hours ago",
  CREATE_NEW: "Create new",
  WEEK: "Week",
};

export const SIDE_BAR = {
  DASHBOARD: "Dashboard",
  OVERVIEW: "Overview",
  MENU: "Menu Management",
  TABLE_MANAGEMENT: "Table Management",
  TABLE: "Table Layout",
  ORDER: "Order Management",
  EMPLOYEE: "Employees",
  AUDIT_LOG: "History",
  INVENTORY: "Inventory",
  RESERVATION: "Reservations",
  STATION: "Station",
  STATION_KITCHEN: "Kitchen Station",
  STATION_BAR: "Bar Station",
  SETTINGS: "Settings",
  LOGOUT: "Logout",
  VOUCHER: "Voucher",
  SHIFT: "Work Shifts",
  SCHEDULE: "Work Schedule",
  ATTENDANCE: "Attendance",
  HR_MANAGEMENT: "HR Management",
};

export const FORM = {
  REQUIRED: "This field is required",
  INVALID_EMAIL: "Invalid email",
  MIN_LENGTH: (min: number) => `Minimum ${min} characters`,
  MIN_VALUE: (min: number) => `Value must be ≥ ${min}`,
  MAX_VALUE: (max: number) => `Value must be ≤ ${max}`,
  INT_ONLY: "Must be an integer",
  EDIT_COMBO: "Edit Combo",
  ADD_COMBO: "Add new Combo",
  EDIT_ITEM: "Edit item",
  ADD_ITEM: "Add new item",
  IMAGE_LABEL: "Image",
  ITEM_NAME: "Item name",
  SKU_CODE: "SKU Code",
  CATEGORY: "Category",
  DESCRIPTION: "Description",
  COMBO_COMPONENTS: "Combo Components",
  SELECT_ITEM_FALLBACK: "Select an item to add...",
  PRICE_CONFIG: "Price configuration",
  PRICE_DINE_IN: "DINE-IN PRICE",
  PRICE_TAKE_AWAY: "TAKEAWAY",
  COST_PRICE: "Cost price",
  PREP_TIME: "Prep time (min)",
  STATION: "Station",
  CANCEL: "CANCEL",
  CONFIRM_SAVE: "Confirm save",
};

export const ROLE = {
  TITLE: "Employee role",
  CURRENT_ROLE: "Current role",
  NEW_ROLE: "New role",
  MANAGER: "Manager",
  CASHIER: "Cashier",
  CHEF: "Chef",
};

export const BUTTON = {
  SUBMIT: "Submit",
  RESET: "Reset",
  CLOSE: "Close",
  EDIT: "Edit",
  DELETE: "Delete",
  ADD: "Add",
  SAVE_CHANGES: "Save changes",
  DETAIL: "Details",
  HISTORY: "History",
  CONFIRM_DELETE: "Confirm delete",
  PREFERENCE: "Preferences",
  FEATURE: "Features",
  BACK: "Back",
  NEXT: "Next",
  UP: "Up",
  DOWN: "Down",
  PAGE: "Page",
  NEXT_PAGE: "Next",
  PREV_PAGE: "Prev",
  TOGGLE_THEME: "Toggle theme",
};

export const API = {
  NETWORK_ERROR: "Cannot connect to server",
  TIMEOUT: "Request timed out",
  UNAUTHORIZED: "You are not logged in",
};

export const NAVIGATION = {
  DASHBOARD: "Overview",
  SALES: "Sales",
  BILLING_HISTORY: "Billing History",
  AUDIT_LOG: "Audit Log",
  MENU: "Menu",
  EMPLOYEE: "Employees",
  PROFILE: "Profile",
  TABLE_MAP: "Table Layout",
  INVENTORY: "Inventory",
  STOCK_HISTORY: "Stock History",
  VOUCHER: "Voucher",
  ORDER_LIST: "Order List",
  ORDER_DETAIL: "Order Detail",
  SETTINGS: "System Settings",
};
