export const DASHBOARD = {
  PORTAL_TITLE: "Operations Portal",
  PORTAL_SUBTITLE: "FoodHub Management System | Operations Center",
  OVERVIEW: "Dashboard Overview",
  USER_ROLE: (role: string) => `You are logged in as: ${role}`,
  STALE_DATA: "Stale data (5m)",
  SYSTEM_HEALTH: "System Health",
  OPERATIONAL_DATA_LOCKED: "Operational data locked",
  LOCKED_DESC:
    "Financial and order history data is restricted by your department. Please use the Kitchen Terminal or POS for direct management.",
  POS_STATUS: "POS Status",
  PRINTER_STATUS: "Kitchen Printer",
  INVENTORY_SYNC: "Inventory Sync",
  ONLINE: "ONLINE",
  READY: "READY",
  STALE: "STALE",
  BULLETIN_TITLE: "Internal Announcements",
  BULLETIN_TAG: "Official announcement",
  RESOURCES_TITLE: "Shared Resources",
  VIEW_ALL: "View all announcements",
  PULSE: "Restaurant Pulse",
  WEATHER_CLOUDY: "28°C / Cloudy",
  MAIN_LOBBY: "Main Lobby",
  STALE_DURATION: (mins: number) => `(${mins} min)`,

  SIGNALR_CONNECTED: "SIGNALR: CONNECTED",
  KPI_LABEL: "(KPI)",
  STATS: {
    REVENUE: "Total Revenue",
    ORDERS: "New Orders",
    TABLES: "Active Tables",
    STAFF: "Staff on Duty",
    REVENUE_TREND: (v: string) => `${v} today`,
    ORDERS_TREND: (v: string) => `${v} today`,
    TABLES_TREND: (v: string) => `${v} occupied`,
    STAFF_TREND: (v: string) => `Change ${v}`,
    REVENUE_DESC: (percent: string) => `${percent} vs last month`,
    ORDERS_DESC: (percent: string) => `${percent} vs yesterday`,
    TABLES_DESC: (percent: string) => `${percent} utilization rate`,
    STAFF_DESC: (count: number) => `${count} staff on duty`,
  },

  TABLE_OCCUPANCY: {
    TITLE: "Table Occupancy",
    FREE: "Available",
    OCCUPIED: "Occupied",
    RESERVED: "Reserved",
  },

  RECENT_ORDERS: {
    TITLE: "Recent Orders",
    ORDER_ID: "Order ID",
    CUSTOMER: "Customer",
    TABLE: "Table",
    AMOUNT: "Amount",
    STATUS: "Status",
    TIME: "Time",
    MINS_AGO: (mins: number) => `${mins} min ago`,
    HOUR_AGO: (hours: number) => `${hours} hr ago`,
    STATUS_COMPLETED: "Completed",
    STATUS_PREPARING: "Preparing",
    STATUS_PENDING: "Pending",
    STATUS_CANCELLED: "Cancelled",
  },

  REVENUE_CHART: {
    TITLE: "Weekly Performance",
    AVG_DAILY: "Daily Average",
    PEAK_DAY: "Peak Day",
    DAYS: {
      MON: "Mon",
      TUE: "Tue",
      WED: "Wed",
      THU: "Thu",
      FRI: "Fri",
      SAT: "Sat",
      SUN: "Sun",
    },
  },

  RESOURCES: {
    TITLE: "Shared Resources",
    RECIPES: "Standard Recipes",
    SCHEDULE: "Shift Schedule",
    TRAINING: "Training Portal",
    HACCP: "HACCP Log",
    SUPPORT: "Kitchen IT Support",
    PUNCH_CLOCK: "Time Clock",
  },

  TOP_DISHES: {
    TITLE: "Best Selling Dishes",
    ORDERS_COUNT: (count: number) => `${count} orders this week`,
  },

  ALERT_STRIP: {
    PRINTER_ERROR: (station: string) => `Kitchen printer error: ${station} disconnected`,
    DELAYED_ORDER: (id: string, mins: number) =>
      `Order #${id} delayed > ${mins} min, food not served`,
  },

  OPERATIONS: {
    TITLE: "Operations Center",
    KDS_BACKLOG: "KDS Backlog (Kitchen)",
    INVENTORY_ALERTS: "Inventory Alerts",
    PROCESSING_ITEMS: (count: number) => `${count} items in progress`,
    WAITING: "Waiting",
    PREPARING: "Preparing",
    PREPARING_PROGRESS: "PREPARATION PROGRESS",
    ITEMS_COUNT: (count: number) => `${count} items`,
    DELAYED_WARNING: (count: number, mins: number) => `WARNING: ${count} ITEMS DELAYED > ${mins}M`,
    INGREDIENT_STATUS: "INGREDIENT STATUS",
    OUT_OF_STOCK: "Out of stock",
    LOW_STOCK: "Low stock",
    STABLE_INVENTORY: "Inventory stable",
    VIEW_DETAILS: "VIEW INVENTORY DETAILS",
  },

  ANALYTICS: {
    TITLE: "Advanced Analytics",
    KPI_TITLE: "Key Metrics",
    VS_YESTERDAY: "vs yesterday",
    REVENUE_CHANNEL: "Sales Channel Distribution",
    UPDATED_JUST_NOW: "UPDATED: JUST NOW",
    VIEW_REPORT: "VIEW DETAILED REPORT",
    ADD_WIDGET: "Add new report",
    ADD_WIDGET_DESC: "Drag and drop charts or metrics you want to track here",
    LIVE_MONITORING: "Live Monitoring",
    DINE_IN: "Dine-in",
    DELIVERY: "Delivery",
    BEST_SELLERS_ANALYSIS: "Best-sellers Analysis",
    QUICK_INSIGHTS: "View deep analysis",
  },
};
