export const EMPLOYEE = {
  TITLE: "Employee List",
  DESCRIPTION: "Manage employee information",
  INFO: "Employee Information",
  EMPTY: "No employees yet",
  ADD: "Add Employee",
  ADD_DESCRIPTION: "Add a new employee to the system",
  ADD_SUSCESS: "Employee added successfully",
  ADD_FAILED: "Failed to add employee",
  EDIT: "Edit Employee",
  DELETE: "Delete Employee",
  DELETE_CONFIRM: "Are you sure you want to delete this employee?",
  DELETE_SUSCESS: "Employee deleted successfully",
  DELETE_FAILED: "Failed to delete employee",
  UPDATE_SUSCESS: "Employee updated successfully",
  UPDATE_FAILED: "Failed to update employee",
  FETCH_ERROR: "Could not load employee list",
  EMPLOYEECODE: "Employee Code",
  FULLNAME: "Full Name",
  FULLNAME_PLACEHOLDER: "Enter full name",
  EMAIL: "Email",
  ROLE: "Role",
  PHONE: "Phone Number",
  ADDRESS: "Address",
  DOB: "Date of Birth",
  STATUS: "Status",
  ACTIVE: "Active",
  INACTIVE: "Inactive",
  CHANGE_PASSWORD: "Change Password",
  CHANGE_ROLE: "Change Role",
  CHANGE_PASSWORD_DESC:
    "Changing the password will automatically send an email notification to the employee.",
  CHANGE_PASSWORD_REASON: "Reason for password change",
  DETAIL: "Employee Details",
  EMP_ID: "Emp ID",
  EMPLOYEE_TITLE: "Employee",
  CONTACT: "Contact",
  NOT_FOUND: "No employees found",
  RETRY: "Retry",
  CHANGE_ROLE_TITLE: "Change Role",
  CHANGE_ROLE_DESC_FULL:
    "Changing the employee's role will grant them a new account and the old account will be deactivated.",
  REASON: "Reason for change",
  INFO_TITLE: "💡 Information:",
  INFO_1: "The old account will be deactivated.",
  INFO_2: "The system will automatically create a new employee code.",
  INFO_3: "New login credentials have been sent to ",
  CONFIRM_CHANGE_ROLE: "Confirm role change",
  AGREE_TERMS: "By checking this box, the old account will be deactivated.",
  AUTO_GEN: "Auto-generated password:",
  DELETE_CONFIRM_NAME: (name: string) => `Are you sure you want to delete "${name}"?`,
  UPDATE_PROFILE: "Update Profile",
  UPDATE_INFO: "Update basic information",
  CHANGE_ROLE_DESC: "Change employee role",
  DELETE_EMPLOYEE: "Delete Employee",
  CONFIRM_DELETE: "Confirm Deletion",
  CONFIRM_DELETE_DESC: "Are you sure you want to proceed with deletion?",
  ACCOUNT_SECURITY: "Account Security",
  SECURITY_DESC: "Change password",
  REMOVE_FROM_SYSTEM: "Remove from system",
  REMOVE_DESC: "Permanently delete",
  CONFIRM_REQUIRED: "Please confirm the role change",
  REASON_REQUIRED: "Please enter a reason for the role change",
  ROLE_MISMATCH: "New role must differ from the current role",
  INVALID_CODE: "Employee code is invalid or does not exist",
  CHANGE_SUCCESS: "Role changed successfully",
  CHANGE_FAILED: "Role change failed",
  REASON_PLACEHOLDER: "Enter reason for promotion, department transfer...",
  SEARCH_BAR_PLACEHOLDER: "Search by name, email, or ID...",
};
