export const INVENTORY = {
  NAV: {
    OVERVIEW: "Overview",
    INGREDIENTS: "Inventory",
    STOCK_IO: "Stock In / Out",
    OPENING_STOCK: "Opening Stock",
    CHECK: "Stock Check",
    REPORT: "Inventory Report",
    LEDGER: "Ledger",
    GROUPS: "Material Groups",
    TRANSACTIONS: "History",
    LOTS: "Stock Lots",
    COGS: "COGS Calculation",
    ALERTS: "Alerts",
    SETTINGS: "Settings",
  },
  TITLE: "Ingredient Inventory",
  WIP_DESC: "Manage and track your kitchen ingredients.",
  TOTAL_ITEMS: "Total ingredients",
  LOW_STOCK: "Low stock",
  INVENTORY_VALUE: "Inventory value",
  ALERT_TAB_LOW_STOCK: "Low stock",
  ALERT_TAB_EXPIRING: "Expiring soon",
  ALERTS_TITLE: "Inventory Alerts",
  ALERTS_DESC: "Manage critical stock levels and upcoming expiry dates.",
  ALERTS_BTN: "Alerts",
  OPENING_STOCK_REMINDER_TITLE: "Opening stock not imported yet",
  OPENING_STOCK_REMINDER_DESC:
    "Please import opening stock before managing inventory to ensure accurate stock data.",
  OPENING_STOCK_REMINDER_ACTION: "Go to opening stock",
  OVERVIEW: {
    REFRESH: "Refresh",
    PAGE_TITLE: "Ingredient Inventory",
    INGREDIENT_LIST_TITLE: "Ingredients List",
    INGREDIENT_LIST_DESC: "Manage and track all ingredient inventory",
    QUICK_ACTIONS_TITLE: "Quick Actions",
    SETTINGS_SECTION: "Inventory Configuration",
    SETTINGS_LINK: "Inventory Settings",
    SETTINGS_LINK_DESC: "Thresholds, FIFO, depreciation...",
    ALERTS_VIEW_ALL: "View all",
    TOTAL_ALERTS: "Inventory alerts",
    STOCK_HEALTHY: "Inventory stable",
    ALERTS_STATUS_OK: "All ingredients are at safe levels",
    OUT_OF_STOCK_SUFFIX: "out of stock",
    LOW_STOCK_SUFFIX: "low stock",
    EXPIRED_SUFFIX: "expired",
    NEAR_EXPIRY_SUFFIX: "expiring soon",
    QUICK_IMPORT: "Stock In",
    QUICK_IMPORT_DESC: "Create import receipt",
    QUICK_EXPORT: "Stock Out",
    QUICK_EXPORT_DESC: "Create export receipt",
    QUICK_CHECK: "Stock Check",
    QUICK_CHECK_DESC: "Create inventory check",
    QUICK_REPORT: "Report",
    QUICK_REPORT_DESC: "View inventory report",
    QUICK_LEDGER: "Ledger",
    QUICK_LEDGER_DESC: "View ledger details",
    QUICK_LOTS: "Lots",
    QUICK_LOTS_DESC: "Manage stock lots",
    QUICK_GROUPS: "Material Groups",
    QUICK_GROUPS_DESC: "Set up rules by material group",
    QUICK_SETTINGS: "Settings",
    QUICK_SETTINGS_DESC: "Configure inventory",
    VIEW_DETAIL_ARROW: "→",
    SEP_DOT: "·",
    NVL_UNIT: "Items",
    PRIORITY_ITEMS_TITLE: "Priority Items",
    PRIORITY_ITEMS_DESC:
      "Quick summary of ingredient groups needing early checks to prevent stockouts and data discrepancies.",
    VIEW_INGREDIENT_LIST: "View ingredients list",
    PRIORITY_LIST: "Priority list",
    HIGHLIGHT_SUFFIX: "highlighted items",
    EMPTY_GROUP: "No items need attention in this group.",
    LOW_STOCK_TITLE: "Low stock ingredients",
    OPEN_ALERTS: "Open inventory alerts",
    EXPIRING_LOTS_TITLE: "Expiring lots",
    VIEW_EXPIRING_LOTS: "View expiring lots",
    MISSING_COST_TITLE: "Ingredients without cost price",
    UPDATE_INGREDIENT: "Update ingredient",
    MISSING_THRESHOLD_TITLE: "Ingredients without alert threshold",
    OPEN_SETTINGS: "Open inventory settings",
    MISSING_COST_META: "missing cost price",
    MISSING_THRESHOLD_META: "missing threshold",
  },
  HISTORY_TITLE: "Stock In/Out History",
  HISTORY_DESC: "Track and manage stock in/out transactions",
  STOCK_IN_TITLE: "Stock In/Out Management",
  CREATE_VOUCHER_BTN: "Create receipt",
  STOCK_IN_VOUCHER: "Import Receipt",
  STOCK_OUT_VOUCHER: "Export Receipt",
  BACK_TO_INVENTORY: "Back to inventory",
  NEW_BATCHES_MONTH: "Total lots this month",
  NEW_STOCK_VALUE: "New import value",
  FLAGGED_ITEMS: "Flagged",
  ADD_TITLE: "Add New Ingredient",
  ADD_DESC:
    "Add a new ingredient to inventory. The system will alert when stock falls below this level.",
  EDIT_TITLE: "Update Ingredient",
  EDIT_DESC: "Edit existing ingredient information in the system.",
  CREATED_BY: "Exported by",
  DELETE: {
    TITLE: "Deactivate Ingredient",
    DESC: "Are you sure you want to deactivate this ingredient? This action can be reversed.",
    REACTIVATE_TITLE: "Reactivate Ingredient",
    REACTIVATE_DESC: "Do you want to reactivate this ingredient for continued use?",
    SUCCESS: "Ingredient deactivated successfully",
    SUCCESS_DEACTIVATE: "Ingredient deactivated",
    SUCCESS_REACTIVATE: "Ingredient reactivated",
    ERROR: "Error deactivating ingredient",
    BTN_CANCEL: "Cancel",
    BTN_CONFIRM: "Deactivate",
    BTN_CONFIRM_REACTIVATE: "Reactivate",
    BTN_DELETING: "Processing...",
  },
  PRO_TIP:
    "Ensure the unit matches the most frequently used measure to help kitchen staff easily convert.",
  FORM: {
    NAME: "Ingredient name",
    SKU: "Material code",
    UNIT: "Unit",
    SELECT_UNIT: "Select unit",
    ALERT_THRESHOLD: "Low stock alert threshold",
    COST: "Average price",
    INITIAL_STOCK: "Initial quantity",
    AUTO_GEN: "(auto)",
    CURRENT_STOCK: "Current stock",
    STOCK_HELP_TEXT: "Quantity only changes via stock in/out.",
    COST_HELP_TEXT: "Cost is calculated from import receipts.",
    SUPPLIER: "Primary supplier",
    DESCRIPTION: "Description / Notes",
    IS_ACTIVE: "Active status",
    PLACEHOLDER_NAME: "e.g. Tomato, Beef...",
    PLACEHOLDER_SKU: "MAT-...",
    PLACEHOLDER_CATEGORY: "Vegetables, Meat...",
    PLACEHOLDER_DESCRIPTION: "Enter ingredient description...",
    BATCH_CODE_LABEL: "Batch code (optional)",
    BATCH_CODE_PLACEHOLDER: "Enter batch code if available",
    GROUP: "Ingredient group",
    GROUP_NONE: "No group",
    GROUP_DESC: "Assign ingredient to a group to inherit group rules.",
    ERROR_ADD: "Error adding ingredient",
    ERROR_CONN: "Connection error occurred",
    SUCCESS_ADD: "Ingredient added successfully",
    SUCCESS_EDIT: "Ingredient updated successfully",
    BTN_SAVING: "Saving...",
    BTN_SAVE: "Save ingredient",
    USE_DEFAULT_THRESHOLD: "Use default threshold",
    USE_DEFAULT_THRESHOLD_DESC:
      "Enable to use the global alert threshold, disable to set a custom one for this ingredient.",
    CURRENT_DEFAULT_THRESHOLD: "Current default threshold is",
    USING_DEFAULT_THRESHOLD: " This ingredient is using the default threshold.",
    CUSTOM_THRESHOLD_HELP: " You can set a custom threshold for this ingredient.",
  },
  TOOLBAR: {
    SEARCH_PLACEHOLDER: "Search code or name...",
    FILTER_STATUS: "Stock status",
    STATUS_ALL: "All statuses",
  },
  STOCK: {
    CURRENT: "Current stock",
    STATUS_NORMAL: "Normal",
    STATUS_LOW: "Low",
    STATUS_OUT: "Out of stock",
  },
  TABLE: {
    EMPTY_TITLE: "No ingredients yet",
    EMPTY_DESC: "Start by adding a new ingredient to inventory.",
    EMPTY_ALERT: "No ingredients are running low.",
    EMPTY_EXPIRING: "No ingredients expiring soon.",
    EMPTY_HISTORY: "No import history yet",
    NO_REF: "No reference",
    COL_NAME: "Ingredient name",
    COL_GROUP: "Group",
    COL_SKU: "Material code",
    COL_CATEGORY: "Category",
    COL_STOCK: "Stock",
    COL_PRICE: "Unit price",
    COL_STATUS: "Condition",
    COL_ACTIVE: "Status",
    COL_ACTIONS: "Actions",
    GROUP_NONE: "No group assigned",
    COL_ITEM: "Ingredient",
    COL_CURRENT_STOCK: "Current stock",
    COL_THRESHOLD: "Alert threshold",
    COL_BATCH: "Batch",
    COL_EXPIRATION: "Expiry date",
    COL_REMAINING: "Remaining stock",
    COL_DATE: "Import date",
    COL_SUPPLIER: "Supplier",
    COL_QTY: "Quantity",
    COL_TOTAL_COST: "Total cost",
    COL_RECEIVER: "Created by",
    COL_STOCK_OUT_BY: "Exported by",
    COL_TYPE: "Transaction type",
    COL_BALANCE: "Post-transaction balance",
    COL_REFERENCE: "Reference",
    TRANS_TYPE_OPENING: "Opening balance",
    TRANS_TYPE_IN: "Stock in",
    TRANS_TYPE_IN_REVERSE: "Import reversal",
    TRANS_TYPE_OTHER: "Other",
    HISTORY_DESC_FULL: "Track all quantity and cost changes for this ingredient.",
    COL_SORT: "Sort",
    SORT_NEWEST: "Newest",
    SORT_OLDEST: "Oldest",
    TRANS_HISTORY: "Stock history",
    THRESHOLD_PREFIX: "Threshold:",
    ERROR_PREFIX: "Error:",
    EXPIRING_BADGE: "Expiring",
    OUT_OF_STOCK_BADGE: "Out of stock",
    LOW_STOCK_BADGE: "Low stock",
    ACTIVE_BADGE: "Active",
    INACTIVE_BADGE: "Inactive",
    CURRENCY: "$",
    PAGE: "Page",
    PAGE_SIZE: "Rows:",
    COL_UNIT_SHORT: "Unit",
    SLASH: "/",
    HYPHEN: "-",
    PLUS_SIGN: "+",
    MINUS_SIGN: "-",
    EM_DASH: "—",
    PAREN_OPEN: "(",
    PAREN_CLOSE: ")",
  },
  SETTINGS: {
    TITLE: "Inventory Configuration",
    DESC: "Manage warehouse operation parameters and calculation methods.",
    GENERAL_INFO: "General Information",
    EXPIRY_WARNING: "Expiry warning days",
    EXPIRY_WARNING_DESC: "System will send notification before product expiration.",
    LOW_STOCK_THRESHOLD: "Default low stock threshold",
    LOW_STOCK_THRESHOLD_DESC: "Alert when stock is lower than this quantity (for new materials).",
    AUTO_DEDUCT: "Auto-deduct stock on sale",
    AUTO_DEDUCT_DESC: "Automatically deduct raw material stock when an order is completed.",
    COST_METHOD: "Cost calculation method",
    COST_METHOD_DESC: "Default method the system uses to calculate inventory value.",
    MAX_RECALC_DAYS: "Maximum COGS recalculation days",
    MAX_RECALC_DAYS_DESC: "Maximum time range for periodic COGS recalculation.",
    OPENING_STOCK_IMPORT_COOLDOWN: "Opening stock import interval",
    OPENING_STOCK_IMPORT_COOLDOWN_DESC:
      "Set minimum hours to wait before the system allows the next opening stock import.",
    OPENING_STOCK_IMPORT_COOLDOWN_HELP:
      "Unit is hours. Enter 0 for no wait. Example: 24 = 1 day, 48 = 2 days.",
    OPENING_STOCK_STATUS_TITLE: "Opening stock import status",
    LAST_IMPORT_TIME: "Last import",
    NEXT_IMPORT_ALLOWED: "Next import allowed from",
    NO_IMPORT_YET: "No imports yet",
    IMPORT_COOLDOWN_VALUE: "Current cooldown",
    IMPORT_COOLDOWN_NOTE: "Calculated in hours with no hard maximum limit.",
    IMPORT_COOLDOWN_NONE: "No wait required, can import immediately",
    HOURS_SUFFIX: "hours",
    SUCCESS_UPDATE: "Inventory settings updated successfully",
    ERROR_FETCH: "Could not load inventory settings",
    COST_METHOD_W_AVG: "Weighted average",
    DEFAULT: "Default",
    COST_METHOD_SUPPORT: "Currently the system only supports.",
  },
  GROUPS: {
    TITLE: "Material Group Management",
    DESC: "Create material groups to assign common rules to items with similar characteristics.",
    CREATE_TITLE: "Add Material Group",
    EDIT_TITLE: "Edit Material Group",
    FORM_DESC: "Groups can carry stock thresholds, expiry thresholds, and default cost methods.",
    NAME: "Group name",
    NAME_PLACEHOLDER: "e.g. Vegetables, Meat, Seafood...",
    DESCRIPTION: "Description",
    DESCRIPTION_PLACEHOLDER: "Enter group notes...",
    LOW_STOCK_THRESHOLD: "Stock threshold",
    EXPIRY_WARNING_DAYS: "Expiry days",
    DEFAULT_COST_METHOD: "Default cost method",
    INHERIT_COST_METHOD: "Inherit from inventory settings",
    DEFAULT_COST_METHOD_DESC: "If empty, the group will use the inventory default cost method.",
    CREATE_BTN: "Create group",
    UPDATE_BTN: "Save changes",
    CANCEL_EDIT: "Cancel edit",
    LIST_TITLE: "Group List",
    LIST_DESC: "Quick view of rules and material counts assigned to each group.",
    EMPTY_TITLE: "No material groups yet.",
    RULES: "Rules",
    INGREDIENTS: "Materials",
    ACTIONS: "Actions",
    OPTIONAL: "Optional",
    SUCCESS_CREATE: "Material group created successfully",
    SUCCESS_UPDATE: "Material group updated successfully",
    SUCCESS_DELETE: "Material group deleted successfully",
    DELETE_TITLE: "Delete material group",
    DELETE_DESC: "Are you sure you want to delete this group?",
    DELETE_BTN: "Delete group",
    DELETING: "Deleting...",
  },
  OPENING_STOCK: {
    TITLE: "Opening Stock Import",
    DESC: "Set up initial quantities and prices for all raw materials when starting to use the system.",
    SEARCH_PLACEHOLDER: "Search material code or name...",
    TOTAL_VALUE: "Total value",
    BTN_SAVE: "Save balance",
    COL_CODE: "Material code",
    COL_NAME: "Material name",
    COL_UNIT: "Unit",
    COL_CURRENT: "Current stock",
    COL_QTY: "Quantity",
    COL_INITIAL: "Initial quantity",
    COL_COST: "Import price",
    COL_TOTAL: "Amount",
    ERROR_FETCH: "Could not load material list",
    SUCCESS_IMPORT: "Opening stock imported successfully",
    EMPTY_SEARCH: "No materials found",
    VALIDATION_REQUIRED: "Please enter quantity for at least one material",
    LOCKED_TITLE: "Opening stock locked",
    LOCKED_DESC: "Opening stock data has been finalized and cannot be edited.",
    LOCKED_TIME: "Lock time:",
    LAST_IMPORT_TIME: "Last import:",
    NEXT_IMPORT_ALLOWED: "Next import allowed from:",
    IMPORT_COOLDOWN: "Cooldown:",
    IMPORT_QTY: "Import quantity",
    PREVIEW_TITLE: "Opening stock import preview",
    PREVIEW_DESC:
      "Quick review of data before confirming import. Existing stock for materials will be overwritten.",
    PREVIEW_TOTAL_ITEMS: "Items to import",
    PREVIEW_TOTAL_QUANTITY: "Total quantity",
    PREVIEW_TOTAL_VALUE: "Total import value",
    PREVIEW_OVERWRITE_ITEMS: "Items to overwrite",
    PREVIEW_EXISTING_STOCK_ITEMS: "Items with existing stock",
    PREVIEW_LIST_TITLE: "Materials with current stock",
    PREVIEW_EMPTY: "No materials to import.",
    PREVIEW_NO_OVERWRITE: "No materials will be overwritten. You can confirm the import.",
    PREVIEW_CONFIRM: "Confirm import",
    REMINDER_TITLE: "Opening stock not imported yet",
    REMINDER_DESC:
      "Please import opening stock before managing inventory to ensure accurate stock data.",
    REMINDER_BTN: "Go to opening stock",
    IMPORT_EXCEL: "Import Excel",
    IMPORT_EXCEL_DESC: "Upload an Excel file (.xlsx, .xls) to quickly import opening stock.",
    IMPORT_EXCEL_BTN: "Upload Excel file",
    IMPORT_EXCEL_TITLE: "Import stock from Excel",
    DOWNLOAD_TEMPLATE: "Download template",
    DOWNLOAD_TEMPLATE_DESC: "Use this template to ensure data is imported in the correct format.",
    IMPORT_PREVIEW_TITLE: "Excel data preview",
    IMPORT_ERROR_INVALID_FILE: "Invalid file or incorrect format.",
    IMPORT_SUCCESS: "Excel data imported successfully.",
    BTN_DOWNLOAD_TEMPLATE: "Download template",
    DRAG_DROP_MSG: "Drag & drop or click to select file",
    SUPPORTED_FORMATS: "Supports .xlsx, .xls format (Max 5MB)",
    BTN_CANCEL: "Cancel",
    BTN_IMPORT: "Import data",
    PROCESSING: "Processing...",
    KB: "KB",
  },
  STOCK_OUT: {
    DATE: "Export date",
    REASON_LABEL: "Reason",
    REASON_FIELD: "Export reason",
    REASON_PLACEHOLDER: "Enter reason",
    REASON_PRESETS: ["Dispose materials", "Internal export", "Inventory check", "Other"],
    NOTE_LABEL: "Additional notes (optional)",
    NOTE_PLACEHOLDER: "Enter notes if needed",
    QTY_LABEL: "Export quantity",
    PRICE_LABEL: "Export price",
    PRICE_OPTIONAL: "(optional)",
    TOTAL_PRICE_LABEL: "Amount",
    CURRENT_STOCK_LABEL: "Current stock:",
    EXCEED_STOCK_WARNING: "Quantity exceeds available stock",
    VALIDATION_MIN_ITEMS: "Please add at least 1 material line with quantity > 0",
    VALIDATION_REASON_REQ: "Please select an export reason",
    SUCCESS_CREATE_PREFIX: "Export receipt created",
    STOCK_EXCEEDED_PREFIX: "Export quantity exceeds current stock of",
    STOCK_EXCEEDED_TOKEN: "(stock",
    ITEM_COUNT_LABEL: "Material lines",
  },
  VOUCHER: {
    TYPE_IN: "Import receipt",
    TYPE_OUT: "Export receipt",
  },
  CHECK: {
    TITLE: "Stock Check",
    DESC: "Compare actual warehouse quantities with book records.",
    CREATE_BTN: "Create check sheet",
    COL_CODE: "Sheet code",
    COL_DATE: "Check date",
    COL_CREATOR: "Created by",
    COL_STATUS: "Status",
    COL_ITEMS: "Item count",
    FILTER_STATUS: "Status:",
    STATUS_ALL: "All",
    DATE_RANGE: "Date range:",
    STATUS_DRAFT: "Draft",
    STATUS_PROCESSED: "Processed",
    EMPTY_TITLE: "No stock checks yet",
    EMPTY_DESC: "Start a stock check to ensure accurate inventory data.",
    FETCH: {
      ERROR: "Could not load stock check list",
      NOT_FOUND: "Stock check not found",
      NOT_FOUND_DESC:
        "The stock check you are looking for may have been deleted, doesn't exist, or you entered an incorrect URL.",
    },
    CREATE: {
      TITLE: "Stock Check Sheet",
      DESC: "Enter actual quantities counted in the warehouse.",
      COL_BOOK_QTY: "Book quantity",
      COL_PHYSICAL_QTY: "Physical quantity",
      COL_DIFF_QTY: "Difference",
      COL_DIFF_SHORT: "Diff",
      COL_REASON: "Reason",
      COL_REASON_NOTE: "Note / Reason",
      SAVE_DRAFT: "Save draft",
      PROCESS: "Process check",
      BTN_EXPORT: "Export sheet",
      SUCCESS_SAVE: "Stock check saved",
      SUCCESS_PROCESS: "Stock check processed successfully",
      SUCCESS_CREATE: "Stock check created successfully.",
    },
  },
  REPORT: {
    TITLE: "Inventory Report",
    DESC: "Analyze stock movements and inventory value over time.",
    COL_OPENING: "Opening stock",
    COL_IN: "Total in",
    COL_OUT: "Total out",
    COL_SALE: "Sales",
    COL_CLOSING: "Closing stock",
    COL_AVG_COST: "Average unit price",
    COL_VALUE: "Stock value",
    LEDGER_TITLE: "Material Detail Ledger",
    LEDGER_DESC: "Detailed balance movements for the ingredient",
    LEDGER_LOADING: "Loading stock history...",
    LEDGER_COL_TIME: "Timestamp",
    LEDGER_COL_DELTA: "Movement",
    LEDGER_COL_NOTE: "Note",
    TOTAL_VALUE_LABEL: "Total stock value",
    DATE_RANGE: "Report period:",
    FILTER_CATEGORY: "Category:",
    CATEGORY_ALL: "All materials",
    SELECT_MATERIAL: "Select ingredient",
    VALUE_SEPARATOR: "—",
  },
  COGS: {
    TITLE: "COGS Calculation",
    DESC: "Method: Weighted Average",
    FORM_TITLE: "Select calculation period",
    FROM_DATE: "From date",
    TO_DATE: "To date",
    ALL_INGREDIENTS: "All raw materials",
    BTN_CALCULATE: "Calculate",
    BTN_CALCULATING: "Calculating...",
    NOTE: "Maximum calculation period is 31 days. The system will recalculate average unit prices and update amounts on all export receipts in the period.",
    INFO_MAX_DAYS: "Maximum calculation period is 31 days",
    FORMULA_TITLE: "Weighted Average Formula",
    FORMULA: "Avg Price = (Opening Value + Import Value) ÷ (Opening Qty + Import Qty)",
    RULE_1: "Recalculate after each new import receipt",
    RULE_2: "Export at average price at the time of export",
    RULE_3: "No imports → unit price = 0",
    RULE_4: "Export value = Export qty × Average price",
    RESULTS_TITLE: "COGS Results — Period",
    BADGE_CALCULATED: "Calculated",
    SUCCESS_TITLE: "Calculation successful",
    SUCCESS_MSG: "COGS calculation completed",
    SUCCESS_DESC_PREFIX: "COGS updated for period from",
    SUCCESS_DESC_TO: "to",
    LABEL_RECEIPTS: "Transactions processed",
    LABEL_ITEMS: "Lots updated",
    LABEL_ADJUSTMENT: "Total adjustment value",
    BTN_RECALCULATE: "Calculate another period",
    CONFIRM_TITLE: "Confirm COGS recalculation",
    CONFIRM_DESC_PREFIX: "Are you sure you want to recalculate COGS from",
    CONFIRM_DESC_TO: "to",
    CONFIRM_DESC_SUFFIX: "? This process will reconcile all in/out transactions in the period.",
    BTN_RUNNING: "Running...",
    BTN_RUN_NOW: "Calculate now",
    COL_NO: "No.",
    COL_OPENING_QTY: "Opening qty",
    COL_OPENING_VAL: "Opening value",
    COL_IN_QTY: "Import qty",
    COL_IN_VAL: "Import value",
    COL_AVG_PRICE: "Avg price",
    COL_OUT_COUNT: "Export receipts",
    COL_TOTAL_VAL: "Amount",
    TXT_VND_PER_KG: "đ/kg",
    FOOTER_TOTAL: "Total amount:",
  },
  ALERTS: {
    TAB_LOW_STOCK: "Low / Out of Stock",
    TAB_EXPIRING: "Expiring / Expired",
    REFRESH: "Refresh",
    EMPTY_TITLE: "No new alerts",
    EMPTY_DESC: "Inventory is in good condition",
    FILTER_PLACEHOLDER: "Search materials...",
    SORT_LOW_STOCK: "Sort: Out of stock first",
    SORT_EXPIRING: "Sort: Earliest expiry first",
    BADGE_OUT_OF_STOCK: "Out of stock",
    BADGE_LOW_STOCK: "Low stock",
    BADGE_EXPIRED: "Expired",
    BADGE_URGENT: "Urgent",
    BADGE_EXPIRING: "Expiring soon",
    ACTION_ORDER_NOW: "Order now",
    ACTION_ORDER: "Order",
    FILTER_LOT_PLACEHOLDER: "Search ingredient or lot code...",
    FILTER_7_DAYS: "In next 7 days",
    COL_LOT: "Lot code",
    COL_DAYS_REMAINING: "Days remaining",
    COL_NOTE: "Note",
    MSG_EXPIRED: "Expired",
    MSG_REMAINING: "Remaining",
    MSG_NOTE_URGENT: "Check and handle immediately",
    MSG_NOTE_TODAY: "Prioritize use today",
    MSG_NOTE_PLAN: "Plan for usage",
    MSG_NOTE_ALLOCATE: "Monitor allocation",
    MSG_NOTE_CHECK: "Check and dispose",
    TXT_DAYS: "days",
  },
  LOTS: {
    TITLE: "Stock Lot Management",
    DESC: "View and manage detailed stock lots by expiry date",
    SUCCESS_CREATE_RECEIPT: "Import receipt created",
    SEARCH_PLACEHOLDER: "Search by lot code or ingredient...",
    COL_CODE: "Lot Code",
    COL_INGREDIENT: "Ingredient",
    COL_STOCK: "Stock quantity",
    COL_UNIT: "Unit",
    COL_EXPIRY: "Expiry date",
    COL_STATUS: "Status",
    COL_ACTIONS: "Actions",
    STATUS_VALID: "Valid",
    STATUS_NEAR_EXPIRY: "Expiring soon",
    STATUS_EXPIRED: "Expired",
    STATUS_DEPLETED: "Depleted",
    STATUS_DISPOSED: "Disposed",
    DISPOSE: {
      TITLE_SHORT: "Dispose lot",
      TITLE: "Confirm lot disposal",
      DESC: "You are about to dispose this material lot. This action cannot be undone and will update COGS.",
      LABEL_NAME: "Ingredient name:",
      LABEL_CODE: "Lot code:",
      LABEL_AVAILABLE: "Available stock:",
      LABEL_QTY: "Dispose quantity",
      LABEL_REASON: "Disposal reason",
      PLACEHOLDER_REASON: "e.g. Expired, Damaged during storage...",
      BTN_CANCEL: "Cancel",
      BTN_CONFIRM: "Confirm disposal",
      BTN_DISPOSING: "Processing...",
      SUCCESS: "Lot disposed successfully",
      ERROR: "Could not dispose lot",
      VALIDATION_QTY: "Please enter a valid quantity",
      INFO_TITLE: "Lot Information",
      INFO_DESC: "Please review lot information carefully before disposing.",
      BTN_USE_MAX: "Use maximum",
      HELP_QTY: "Enter the quantity you want to dispose.",
      PRESET_REASONS: ["Expired", "Damaged", "Poor quality", "Other"],
      HELP_REASON: "Select or enter a disposal reason for records.",
      LIMIT_SUFFIX: "maximum",
      VALIDATION: {
        REASON_REQUIRED: "Please enter a disposal reason",
        REASON_MAX: "Reason cannot exceed 255 characters",
        QTY_REQUIRED: "Please enter disposal quantity",
        QTY_POSITIVE: "Disposal quantity must be greater than 0",
        QTY_EXCEEDED: "Disposal quantity exceeds available stock",
      },
    },
  },
};
