export const LANDING = {
  TITLE: "Management Platform",
  SUBTITLE: "for Modern Restaurants",
  GET_STARTED: "Get started free",
  FOOTER_BRAND: "FoodHub",
  FOOTER_DESC:
    "A 4.0 restaurant management platform, optimizing operations seamlessly from kitchen to table.",
  PRODUCT: "Product",
  FEATURES: "Features",
  PRICING: "Pricing",
  INTEGRATIONS: "Integrations",
  COMPANY: "Company",
  ABOUT: "About",
  CAREERS: "Careers",
  BLOG: "Blog",
  SUPPORT: "Support",
  HELP_CENTER: "Help Center",
  STATUS: "Status",
  COPYRIGHT: "© 2026 FoodHub Kitchen Management. All rights reserved.",
  PRIVACY: "Privacy Policy",
  TERMS: "Terms of Service",
  KDS_V2: "KDS v2.0 - Live Connection",
  NAV_BRAND: "FoodHub",
  LEARN_MORE: "Learn more",
  PARTNERS: "Partner Restaurants",
  NEWS: "News & Resources",
  INSIGHT: "Insight",
  HERO_TITLE: "Optimize Your",
  HERO_SUBTITLE: "Culinary Operations",
  HERO_DESC:
    "From table ordering to the heat of the kitchen. FoodHub provides a digital platform for modern restaurant operations and intelligent kitchen management.",
  ENTER_SYSTEM: "Enter system",
  DASHBOARD: "Overview",
  STAFF_LOGIN: "Staff login",
  KITCHEN_TERMINAL: "Kitchen Terminal",
  MISSION_CRITICAL: "Core solutions for BOH",
  MISSION_DESC: "Software designed specifically for the pace and pressure of the back-of-house.",
  KITCHEN_INTEL: "Kitchen Intelligence",
  KDS_PREVIEW: "KDS Terminal 01 Interface",
  TECH_REDUCING: "Average 24% reduction in food serving time",
  RESERVATION_BTN: "Reserve now",
  ABOUT_TITLE: "About FoodHub",
  ABOUT_DESC:
    "FoodHub is a trusted partner of over 500 restaurants, providing a comprehensive management ecosystem to elevate the dining experience.",
  ESTABLISHED: "Established since 2018",
  TEAM_SIZE: "Over 100 technical and culinary experts",
  YEAR_VAL: "2023",
  AWARDS_VAL: "50+",
  CUSTOMERS_VAL: "500+",
  ABOUT_IMG_ALT: "Restaurant Business",
  RESERVATION_TITLE: "FoodHub Reservation",
  RESERVATION_DESC:
    "Select a date, time, and number of guests to reserve a table at our partner restaurants.",
  CONFIRM_RESERVATION: "Confirm reservation",
  BLOG_TITLE: "News & Careers",
  BLOG_DESC:
    "Stay updated with the latest restaurant technology trends and internal news from FoodHub.",
  BLOG_INSIGHT: "Insight",
  READ_MORE: "Read more",

  REVIEWS_TITLE: "Partner Reviews",
  REVIEWS_DESC: "What chefs and managers say about us.",
  REVIEWS_LIST: [
    {
      author: "Chef Toan Nguyen",
      role: "Ocean Grill",
      content:
        "Since using FoodHub, ticket errors have been virtually eliminated. The kitchen team coordinates much more smoothly.",
    },
    {
      author: "Ms. Lan Anh",
      role: "Manager at Red Coral",
      content:
        "Detailed reporting helps me keep track of business even when I'm not at the restaurant.",
    },
    {
      author: "Mr. Minh Quan",
      role: "Owner of Tasty Hub chain",
      content: "Stable software, modern interface, and very easy to train new staff.",
    },
  ],
  RESERVATION: {
    SUBTITLE: "Reservations",
    TITLE_MAIN: "Reserve Your",
    TITLE_ITALIC: "Experience",
    TITLE_SUFFIX: "today.",
    DESCRIPTION:
      "Don't let precious moments wait. FoodHub is committed to providing the finest dining spaces.",
    HOTLINE_LABEL: "24/7 Support Hotline",
    HOTLINE_NUMBER: "1900 6868",
    FORM: {
      NAME_LABEL: "Guest name",
      NAME_PLACEHOLDER: "John Doe",
      PHONE_LABEL: "Phone number",
      PHONE_PLACEHOLDER: "09xx xxx xxx",
      DATE_LABEL: "Dining date",
      DATE_PICKER_EMPTY: "Select date",
      TIME_LABEL: "Arrival time",
      TIME_PLACEHOLDER: "Select time",
      TIME_EMPTY: "No time available",
      GUESTS_LABEL: "Number of guests",
      AREA_LABEL: "Area",
      AREA_PLACEHOLDER: "Select location",
      MENU_LABEL: "Dining type",
      MENU_PLACEHOLDER: "Select menu type",
      NOTE_LABEL: "Message (Max 200 characters)",
      NOTE_PLACEHOLDER: "Special requests (Birthday, allergies...)",
      SUBMIT_BUTTON: "Confirm reservation",
      SUBMIT_DISABLED: "Not accepting guests",
      FOOTER_NOTE: "Instant confirmation • Free cancellation (45min before)",
    },
    AREAS: [
      { value: 0, label: "Regular Room" },
      { value: 1, label: "VIP Room" },
    ],
    MENU_TYPES: [
      { value: "alacarte", label: "A la carte" },
      { value: "combo", label: "Combo / Set menu" },
    ],
  },
};
