export const MENU = {
  TITLE: "Menu Management",
  SUBTITLE: "Centralized system for managing dishes, prices, and station coordination.",
  ADD_NEW_ITEM: "Add new item",
  TAB_ITEM: "Individual Items",
  TAB_COMBO: "Combo / Set Menu",
  ADD_ITEM: "+ Add item",
  ADD_COMBO: "Add Combo",
  EMPTY_COMBO: "No combo data yet...",
  ID_NOT_FOUND: "Error: Menu item ID not found!",
  DELETE_SUCCESS: "Deleted successfully!",
  DELETE_CONFIRM: (name: string) => `Are you sure you want to delete "${name}"?`,
  UPDATE_STOCK_ERROR: "Could not update stock status!",
  SAVE_SUCCESS: "Data saved successfully!",
  DELETE_DEFAULT_ERROR:
    "This item has been included in invoices and cannot be deleted. Please disable the sale status instead!",
  MENUCOUNT: (count: number) => `${count} items`,
  NAV: {
    OVERVIEW: "Overview",
    MENU_LIST: "Menu List",
    OPTIONS: "Option Groups",
    RECIPES: "Item Recipes",
  },
  OPTIONS: {
    TITLE: "Menu Item Options",
    MENU_FAILED: "Could not load options for this item!",
    NAME_GROUP: "Option group name",
    TYPE: "Option type",
    REQUIRED_MARK: "*",
    CHOOSE_ONE: "Choose one",
    MAXIMUM: "Maximum",
    REQUIRED_LABEL: "Required",
    SELECTED: "Selected",
    NEED_SELECT: "Select required",
    ADD_TO_ORDER: "Add to order -",
    ITEM_NOTE: "Item note",
    PRICE_EXTRA: "Extra price",
    PLACEHOLDER_OPTION_NAME: "e.g. Size M",
    PLACEHOLDER_EXTRA_PRICE: "e.g. 10000",
    COMBO_ITEMS: "Options in group",
    EMPTY_COMBO: "No options yet. Click Add to create.",
    ADD_FROM_LIBRARY: "Add option group",
    REUSABLE_TITLE: "Option list",
    SEARCH_PLACEHOLDER: "Search group name...",
    MIN_SELECT: "Minimum selection",
    MAX_SELECT: "Maximum selection",
    ASSIGNED_OPTIONS: "Assigned options",
    CREATE_NEW_GROUP: "Create new group",
    USAGE_COUNT: (count: number) => `Used in ${count} items`,
    VIEW_ITEMS: (count: number) => `View ${count} options`,
    CREATE_FIRST_HINT: "Create the first option group to start setting up the menu.",
    CREATE_GROUP: "Create new group",
    NO_ITEMS: "No options yet",
    ASSIGN_DESC: "Configure rules for each option group on this item.",
    LIBRARY_DESC: "Assign pre-configured option groups to this item.",
    EMPTY_ASSIGNED: "No options assigned yet. Click 'Add option group' to start.",
    EMPTY_LIBRARY: "No template group data available.",
    MASTER_DESC: "System for managing shared option groups across the entire menu.",
    FILTER_ALL_TYPES: "All types",
    TYPE_SINGLE: "Single choice",
    TYPE_MULTI: "Multiple choice",
    ASSIGNED_TO_ITEMS: "Assigned to items",
    EMPTY_MASTER: "No option group data found.",
    CREATE_GROUP_TITLE: "Create new option group",
    CREATE_GROUP_DESC: "Set up information and options within the group.",
    EDIT_GROUP_TITLE: "Edit option group",
    EDIT_GROUP_DESC: "Update information and option list.",
    SECTION_GROUP_INFO: "Group information",
    PLACEHOLDER_GROUP_NAME: "e.g. Size, Sweetness, Topping...",
    TYPE_SINGLE_HINT: "Customer can only select exactly 1 option (radio).",
    TYPE_MULTI_HINT: "Customer can select multiple options (checkbox).",
    IS_ACTIVE_LABEL: "Visible",
    STATUS_HIDDEN: "Hidden",
    ADD_ITEM_BTN: "Add option",
    ITEM_LABEL_COL: "Option name",
    ITEMS_HINT: "Options the customer will see when ordering.",
    ACTIVE_HINT: "Enable for customer to select this option.",
    ITEMS_COUNT_SUFFIX: "options",
    VALIDATE_NAME_REQUIRED: "Please enter the option group name.",
    VALIDATE_ITEMS_MIN: "At least 1 option is required in the group.",
    VALIDATE_ITEM_LABEL: "Option name cannot be empty.",
    CREATE_SUCCESS: "Option group created successfully!",
    EDIT_SUCCESS: "Option group updated successfully!",
    DELETE_SUCCESS: "Option group deleted successfully!",
    DELETE_CONFIRM: (name: string) =>
      `Are you sure you want to delete group "${name}"? This action cannot be undone.`,
    DELETE_IN_USE_ERROR: "This group is being used in menu items and cannot be deleted.",
  },
  COL_ITEM_NAME: "Item",
  COL_CATEGORY: "Category",
  COL_PRICE: "Price",
  COL_STATUS: "Status",
  COL_ACTION: "Actions",
  STATUS_OUT_OF_STOCK: "Out of stock",
  STATUS_IN_STOCK: "In stock",
  NO_CATEGORY: "None",
  TOOLTIP_CHANGE_STATUS: "Change status",
  TOOLTIP_EDIT: "Edit",
  TOOLTIP_DELETE: "Delete",
  NOT_FOUND_TITLE: "No menu items found!",
  NOT_FOUND_DESC: "Please check the filters or add a new item.",
  MODAL_EDIT_TITLE: "Edit menu item",
  MODAL_ADD_TITLE: "Add new menu item",
  MODAL_EDIT_DESC: "Update the item details.",
  MODAL_ADD_DESC: "Fill in the information to create a new menu item for the restaurant.",
  LABEL_NAME: "Item name",
  LABEL_DESC: "Description",
  LABEL_STATION: "Preparation area",
  LABEL_PRICE: "Price (VNĐ)",
  LABEL_COST: "Cost (VNĐ)",
  LABEL_CATEGORY: "Category",
  LABEL_IMAGE_URL: "Image (URL)",
  LABEL_MARK_OUT_OF_STOCK: "Mark as Out of Stock (Not for sale)",
  LABEL_EXPECTED_TIME: "Prep time (minutes)",
  LABEL_IMAGE_VIEW: "View image",
  LABEL_COMBO_ITEMS: "Combo items",
  SELECT_ITEM_PLACEHOLDER: "Select item",
  COMBO_SEARCH_PLACEHOLDER: "Search for an item...",
  PLACEHOLDER_NAME: "e.g. Pho Bo",
  PLACEHOLDER_DESC: "Detailed description of the dish...",
  PLACEHOLDER_STATION: "Select area",
  PLACEHOLDER_PRICE: "e.g. 50000",
  PLACEHOLDER_COST: "e.g. 30000",
  PLACEHOLDER_CATEGORY: "Select category",
  PLACEHOLDER_IMAGE_URL: "https://example.com/image.jpg",
  PLACEHOLDER_EXPECTED_TIME: "e.g. 15",
  OPTION_SELECT_DEFAULT: "-- Select --",
  BUTTON_CANCEL: "Cancel",
  BUTTON_UPDATE: "Update",
  BUTTON_CREATE: "Create",
  STATION: {
    HOTKITCHEN: "Hot Kitchen",
    COLDKITCHEN: "Cold Kitchen",
    DRINKS: "Beverage",
  },
  LOADING_IMAGE: "Loading image...",
  UPLOADING_IMAGE: "Processing image...",
  FETCHING_RECIPE: "Loading recipe data...",
  UNIT_VND: "VNĐ",
  HELPER_INGREDIENTS: "Set up the ingredient components for this dish.",
  HELPER_KDS_DEDUCTION:
    "When this dish is completed on KDS, the system will automatically deduct inventory based on this recipe. Ensure data accuracy for correct inventory reports.",
  ADD_NOW: "Add now",
  INGREDIENTS_COUNT: (count: number) => `${count} ingredients`,
  PLACEHOLDER_SEARCH: "Search item name...",
  MAX_SELECT_REACHED: (max: number) => `Maximum ${max} options can be selected`,
  PLEASE_SELECT_GROUP: (name: string) => `Please select "${name}"`,
  ADDED_TO_ORDER: "Added to order",
  FILTER_ALL_CATEGORY: "All categories",
  FILTER_OUT_OF_STOCK: "Out of stock",
  CATEGORY: {
    COFFEE: "Coffee",
    SOUP: "Soup",
    TEA: "Tea",
  },
  MENU_PAGE_SUBTITLE: "Add, edit, delete and manage dish status in the restaurant.",
  TAB_DETAILS: "Item Details",
  TAB_RECIPE: "Recipe & Ingredients",
  TAB_MEDIA: "Images & Media",
  TAB_ITEM_S: "Items",
  TAB_COMBO_S: "Combo",
  MODAL_ID_PREFIX: "ID:",
  MEDIA_MANAGEMENT_TITLE: "Media Management",
  MEDIA_MANAGEMENT_DESC: "Upload images or videos for this dish.",
  MEDIA: {
    UPLOAD_NEW: "Upload new file",
    PREVIEW: "Preview",
    CURRENT_IMAGE: "Current item image",
    EMPTY: "No image to display",
    HINT_PRIORITY:
      "If a file is uploaded, the system will prioritize the newly selected image when saving.",
    SELECTED_FILE: (name: string) => `Selected: ${name}`,
    UPLOAD_HINT: "You can upload a new image here.",
    HAS_IMAGE: "Has image",
    NO_IMAGE: "No image",
  },
  OR: "OR",
  RECEIPT: {
    TITLE: "Invoice Details",
    DISCOUNT: "Discount",
    SUBTOTAL: "Subtotal",
    TAX: "Tax",
    TOTAL: "Total",
  },
  RECIPE: {
    SETUP_TITLE: "Recipe Setup",
    SETUP_DESC: "Define the ingredients and quantities needed for this dish.",
    ADD_INGREDIENT: "Add ingredient",
    SEARCH_INGREDIENT_PLACEHOLDER: "Search ingredient...",
    CATEGORY_PLACEHOLDER: "Category",
    CATEGORY_ALL: "All categories",
    CATEGORY_MEAT: "Meat",
    CATEGORY_VEGGIE: "Vegetables",
    CATEGORY_SPICE: "Spices",
    SEARCH_BUTTON: "Search",
    INGREDIENT_NAME: "Ingredient name",
    UNIT: "Unit",
    STOCK_COLUMN: "Stock",
    QUANTITY_COLUMN: "Quantity",
    NO_INGREDIENTS_FOUND: "No ingredients found.",
    CONFIRM_ADD_BUTTON: "Confirm added",
    TOTAL_COST: "Total recipe cost",
    PREP_TIME: "Prep time (minutes)",
    INSTRUCTIONS: "Preparation instructions",
    QUANTITY: "Quantity",
    COST: "Estimated cost",
    IS_OPTIONAL: "Optional",
    INGREDIENTS_LIST: "Ingredients list",
    EMPTY_MAPPED: "No ingredients yet. Click Add ingredient to start.",
    SAVING: "Saving recipe...",
    SAVE_SUCCESS: "Recipe saved successfully!",
    SAVE_ERROR: "Failed to save recipe. Please try again!",
    LOADING: "Loading recipe data...",
    SAVE_RECIPE: "Save recipe",
    DISCARD: "Discard",
    QUANTITY_MIN_ERROR: "Quantity must be greater than 0",
    AT_LEAST_ONE_ERROR: "At least one ingredient is required",
    INSTRUCTIONS_PLACEHOLDER: "Describe the cooking process...",
    PREP_TIME_PLACEHOLDER: "e.g. 15",
    TITLE: "Recipe Details",
    DESCRIPTION: "View and edit ingredients needed to prepare this dish.",
    INGREDIENT: "Ingredient",
    INSTRUCTION: "Cooking instructions",
    CURRENCY: "$",
    TOTAL_COST_DESC: "Based on the latest import price of ingredients in the recipe.",
  },
  OVERVIEW: {
    HERO_DESC:
      "Monitor menu coverage, items needing priority updates, and service capacity by category before going into detailed operations.",
    STATS: {
      SELLABLE: "Items on sale",
      COMBOS: "Combos / set menus",
      UNAVAILABLE: "Unavailable items",
      CATEGORIES: "Categories in use",
    },
    ACTIONS: {
      CATALOG: "Manage item list",
      OPTIONS: "Manage option groups",
      RECIPES: "Set up item recipes",
    },
    SECTIONS: {
      CATEGORY_MIX: "Category Mix",
      CATEGORY_MIX_DESC:
        "Quick overview of which categories have the largest share in the current item list.",
      STATION_READINESS: "Station Capacity",
      STATION_READINESS_DESC:
        "Distribute items by station to balance load between hot kitchen, cold kitchen, and beverage station.",
      CHECKLIST: "Pre-shift Quick Check",
      CHECKLIST_DESC: "Quick signals to check if the menu is ready for operations.",
      PRIORITY: "Items Requiring Attention",
      PRIORITY_DESC:
        "These items show signs of needing early updates for better menu display and smoother operations.",
      OPTION_HIGHLIGHTS: "Most Used Option Groups",
    },
    CHECKLIST: {
      IMAGE_COVERAGE: "Has display image",
      IMAGE_HINT: "among all items and combos",
      COST_COVERAGE: "Has cost price",
      COST_HINT: "cost price configured",
      OPTION_COVERAGE: "Active option groups",
      OPTION_HINT: "option groups assigned",
      UNAVAILABLE_HINT: "needs ingredient or sale status check",
    },
    EMPTY: {
      CATEGORIES: "No category data to display.",
      STATIONS: "No items assigned to a preparation station yet.",
      PRIORITY: "Menu looks good. No items need priority attention.",
      STATION_NO_DATA: "No prep time data available",
    },
    REASONS: {
      OUT_OF_STOCK: "Out of stock",
      MISSING_IMAGE: "Missing image",
      MISSING_COST: "No cost price",
      LONG_PREP: "Long prep time",
    },
    AVG_PREP_SUFFIX: "min avg",
    ITEM_UNIT: "items",
    REFRESH: "Refresh",
  },
};
