export const ORDER = {
  TITLE: "Orders",
  EMPTY: "No orders yet",
  TAB_ORDER: "Orders",
  TAB_MENU: "Menu",
  FETCH_ORDERING: "Loading orders...",
  FETCH_MENU: "Loading menu...",
  FETCH_ERROR: "Could not load order list",
  DESCRIPTION_DETAIL: (tableNumber: string, total: number) =>
    `${tableNumber} • Total ${total} items`,
  NOTE: (note: string) => `Note: ${note}`,
  QUANTITY: (quantity: number) => `Qty: ${quantity}`,
  BOARD: {
    TABLE_ZONE: "Table Zone",
    ORDER_COUNT: (count: number) => `${count} orders`,
    PICK_ORDER_TITLE: "Select Order",
    PICK_ORDER_DESC: "Select an active order on this table to view details.",
    CREATE_TAKEAWAY_ORDER: "Create takeaway order",
    TAKEAWAY_ORDERS: "Takeaway Orders",
    AVAILABLE_LCT: "Available",
    AT_TABLE: "Dine-in",
    TAKEAWAY: "Takeaway",
    LATEST_UPDATE: "Latest update",
    OLDEST_UPDATE: "Oldest update",
    SORT_BY: "Sort by",
    STATUS_LABEL: "Status",
    ADVANCED_FILTER: "Advanced filter",
    OVERVIEW: "Overview",
    ORDER_CODE: "Order Code",
    TYPE_TABLE: "Type / Table",
    TIME: "Time",
    TOTAL_AMOUNT: "Total",
    VIP: "VIP",
    ALL_STATUS: "All statuses",
    ALL_TYPE: "All order types",
    DINE_IN_LABEL: "Dine-in",
    TAKEAWAY_LABEL: "Takeaway",
    LOADING_DATA: "Loading data...",
    NOT_FOUND: "No matching orders found.",
    SEARCH_PLACEHOLDER: "Search order code, table number...",
    TABLE_PREFIX: "Table:",
    PAGE: "Page",
    PAGE_PREV: "Previous page",
    PAGE_NEXT: "Next page",
    FETCH_ERROR: "Error loading order list.",
    CREATE_ORDER_ERROR: "Failed to create order",
    NOT_SELECTED_TABLE: "No table selected",
    STATUS_AVAILABLE: "Available",
    STATUS_SERVING: "In use",
    STATUS_RESERVED: "Reserved",
    STATUS_OUT_OF_SERVICE: "Out of service",
    GET_STATUS_LABEL: (status: string) => {
      switch (status) {
        case "ready":
          return "Available";
        case "serving":
          return "In use";
        case "reserved":
          return "Reserved";
        case "out_of_service":
          return "Out of service";
        case "tk_serving":
          return "Cooking";
        case "tk_ready":
          return "Ready";
        default:
          return status;
      }
    },
    DROPDOWN_FEATURE: {
      MERGE: "Merge orders",
      MERGE_LABEL: "Select orders to merge",
      MERGE_NO_ORDERS: "No orders available to merge",
      LABEL_MERGE: "Select orders to merge",
      MERGE_SUCCESS: "Orders merged successfully",
      MERGE_ERROR: "Failed to merge orders",
      MERGE_ORIGIN: "Source order",
      MERGE_DESTINATION: "Target order",
      MERGE_PLACEHOLDER: "Select order to merge",
      MERGE_SECOND_ORDER_REQUIRED: "Target order cannot be empty",
      MERGE_DUPLICATE_ERROR: "Cannot merge the same order",
      SPLIT: "Split order",
      SPLIT_ORIGIN: "Source order",
      SPLIT_SUMMARY: (lineCount: number, itemTotal: number) =>
        `${lineCount} items | ${itemTotal} portions`,
      SPLIT_DESTINATION_LABEL: "Item destination",
      SPLIT_DESTINATION_DESC:
        "Select an existing order or an available table to create a new order.",
      SPLIT_MODE_SAME: "Same table",
      SPLIT_MODE_EXISTING: "Existing order",
      SPLIT_MODE_NEW: "Available table",
      SPLIT_DESTINATION_ORDER: "Target order",
      SPLIT_DESTINATION_ORDER_PLACEHOLDER: "Select receiving order",
      SPLIT_DESTINATION_TABLE: "Target table",
      SPLIT_DESTINATION_TABLE_PLACEHOLDER: "Select available table for new order",
      SPLITED_ITEMS_LABEL: "Items to split",
      SPLITED_ITEMS_DESC: "Select the quantity to transfer for each item.",
      SPLIT_SELECTED_COUNT: (count: number) => `${count} portions transferred`,
      SPLIT_LOADING_ITEMS: "Loading items...",
      SPLIT_EMPTY_ITEMS: "No items to split.",
      SPLIT_ITEM_QTY_LABEL: "Current quantity:",
      SPLIT_ITEM_NOTE_LABEL: "Note:",
      SPLIT_ITEM_COMPLETED_ERROR: "Item is completed, cannot be split.",
      SPLIT_SUCCESS: "Order split successfully",
      SPLIT_ERROR: "Failed to split order",
      SPLIT_ACTION_NEW: "Create split order",
      SPLIT_ACTION_EXISTING: "Split to target order",
      SPLIT_FETCH_ITEMS_ERROR: "Could not load items for this table",
      SPLIT_REQUIRED_QTY: "Select quantity of items to split",
      SPLIT_REQUIRED_DESTINATION_ORDER: "Select target order to receive items",
      SPLIT_REQUIRED_DESTINATION_TABLE: "Select available table for new order",
      SPLIT_DESTINATION_SAME_ORDER: "Same order",
      SPLIT_DESTINATION_EXISTING_ORDER: "Other order",
      SPLIT_DESTINATION_NEW_TABLE: "Other table",
      MOVE_TABLE: "Move table",
      MOVE_TABLE_LABEL: "Select table to move to",
      MOVE_TABLE_ORIGIN: "Source table",
      MOVE_TABLE_DESTINATION: "Target table",
      MOVE_TABLE_SUCCESS: "Table moved successfully",
      MOVE_TABLE_ERROR: "Failed to move table",
      MOVE_TABLE_SELECT_PLACEHOLDER: "Select order",
      MOVE_TABLE_ORDER_REQUIRED: "No order found for this table",
      MOVE_TABLE_DESTINATION_REQUIRED: "Select target table to move to",
      CANCEL: "Cancel order",
      CANCEL_CONFIRM: "Are you sure you want to cancel this empty order?",
      CANCEL_SUCCESS: "Order cancelled successfully",
      CANCEL_ERROR: "Failed to cancel order",
    },
  },
  CURRENT: {
    TOTAL_AMOUNT: "Total Payment",
    PAYMENT_METHOD: "Payment method",
    CASH: "Cash",
    TRANSFER: "Transfer",
    CARD: "Card (POS)",
    MIXED_CASH_QR: "Cash + QR",
    CUSTOMER_GAVE: "Customer paid",
    QR_AMOUNT: "QR Payment",
    CHANGE: "Change",
    PROCESSING: "Processing...",
    CREATING_QR: "Generating QR...",
    CREATE_QR_WITH_AMOUNT: (amount: string) => `Create payment QR (${amount})`,
    SUBTOTAL: "Subtotal",
    TAX: "Tax (VAT 10%)",
    DISCOUNT: "Discount",
    ADD_TO_ORDER: "Add to order",
    PAY: "Checkout",
    PRINT_TEMP_ACTION: "Print pre-check",
    EMPTY: "No items in the order yet",
    CONFIRM_PAYMENT: "Confirm payment",
    CHECKOUT_TITLE: "Order Checkout",
    CHECKOUT_DESC: "Please select a payment method and confirm",
    NEW: "New",
    STATUS_PREP: "Preparing",
    STATUS_COOKING: "Cooking",
    STATUS_DONE: "Done",
    STATUS_SERVING: "Serving",
    STATUS_COMPLETED: "Completed",
    STATUS_CANCELLED: "Cancelled",
    STATUS_REJECTED: "Rejected",
    STATUS_PAID: "Paid",
    TAKEAWAY: "Takeaway",
    DINE_IN: "Dine-in",
    QR_CREATE_ERROR: "Could not generate payment QR code.",
    QR_FETCH_ERROR: "An error occurred while loading the QR code.",
    PAYMENT_RECEIVED: "Payment received!",
    INPUT_AMOUNT_REQUIRED: "Please enter the amount paid by customer",
    INVALID_AMOUNT: "Amount paid is invalid or less than total",
    PAYMENT_SUCCESS: "Payment successful!",
    PAYMENT_FAILED: "Payment failed, please try again.",
    PAYMENT_ERROR: "An error occurred during payment.",
    SELECT_TABLE_REQUIRED: "Please select a table before submitting",
    ORDER_NOT_FOUND: "Order information not found",
    CART_EMPTY: "Cart is empty",
    SUBMIT_SUCCESS: "Successfully sent to kitchen!",
    SUBMIT_FAILED: "Failed to send to kitchen",
    SUBMIT_ERROR: "An error occurred while sending request",
    SYNC_PAYMENT: "Check payment",
    SYNCING: "Checking...",
    SYNC_CONFIRM: "The system will check payment status from PayOS.",
  },
  PRINT_TEMP: {
    TITLE: "PRE-CHECK BILL",
    TIME: "Print date",
    EMPLOYEE: "Staff",
    ORDER_CODE(orderCode: string) {
      return `Order Code: ${orderCode}`;
    },
    MENU_NAME: "Item name",
    QUANTITY: "Quantity",
    UNIT_PRICE: "Unit price",
    AMOUNT: "Amount",
    TAX_LABEL: "VAT (10%)",
    BEFORE_TAX: "Total before tax",
    TOTAL_AMOUNT: "Total payment",
    THIS_IS_NOT_RECEIPT: "This is not a payment receipt",
    THANK_YOU: "Thank you and see you again!",
    PAYMENT_METHOD_LABEL: "Method:",
    CUSTOMER_GAVE_LABEL: "Customer paid:",
    CHANGE_LABEL: "Change:",
    METHOD_TRANSFER_QR: "Transfer / QR",
    METHOD_CASH: "Cash",
    METHOD_CARD: "Card / Transfer",
    SHOP_ADDRESS: "123 Food Street, District 1, HCM",
    SHOP_PHONE_PREFIX: "Tel:",
    SHOP_PHONE: "0123.456.789",
    RECEIPT_ID_PREFIX: "No:",
    PRINT_DATE: "Print date:",
    TABLE_PREFIX: "Table:",
    TAKEAWAY_LABEL: "Takeaway",
    CASHIER_LABEL: "Cashier:",
    ITEM_NAME_HEADER: "Item",
    QUANTITY_HEADER: "Qty",
    AMOUNT_HEADER: "Amount",
    SUBTOTAL_LABEL: "Subtotal:",
    DISCOUNT_LABEL: "Discount",
    TAX_LABEL_PREFIX: "Tax",
    TOTAL_LABEL: "TOTAL:",
    FOOTER_THANK_YOU: "THANK YOU - SEE YOU AGAIN",
    FOOTER_CHECK_BEFORE_LEAVE: "Please check your bill carefully before leaving",
  },
  DETAIL: {
    TITLE: "Order Details",
    DESCRIPTION_MANAGER: "Track order information, items, payments, and audit logs.",
    BACK_TO_LIST: "Back to list",
    LOADING: "Loading order details...",
    EMPTY_TITLE: "No order data",
    EMPTY_DESC: "No matching order found.",
    TAB_OVERVIEW: "Overview",
    TAB_ITEMS: "Items",
    TAB_PAYMENT: "Payment",
    TAB_AUDIT: "Audit Log",
    TIMELINE_TITLE: "Timeline",
    TIMELINE_DESC: "Order lifecycle.",
    TIMELINE_CREATE: "Created",
    TIMELINE_UPDATE: "Updated",
    TIMELINE_PAID: "Paid",
    TIMELINE_COMPLETE: "Completed",
    TIMELINE_CANCEL: "Cancelled",
    ORDER_TYPE: "Order type",
    TABLE_RESERVATION: "Table / Reservation",
    SUBTOTAL: "Subtotal",
    TOTAL_AMOUNT: "Total payment",
    ITEMS_TITLE: "Item List",
    ITEMS_EMPTY_TITLE: "No items in order",
    ITEMS_EMPTY_DESC: "Items will appear here.",
    QTY_LABEL: "Qty:",
    PRICE_LABEL: "Price:",
    NOTE_LABEL: "Note:",
    LINE_TOTAL: "Line total",
    SECTION_NOTE: "Item status, options, notes, and line totals.",
    PAYMENT_TITLE: "Payment",
    PAYMENT_METHOD: "Method",
    PAYMENT_RECEIVED: "Received",
    PAID_AT: "Paid at",
    VAT: "VAT",
    PRECHECK_TITLE: "Pre-check bill",
    PRECHECK_DESC: "Only active orders display this data.",
    PRE_SUBTOTAL: "Subtotal",
    PRE_PRETAX: "Pre-tax",
    PRE_VAT: "VAT",
    PRE_TOTAL: "Total",
    PRE_EMPTY_TITLE: "No pre-check bill yet",
    AUDIT_TIMELINE: "Order timeline",
    AUDIT_BE_TITLE: "Audit log BE",
    AUDIT_BE_DESC:
      "Track operations performed on the order, including who, when, and what data changed.",
    ITEM_COUNT: (count: number) => `${count} items in order`,
    SPLIT_BILL: "Split bill",
    SPLIT_BILL_PROMPT: (name: string) => `Enter quantity to split from "${name}"`,
    SPLIT_BILL_INVALID_QTY: "Invalid split quantity.",
    SPLIT_BILL_SUCCESS: "Bill split successfully.",
    SPLIT_BILL_FAILED: "Bill split failed.",
    ORDER_NOT_FOUND_FOR_TABLE: "No order found for this table",
    DISCOUNT_AMOUNT: "Discount",
    PROMOTION_CODE: "Promo code",
    VOUCHER_CODE: "Voucher Code",
    NOTE: "Order note",
    VAT_RATE: (rate: number) => `Tax (VAT ${rate}%)`,
    PAYMENT_INFO: "Payment information",
    CUSTOMER_INFO: "Customer information",
    RESERVATION_ID: "Reservation ID",
    TABLE_ID: "Table number",
    SUBTOTAL_BEFORE_DISCOUNT: "Subtotal (before discount)",
  },
  MANAGEMENT: {
    ARIA_NAV: "Order navigation",
    WORKSPACE_TITLE: "Order Management Workspace",
    WORKSPACE_DESC:
      "All-in-one screen for managers: view orders, check payments, and have audit logs ready.",
    RELOAD: "Reload",
    STATS: {
      TOTAL: "Total orders",
      SERVING: "Serving",
      REVENUE: "Revenue",
      VIP: "VIP",
    },
    TABS: {
      ORDERS: "Order List",
      BILLING: "Billing History",
      AUDIT: "Audit Log",
    },
    PAGE_COUNT: (count: number) => `${count} pages`,
  },
  OVERVIEW: {
    HERO_TITLE: "Order Management",
    HERO_DESC: "Track order status, payments, and audit from one place.",
    FETCH_ERROR: "Could not load order overview.",
    STATS: {
      ACTIVE: "Total active orders",
      WAITING: "Awaiting payment",
      PAID_TODAY: "Paid today",
    },
    BILLING_HISTORY: {
      TITLE: "Billing History",
      LOADING: "Loading billing history...",
      EMPTY: "No payment transactions yet.",
      UNKNOWN_METHOD: "Unknown",
    },
    AUDIT: {
      TITLE: "Audit Log",
      LOADING: "Loading audit log...",
      EMPTY: "No audit log data from API yet.",
      SERVING_ACTION: "Serving",
      UPDATE_ACTION: "Order updated",
    },
    DISTRIBUTION: {
      ORDER_TYPE: "Order Type Distribution",
      ORDER_TYPE_DESC:
        "Quick overview of dine-in, takeaway, and delivery order ratios in the current shift.",
      ORDER_STATUS: "Status Distribution",
      ORDER_STATUS_DESC:
        "Focus on main operational statuses to know where the kitchen and cashier stand.",
      EMPTY_TYPE: "No order type data to display.",
      EMPTY_STATUS: "No status data to display.",
    },
    STATUS_LABELS: {
      SERVING: "Serving",
      COMPLETED: "Kitchen completed",
      WAITING_CHECKOUT: "Awaiting payment",
    },
  },
  BILLING: {
    TITLE: "Billing History",
    SEARCH_PLACEHOLDER: "Search by order code or customer",
    METHOD_PLACEHOLDER: "Method",
    TYPE_PLACEHOLDER: "Order type",
    ALL_METHODS: "Payment method",
    CASH: "Cash",
    TRANSFER: "Transfer",
    CARD: "Card",
    DELIVERY: "Delivery",
    DINE_IN: "Dine-in",
    TAKEAWAY: "Takeaway",
    FETCH_ERROR: "Could not load billing history.",
    LOADING: "Loading billing history...",
    EMPTY: "No matching payment transactions.",
    COLUMNS: {
      ORDER_CODE: "Order Code",
      ORDER_TYPE: "Order Type",
      METHOD: "Method",
      PAID_AT: "Paid at",
      TOTAL: "Total",
      STATUS: "Status",
    },
  },
  COMBO: {
    BADGE_LABEL: "Combo",
    ITEMS_HEADING: "Combo items",
    ITEMS_HOVER_HINT: "Hover to view sub-items in combo",
    ITEMS_LABEL: "Combo Items",
    ITEMS_SELECTION_HINT: "Select sub-items and options if available",
    QUANTITY_LABEL: "Quantity:",
    QUANTITY_SEPARATOR: "x",
    CHILD_NOTE_LABEL: "Item note",
    NO_ITEMS_MESSAGE: "No sub-items for this combo yet.",
  },
};
