export const RESERVATION = {
  TITLE: "Reservations",
  STATS_TOTAL: "Total reservations",
  STATS_BOOKED: "Booked",
  STATS_ARRIVED: "Arrived",
  STATS_CANCELLED: "Cancelled",

  COL_CODE: "Reservation code",
  COL_CUSTOMER: "Customer",
  COL_DATETIME: "Date & Time",
  COL_AREA: "Area",
  COL_PEOPLE: "Guests",
  COL_PARTY_TYPE: "Party type",
  COL_STATUS: "Status",
  COL_ACTIONS: "Actions",

  STATUS_BOOKED: "Booked",
  STATUS_CHECKED_IN: "Arrived",
  STATUS_CANCELLED: "Cancelled",
  STATUS_NO_SHOW: "No Show",

  SEARCH_PLACEHOLDER: "Search by name, phone...",
  AREA_FILTER: "Area",
  STATUS_FILTER: "Status",
  CREATE_BTN: "New reservation",
  ALL_AREAS: "All areas",
  ALL_STATUSES: "All statuses",
  STATUS_FILTER_BOOKED: "Booked",
  STATUS_FILTER_ARRIVED: "Arrived",
  STATUS_FILTER_CANCELLED: "Cancelled",

  CREATE_DIALOG_TITLE: "Create new reservation",
  EDIT_DIALOG_TITLE: "Edit reservation",
  FIELD_CUSTOMER_NAME: "Customer name",
  FIELD_CUSTOMER_NAME_PLACEHOLDER: "Enter customer name",
  FIELD_PHONE: "Phone number",
  FIELD_PHONE_PLACEHOLDER: "Enter phone number",
  FIELD_DATE: "Booking date",
  FIELD_TIME: "Booking time (24h)",
  FIELD_AREA: "Area",
  FIELD_PEOPLE_COUNT: "Number of guests",
  FIELD_PARTY_TYPE: "Party type",
  FIELD_PARTY_TYPE_NONE: "None",
  FIELD_NOTE: "Notes",
  FIELD_NOTE_PLACEHOLDER: "Enter additional notes...",
  BTN_CANCEL: "Cancel",
  BTN_SUBMIT_CREATE: "Create reservation",
  BTN_SUBMIT_UPDATE: "Update",
  BTN_SAVING: "Saving...",

  CREATE_DIALOG_DESC: "Fill in details to create a new reservation.",
  EDIT_DIALOG_DESC: "Edit details of the current reservation.",
  PLACEHOLDER_PARTY_TYPE: "Select party type",
  PLACEHOLDER_AREA: "Select area",
  AREA_ANY: "Any",

  PARTY_TYPE_NORMAL: "Regular dining",
  PARTY_TYPE_BIRTHDAY: "Birthday party",
  PARTY_TYPE_ANNIVERSARY: "Anniversary",
  PARTY_TYPE_CORPORATE: "Corporate event",

  BTN_BACK: "Back",
  BTN_CONFIRM_CANCEL: "Confirm cancel",
  BTN_CONFIRM_ARRIVAL: "Confirm",
  BTN_CLOSE_DIALOG: "Cancel",

  CONFIRM_ARRIVAL_TITLE: "Start serving",
  CONFIRM_ARRIVAL_DESC_1: "Confirm that customer",
  CONFIRM_ARRIVAL_DESC_2: "has arrived at the restaurant?",
  CONFIRM_ARRIVAL_TABLE: "Table",
  CONFIRM_ARRIVAL_PEOPLE: "Guests",

  CANCEL_BOOKING_TITLE: "Cancel reservation",
  CANCEL_BOOKING_DESC_1: "Reservation for",
  CANCEL_BOOKING_DESC_2: "will be cancelled. This action cannot be undone.",

  ACTION_EDIT: "Edit",
  ACTION_CANCEL: "Cancel reservation",
  REQUIRED_MARK: "*",
  HELP_ICON: "ℹ️",
  EMPTY_DATA: "No reservation data found.",

  PAGINATION_SHOWING: "Showing",
  PAGINATION_OF: "of total",
  PAGINATION_UNIT: "reservations",

  VALIDATION_MIN_LEAD_TIME: "Please book at least the required time in advance.",
  VALIDATION_MIN_LEAD_TIME_DYNAMIC: (min: number) =>
    `Please book at least ${min} minutes in advance.`,
  VALIDATION_WITHIN_OPERATING_HOURS: "Reservation must be within restaurant operating hours (24h).",
  VALIDATION_WITHIN_OPERATING_HOURS_DYNAMIC: (open: string, close: string) =>
    `Reservation must be within operating hours ${open} - ${close}.`,
  VALIDATION_BREAK_TIME: "Restaurant is on break. Please select a different time.",
  VALIDATION_BREAK_TIME_DYNAMIC: (start: string, end: string) =>
    `Restaurant break time from ${start} to ${end}. Please select a different time.`,
  VALIDATION_REQUIRED_NAME_PHONE: "Please enter customer name and phone number",
  VALIDATION_REQUIRED_DATE_TIME: "Please select reservation date and time",
  VALIDATION_VIP_REQUIRED: "Groups over 12 guests require a VIP room reservation.",
  ERROR_CREATE_FAILED: "Failed to create reservation",
  ERROR_SAVE_FAILED: "Failed to save information",
  ERROR_CONNECTION: "Could not connect to server",
  ERROR_UNKNOWN: "An unknown error occurred",

  SWITCH_AREA_TITLE: "Switch area",
  SWITCH_AREA_DESC:
    "The previous area has no available tables. Please select a table in a different area.",
  SWITCH_AREA_SELECT_LABEL: "Select area",
  SWITCH_AREA_SELECT_PLACEHOLDER: "Select area...",
  SWITCH_TABLE_SELECT_LABEL: "Select available table",
  SWITCH_TABLE_PLACEHOLDER_SELECT_AREA: "Select an area first",
  SWITCH_TABLE_PLACEHOLDER_NO_TABLE: "No matching available tables",
  SWITCH_TABLE_PLACEHOLDER_SELECT_TABLE: "Select table...",
  BTN_CONFIRM_SWITCH_CHECKIN: "Confirm switch & Check-in",
  MSG_SWITCH_INFO: "Please select another table in an available area.",
};
