export const SALES_ANALYTICS = {
  TITLE: "Analytics & Statistics",
  DESCRIPTION: "Track your restaurant's business performance.",
  WIP_TITLE: "Feature in development",
  WIP_DESC:
    "This feature is currently under development. Please come back later to view detailed reports.",
  BEST_SELLERS_ANALYSIS: "Best-sellers Analysis",
  TOP_CATEGORY: "Top performing category",
  MOST_PROFITABLE: "Most profitable item",
  TOTAL_ITEM_SALES: "Total quantity sold",
  SEARCH_PLACEHOLDER: "Search dishes...",
  FILTER_CATEGORY: "Filter by category",
  SORT_BY: "Sort by",
  REVENUE_OVER_TIME: "Revenue over time",
  REVENUE_BY_CATEGORY: "Revenue by category",
  DAILY: "Daily",
  MONTHLY: "Monthly",
  MAIN_DISH: "Main dish",
  STARTER: "Appetizer",
  DRINK: "Beverages",
  DESSERT: "Dessert",
  RANK: "#",
  ITEM_NAME: "Dish",
  CATEGORY: "Category",
  QUANTITY: "Quantity",
  REVENUE: "Revenue",
  TOTAL_PERCENT: "% Total",
  TOTAL_REVENUE: "Total revenue",
  TOTAL_ORDERS: "Total orders",
  AVG_ORDER_VALUE: "Average order value",
  GROSS_PROFIT: "Gross profit",
  SALES_TARGET_LABEL: "Target",
  STABLE_OPERATIONS: "Stable operations",
  REAL_TIME_UPDATE: "Real-time updates",
  QUICK_INSIGHTS: "Quick insights",
  OPERATIONAL_SUGGESTION: "Operational suggestions",
  MANAGER_ONLY: "Only managers can view this detailed data.",
  EXPORT_REPORT: "Export report",
  SELECT_DATE: "Select date",
  EXPORT_BY_RANGE: "By date range",
  EXPORT_BY_MONTH: "By month",
  SELECT_MONTH: "Select month",
  SELECT_YEAR: "Select year",
  BEST_ITEM_INSIGHT: (name: string, percent: number) =>
    `${name} is the most effective, contributing ${percent}% of revenue.`,
  CATEGORY_INSIGHT: (name: string) => `${name} is leading. Consider optimizing the menu.`,
  EXPORT_SUCCESS: "Excel report exported successfully!",
  EXPORT_ERROR: "Export failed, please try again!",
};
