export const SHIFT = {
  TITLE: "Shift Management",
  ADD_SHIFT: "Create shift",
  EDIT_SHIFT: "Edit shift",
  SHIFT_NAME: "Shift name",
  START_TIME: "Start time",
  END_TIME: "End time",
  STATUS: "Status",
  ACTIVE: "Active",
  INACTIVE: "Paused",
  TOTAL_ACTIVE: "TOTAL ACTIVE",
  STAFF_WORKING: "STAFF ON DUTY",
  OVERTIME_RISK: "OVERTIME RISK",
  VACANT_POSITIONS: "VACANT POSITIONS",
  DESCRIPTION: "Description",
  POSITION: "Position",
  PLACEHOLDER_NAME: "e.g. Morning Shift",
  PLACEHOLDER_DESC: "Detailed description of the shift...",
  PLACEHOLDER_POSITION: "Select position...",
  CREATE_SUCCESS: "Shift created successfully",
  UPDATE_SUCCESS: "Shift updated successfully",
  DELETE_SUCCESS: "Shift deleted successfully",
  PAGE_DESC: "Configure and monitor work time frames for staff.",
  REPORT_DESC: "Staff attendance rate has increased since applying the new schedule.",
  ADD_NEW: "Add new shift",
  ADD_DESC: "Fill in information to create a new shift for the restaurant.",
  EDIT_DESC: "Update shift details.",
  DETAILS: "Shift details",
  MEDIA: "Images & Media",
  STATS_WEEKLY_CHANGE: "+2 this week",
  STATS_OVERTIME_WARNING: "High alert",
  STATS_UNASSIGNED: "Unassigned",
};

export const SCHEDULE = {
  TITLE: "Schedule Management",
  WEEK: "THIS WEEK",
  COPY_PREVIOUS: "Copy last week",
  SAVE_SCHEDULE: "Save schedule",
  TOTAL_STAFF: "TOTAL STAFF",
  ESTIMATED_HOURS: "ESTIMATED HOURS",
  ESTIMATED_COST: "ESTIMATED COST",
  SHIFT_COVERAGE: "SHIFT COVERAGE",
  EMPLOYEE_NAME: "EMPLOYEE",
  TODAY: "TODAY",
  MORNING_SHIFT: "MORNING SHIFT",
  AFTERNOON_SHIFT: "AFTERNOON SHIFT",
  PAGE_TEXT: "Page",
  REPORT_TITLE: "SHIFT PERFORMANCE REPORT",
  VIEW_ANALYTICS: "VIEW ANALYTICS",
  PENDING_REQUESTS: "PENDING REQUESTS",
  VIEW_ALL_REQUESTS: "VIEW ALL REQUESTS",
  ADMIN_TITLE: "CRIMSON STUDIO ADMIN",
  WEEK_DATES: "20/10 — 26/10",
  STATS_STAFF_SUB: "+2 new staff this week",
  STATS_HOURS_SUB: "Based on assigned schedule",
  STATS_COST_SUB: "VND (Base salary)",
  ASSIGN_TITLE: "Assign shift",
  ASSIGN_DESC: "Assign a shift to an employee on a specific date.",
  SELECT_SHIFT: "Select shift",
  SELECT_SHIFT_PLACEHOLDER: "Select shift...",
  NOTE_LABEL: "Notes",
  NOTE_PLACEHOLDER: "e.g. Make-up for last week",
  ASSIGN_BUTTON: "Assign",
  WORK_DATE: "Work date",
  UPDATE_SUCCESS: "Assignment updated successfully",
  DELETE_SUCCESS: "Assignment removed successfully",
  CONFIRM_DELETE: "Are you sure you want to remove this assignment?",
  EDIT_TITLE: "Edit assignment",
  REMOVE_BUTTON: "Remove assignment",
  HOURS_UNIT: "h",
  REQUEST_TYPE_SHIFT_CHANGE: "Shift swap - Afternoon shift",
  REQUEST_TYPE_LEAVE: "Leave - Friday",
  NOW: "Now",
  NEXT_WEEK: "Next week",
  NEXT_2_WEEKS: "In 2 weeks",
  NEXT_MONTH: "Next month",
  SELECT_WEEK: "Select work week",
  ASSIGNED_SHIFT: "Assigned shift",
  EMPTY_SHIFT: "Empty (Hover to assign)",
  AUTO_SAVE: "Auto-save quick changes",
  CHOOSE_WEEK: "SELECT WORK WEEK",
  PERIOD: "Period",
};
