export const VOUCHER = {
  TITLE: "Voucher Management",
  DESCRIPTION: "Manage discount codes and promotions",
  CREATE: "Create Voucher",
  EDIT: "Edit Voucher",
  UPDATE: "Update Voucher",
  DETAILS: "Voucher Details",

  SEARCH_PLACEHOLDER: "Search voucher code...",
  FILTER_TYPE: "Type",
  FILTER_STATUS: "Status",
  FILTER_ALL_TYPE: "All types",
  FILTER_ALL_STATUS: "All statuses",
  FILTER_ACTIVE: "Active",
  FILTER_INACTIVE: "Inactive",
  STATS_ACTIVE: "active",
  STATS_INACTIVE: "inactive",

  TABLE_CODE: "Voucher Code",
  TABLE_TYPE: "Type",
  TABLE_VALUE: "Value",
  TABLE_USAGE: "Usage",
  TABLE_VALIDITY: "Validity Period",
  TABLE_STATUS: "Status",
  TABLE_ACTIONS: "Actions",

  ACTION_VIEW: "View details",
  ACTION_VIEW_DESC: "View voucher information",
  ACTION_EDIT: "Edit",
  ACTION_EDIT_DESC: "Update voucher information",
  ACTION_DELETE: "Delete voucher",
  ACTION_DELETE_DESC: "Remove from system",
  ACTION_RETRY: "Retry",
  ACTION_CLOSE: "Close",
  ACTION_CANCEL: "Cancel",
  ACTION_SAVE: "Create Voucher",
  ACTION_ACTIVATE: "Activate",
  ACTION_DEACTIVATE: "Deactivate",
  ACTION_TOGGLE_DESC: "Toggle status",

  STATUS_ACTIVE: "Active",
  STATUS_INACTIVE: "Inactive",
  STATUS_EXPIRED: "Expired",
  STATUS_LABEL: "Status:",

  NOT_FOUND: "No vouchers found",
  DELETE_CONFIRM: (code: string) => `Are you sure you want to delete voucher "${code}"?`,

  PAGINATION_SHOWING: "Showing",
  PAGINATION_OF: "vouchers",
  PAGINATION_PREV: "‹",
  PAGINATION_NEXT: "›",
  ARROW: "→",

  SECTION_BASIC: "Basic Information",
  SECTION_VALUE: "Value & Limits",
  SECTION_VALIDITY: "Validity Period",
  SECTION_USAGE: "Usage & Status",

  FIELD_CODE: "Voucher code",
  FIELD_CODE_PLACEHOLDER: "e.g. SUMMER50",
  FIELD_TYPE: "Voucher type",
  FIELD_DISCOUNT_PERCENT: "Discount value (%)",
  FIELD_DISCOUNT_FIXED: "Discount value (đ)",
  FIELD_MAX_DISCOUNT: "Max discount (đ)",
  FIELD_MAX_DISCOUNT_PLACEHOLDER: "Optional",
  FIELD_MIN_ORDER: "Min order (đ)",
  FIELD_START_DATE: "Start date",
  FIELD_END_DATE: "End date",
  FIELD_START_TIME: "Start time",
  FIELD_END_TIME: "End time",
  FIELD_USAGE_LIMIT: "Usage limit",
  FIELD_STATUS: "Active status",
  FIELD_STATUS_ON: "Activate",
  FIELD_STATUS_OFF: "Deactivate",

  FREE_ITEM_TITLE: "Free item configuration",
  FREE_ITEM_ID: "Free item ID",
  FREE_ITEM_QTY: "Quantity",
  FREE_ITEM_SEARCH_PLACEHOLDER: "Search free item...",
  FREE_ITEM_SELECT_LABEL: "Select free item",

  VALIDATE_CODE_REQUIRED: "Please enter a voucher code",
  VALIDATE_DATE_REQUIRED: "Please select start and end dates",
  VALIDATE_DATE_ORDER: "End date must be after start date",

  CREATE_DESC: "Set up a new promotion program.",
  EDIT_DESC: "Update promotion voucher information.",
  SAVING: "Saving...",

  DETAIL_BASIC: "Basic Information",
  DETAIL_CONDITIONS: "Conditions",
  DETAIL_STATS: "Usage Statistics",
  DETAIL_CODE: "Voucher code",
  DETAIL_NAME: "Name",
  DETAIL_TYPE: "Type",
  DETAIL_VALUE: "Value",
  DETAIL_MIN_ORDER: "Min order",
  DETAIL_MAX_DISCOUNT: "Max discount",
  DETAIL_TIME_RANGE: "Duration",
  DETAIL_TIME_OF_DAY: "Time slot",
  DETAIL_ALL_DAY: "All day",
  DETAIL_FREE_ITEM: "Free item",
  DETAIL_UNLIMITED: "Unlimited",
  DETAIL_USED: "used",
  DETAIL_ENABLE: "Enable Voucher",
  DETAIL_ENABLE_DESC: "Allow customers to use this code",
  DETAIL_FREE_ITEM_LABEL: "Free item",

  SECTION_NUM_1: "1",
  SECTION_NUM_2: "2",
  SECTION_NUM_3: "3",
  SECTION_NUM_4: "4",

  SIDEBAR_TITLE: "Voucher",

  APPLY_MODAL_TITLE: "Apply discount code",
  APPLY_MODAL_DESC: "Enter a voucher code to get a discount on your order.",
  APPLY_MODAL_PLACEHOLDER: "Enter voucher code...",
  APPLY_MODAL_APPLY: "Apply",
  APPLY_MODAL_REMOVE: "Remove",
  APPLY_MODAL_CURRENT: "Currently applied:",
  APPLY_SUCCESS: "Discount code applied successfully!",
  APPLY_ERROR: "Could not apply discount code",
  ERROR_MIN_AMOUNT: "Order value does not meet the minimum requirement for this code",
  ERROR_ALREADY_APPLIED: "This order already has a discount code applied",
  REMOVE_SUCCESS: "Discount code removed",
  REMOVE_ERROR: "Could not remove discount code",
  LIST_AVAILABLE: "Available vouchers",
  LOADING_LIST: "Loading list...",
  EXPIRY_SHORT: "Exp:",
  EMPTY_LIST: "No vouchers available at this time",
  APPLIED: "Applied",
  GIFT_BADGE: "Free item",
  GIFT_LABEL: "Gift",
  GIFT_TITLE: "Free Item",
};
