import React from "react";

import { KDSOrderGrid } from "@/components/features/kds/KDSOrderGrid";
import { KDSQueueHeader } from "@/components/features/kds/KDSQueueHeader";
import { OrderItemStatus, OrderStatus, OrderType } from "@/types/enums";
import { Order } from "@/types/Order";

// Simulated Data for KDS Layout matching the Stitch design
const MOCK_ORDERS: Order[] = [
  {
    orderId: "o1",
    orderCode: "ORD-098",
    orderType: OrderType.DineIn,
    status: OrderStatus.Serving,
    totalAmount: 0,
    isPriority: false,
    createdAt: new Date().toISOString(),
    orderItems: [
      {
        orderItemId: "oi1",
        orderId: "o1",
        menuItemId: "m1",
        itemCodeSnapshot: "M1",
        itemNameSnapshot: "Gà Nướng Mật Ong",
        stationSnapshot: "HOT",
        status: OrderItemStatus.Cooking,
        quantity: 2,
        unitPriceSnapshot: 0,
        itemNote: "Da giòn",
        createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
      },
      {
        orderItemId: "oi2",
        orderId: "o1",
        menuItemId: "m2",
        itemCodeSnapshot: "M2",
        itemNameSnapshot: "Cơm Tấm Sườn Bì",
        stationSnapshot: "HOT",
        status: OrderItemStatus.Preparing,
        quantity: 1,
        unitPriceSnapshot: 0,
        itemNote: "Thêm sườn - return",
        createdAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
      },
      {
        orderItemId: "oi3",
        orderId: "o1",
        menuItemId: "m3",
        itemCodeSnapshot: "M3",
        itemNameSnapshot: "Canh Khổ Qua",
        stationSnapshot: "HOT",
        status: OrderItemStatus.Cooking,
        quantity: 1,
        unitPriceSnapshot: 0,
        createdAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
      },
      {
        orderItemId: "oi4",
        orderId: "o1",
        menuItemId: "m4",
        itemCodeSnapshot: "M4",
        itemNameSnapshot: "Trà Đá",
        stationSnapshot: "BAR",
        status: OrderItemStatus.Cooking,
        quantity: 3,
        unitPriceSnapshot: 0,
        itemNote: "Nhiều đá",
        createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
      },
    ],
  },
  {
    orderId: "o2",
    orderCode: "ORD-102",
    orderType: OrderType.DineIn,
    status: OrderStatus.Serving,
    totalAmount: 0,
    isPriority: false,
    createdAt: new Date().toISOString(),
    orderItems: [
      {
        orderItemId: "oi5",
        orderId: "o2",
        menuItemId: "m5",
        itemCodeSnapshot: "M5",
        itemNameSnapshot: "Trà Chanh Giã Tay",
        stationSnapshot: "BAR",
        status: OrderItemStatus.Cooking,
        quantity: 4,
        unitPriceSnapshot: 0,
        itemNote: "Ít đá",
        createdAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
      },
      {
        orderItemId: "oi6",
        orderId: "o2",
        menuItemId: "m6",
        itemCodeSnapshot: "M6",
        itemNameSnapshot: "Salad Ức Gà",
        stationSnapshot: "COLD",
        status: OrderItemStatus.Cooking,
        quantity: 1,
        unitPriceSnapshot: 0,
        itemNote: "nhiều rau",
        createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
      },
    ],
  },
  {
    orderId: "o3",
    orderCode: "ORD-105",
    orderType: OrderType.DineIn,
    status: OrderStatus.Serving,
    totalAmount: 0,
    isPriority: false,
    createdAt: new Date().toISOString(),
    orderItems: [
      {
        orderItemId: "oi7",
        orderId: "o3",
        menuItemId: "m7",
        itemCodeSnapshot: "M7",
        itemNameSnapshot: "Bánh Mì Chảo Đặc Biệt",
        stationSnapshot: "HOT",
        status: OrderItemStatus.Cooking,
        quantity: 3,
        unitPriceSnapshot: 0,
        itemNote: "Ít pate",
        createdAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
      },
      {
        orderItemId: "oi8",
        orderId: "o3",
        menuItemId: "m8",
        itemCodeSnapshot: "M8",
        itemNameSnapshot: "Sữa Đậu Nành",
        stationSnapshot: "BAR",
        status: OrderItemStatus.Cooking,
        quantity: 3,
        unitPriceSnapshot: 0,
        itemNote: "Ít đường",
        createdAt: new Date(Date.now() - 1000 * 60 * 6).toISOString(),
      },
    ],
  },
  {
    orderId: "o4",
    orderCode: "ORD-108",
    orderType: OrderType.DineIn,
    status: OrderStatus.Serving,
    totalAmount: 0,
    isPriority: false,
    createdAt: new Date().toISOString(),
    orderItems: [
      {
        orderItemId: "oi9",
        orderId: "o4",
        menuItemId: "m9",
        itemCodeSnapshot: "M9",
        itemNameSnapshot: "Phở Bò Tái Lăn",
        stationSnapshot: "HOT",
        status: OrderItemStatus.Cooking,
        quantity: 2,
        unitPriceSnapshot: 0,
        itemNote: "Nhiều hành",
        createdAt: new Date(Date.now() - 1000 * 60 * 9).toISOString(),
      },
      {
        orderItemId: "oi10",
        orderId: "o4",
        menuItemId: "m10",
        itemCodeSnapshot: "M10",
        itemNameSnapshot: "Quẩy Giòn",
        stationSnapshot: "HOT",
        status: OrderItemStatus.Cooking,
        quantity: 1,
        unitPriceSnapshot: 0,
        createdAt: new Date(Date.now() - 1000 * 60 * 4).toISOString(),
      },
      {
        orderItemId: "oi11",
        orderId: "o4",
        menuItemId: "m11",
        itemCodeSnapshot: "M11",
        itemNameSnapshot: "Nước Cam",
        stationSnapshot: "BAR",
        status: OrderItemStatus.Cooking,
        quantity: 1,
        unitPriceSnapshot: 0,
        createdAt: new Date(Date.now() - 1000 * 60 * 11).toISOString(),
      },
    ],
  },
  {
    orderId: "o5",
    orderCode: "ORD-110",
    orderType: OrderType.Takeaway,
    status: OrderStatus.Serving,
    totalAmount: 0,
    isPriority: true,
    createdAt: new Date().toISOString(),
    orderItems: [
      {
        orderItemId: "oi12",
        orderId: "o5",
        menuItemId: "m12",
        itemCodeSnapshot: "M12",
        itemNameSnapshot: "Bún Chả Hà Nội",
        stationSnapshot: "HOT",
        status: OrderItemStatus.Cooking,
        quantity: 3,
        unitPriceSnapshot: 0,
        itemNote: "nhiều chả",
        createdAt: new Date().toISOString(),
      },
    ],
  },
  {
    orderId: "o6",
    orderCode: "ORD-112",
    orderType: OrderType.DineIn,
    status: OrderStatus.Serving,
    totalAmount: 0,
    isPriority: false,
    createdAt: new Date().toISOString(),
    orderItems: [
      {
        orderItemId: "oi13",
        orderId: "o6",
        menuItemId: "m13",
        itemCodeSnapshot: "M13",
        itemNameSnapshot: "Cafe Muối",
        stationSnapshot: "BAR",
        status: OrderItemStatus.Ready,
        quantity: 2,
        unitPriceSnapshot: 0,
        createdAt: new Date().toISOString(),
      },
    ],
  },
  {
    orderId: "o7",
    orderCode: "ORD-115",
    orderType: OrderType.Takeaway,
    status: OrderStatus.Serving,
    totalAmount: 0,
    isPriority: false,
    createdAt: new Date().toISOString(),
    orderItems: [
      {
        orderItemId: "oi14",
        orderId: "o7",
        menuItemId: "m14",
        itemCodeSnapshot: "M14",
        itemNameSnapshot: "Phở Gà Lá Chanh",
        stationSnapshot: "HOT",
        status: OrderItemStatus.Cooking,
        quantity: 1,
        unitPriceSnapshot: 0,
        createdAt: new Date().toISOString(),
      },
    ],
  },
  {
    orderId: "o8",
    orderCode: "ORD-120",
    orderType: OrderType.DineIn,
    status: OrderStatus.Serving,
    totalAmount: 0,
    isPriority: true,
    createdAt: new Date().toISOString(),
    orderItems: [
      {
        orderItemId: "oi15",
        orderId: "o8",
        menuItemId: "m15",
        itemCodeSnapshot: "M15",
        itemNameSnapshot: "Lẩu Thái Hải Sản Siêu To Khổng Lồ",
        stationSnapshot: "HOT",
        status: OrderItemStatus.Cooking,
        quantity: 1,
        unitPriceSnapshot: 0,
        itemNote: "Nhiều tôm, mực, cá, rau, nấm, trứng, đậu phụ, thịt bò",
        createdAt: new Date().toISOString(),
      },
      {
        orderItemId: "oi16",
        orderId: "o8",
        menuItemId: "m16",
        itemCodeSnapshot: "M16",
        itemNameSnapshot: "Tôm Sú Nướng",
        stationSnapshot: "HOT",
        status: OrderItemStatus.Cooking,
        quantity: 12,
        unitPriceSnapshot: 0,
        createdAt: new Date().toISOString(),
      },
      {
        orderItemId: "oi17",
        orderId: "o8",
        menuItemId: "m17",
        itemCodeSnapshot: "M17",
        itemNameSnapshot: "Cơm Chiên Hải Sản",
        stationSnapshot: "HOT",
        status: OrderItemStatus.Cooking,
        quantity: 2,
        unitPriceSnapshot: 0,
        createdAt: new Date().toISOString(),
      },
      {
        orderItemId: "oi18",
        orderId: "o8",
        menuItemId: "m18",
        itemCodeSnapshot: "M18",
        itemNameSnapshot: "Rau Muống Xào Tỏi",
        stationSnapshot: "HOT",
        status: OrderItemStatus.Cooking,
        quantity: 1,
        unitPriceSnapshot: 0,
        createdAt: new Date().toISOString(),
      },
      {
        orderItemId: "oi19",
        orderId: "o8",
        menuItemId: "m19",
        itemCodeSnapshot: "M19",
        itemNameSnapshot: "Trà Đá",
        stationSnapshot: "BAR",
        status: OrderItemStatus.Cooking,
        quantity: 4,
        unitPriceSnapshot: 0,
        createdAt: new Date().toISOString(),
      },
    ],
  },
  {
    orderId: "o9",
    orderCode: "ORD-125",
    orderType: OrderType.DineIn,
    status: OrderStatus.Serving,
    totalAmount: 0,
    isPriority: false,
    createdAt: new Date().toISOString(),
    orderItems: [
      {
        orderItemId: "oi20",
        orderId: "o9",
        menuItemId: "m20",
        itemCodeSnapshot: "M20",
        itemNameSnapshot: "Bún Đậu Mắm Tôm",
        stationSnapshot: "HOT",
        status: OrderItemStatus.Cooking,
        quantity: 2,
        unitPriceSnapshot: 0,
        createdAt: new Date().toISOString(),
      },
    ],
  },
  {
    orderId: "o10",
    orderCode: "ORD-128",
    orderType: OrderType.Takeaway,
    status: OrderStatus.Serving,
    totalAmount: 0,
    isPriority: false,
    createdAt: new Date().toISOString(),
    orderItems: [
      {
        orderItemId: "oi21",
        orderId: "o10",
        menuItemId: "m21",
        itemCodeSnapshot: "M21",
        itemNameSnapshot: "Bánh Mì Thịt Nướng",
        stationSnapshot: "HOT",
        status: OrderItemStatus.Cooking,
        quantity: 5,
        unitPriceSnapshot: 0,
        createdAt: new Date().toISOString(),
      },
    ],
  },
  {
    orderId: "o11",
    orderCode: "ORD-132",
    orderType: OrderType.DineIn,
    status: OrderStatus.Serving,
    totalAmount: 0,
    isPriority: false,
    createdAt: new Date().toISOString(),
    orderItems: [
      {
        orderItemId: "oi22",
        orderId: "o11",
        menuItemId: "m22",
        itemCodeSnapshot: "M22",
        itemNameSnapshot: "Mì Ý Carbonara",
        stationSnapshot: "HOT",
        status: OrderItemStatus.Cooking,
        quantity: 1,
        unitPriceSnapshot: 0,
        createdAt: new Date().toISOString(),
      },
    ],
  },
  {
    orderId: "o12",
    orderCode: "ORD-135",
    orderType: OrderType.DineIn,
    status: OrderStatus.Serving,
    totalAmount: 0,
    isPriority: true,
    createdAt: new Date().toISOString(),
    orderItems: [
      {
        orderItemId: "oi23",
        orderId: "o12",
        menuItemId: "m23",
        itemCodeSnapshot: "M23",
        itemNameSnapshot: "Pizza Hải Sản",
        stationSnapshot: "HOT",
        status: OrderItemStatus.Cooking,
        quantity: 2,
        unitPriceSnapshot: 0,
        createdAt: new Date().toISOString(),
      },
    ],
  },
];

// Generate queue orders for header
const MOCK_QUEUE_ORDERS: Order[] = [
  { ...MOCK_ORDERS[2], orderCode: "105" }, // ORD-105 -> 105
  { ...MOCK_ORDERS[3], orderCode: "108" },
  { orderId: "q1", orderCode: "110" } as Order,
  { orderId: "q2", orderCode: "112" } as Order,
  { orderId: "q3", orderCode: "115" } as Order,
  { orderId: "q4", orderCode: "118" } as Order,
  { orderId: "q5", orderCode: "120" } as Order,
  { orderId: "q6", orderCode: "125" } as Order,
];

// FFE-PERF: Using Server Component for page data logic
export default async function KDSDashboardPage() {
  // Mock fetching data
  const activeOrders = MOCK_ORDERS;
  const queueOrders = MOCK_QUEUE_ORDERS;

  // Format current time for display
  const now = new Date();
  const timeString = `${now.getHours().toString().padStart(2, "0")}:${now.getMinutes().toString().padStart(2, "0")}`;

  return (
    <>
      <KDSQueueHeader queueOrders={queueOrders} currentTime={timeString} />
      <KDSOrderGrid orders={activeOrders} />
    </>
  );
}
